[AN] feat: 멍개 리스트 기능 구현
woowacourse-teams/2024-friendogly pull request #104
Opened 2024-07-18 01:44 UTC by jinuemong

## 이슈
- close #20 

## 개발 사항
- 멍개 리스트 기능 구현하였습니다.
- concatAdapter를 활용해서 중첩 리싸이클러뷰를 구현하였습니다.

# 전달 사항 (없으면 삭제해 주세요)
- 필터 기능은 생각보다 뎁스가 많아서 별도 이슈파겠습니다 ~

2024-07-18 07:05 UTC, dpcks0509 submitted a review, later dismissed
고생했어요!

2024-07-18 08:30 UTC, gaeun5744 requested changes

2024-07-18 08:30 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/group/list/GroupListBindingAdapters.kt
> +private const val UNPARTICIPABLE_NAME = "모집완료"
strings.xml에 빼주세요!!

2024-07-18 08:30 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/group/list/GroupListBindingAdapters.kt
> +}
strings.xml의 format 기능대신 이렇게 하는 이유가 있을까요..?

2024-07-18 08:30 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/group/list/model/groupfilter/GroupFilter.kt
> +        class NeutralizingMale : GenderFilter(NEUTRALIZING_MALE_NAME)
별 다른 데이터를 저장하지 않는다면 `data object`를 써도 좋을거 같아요!!

2024-07-18 08:30 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/group/list/model/groupfilter/GroupFilter.kt
> +        private const val BIG_DOG_NAME = "대형견"
이것도 strings.xml 에 빼주세요!!

2024-07-18 09:37 UTC, junjange requested changes

2024-07-18 09:37 UTC, junjange commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/group/list/adapter/group/GroupViewHolder.kt
> +        val filterAdapter = FilterAdapter()
`bind()`가 될 때마다 `FilterAdapter()`를 생성하고 있어서 효율적이지 못한 것 같습니다.

2024-07-19 06:07 UTC, jinuemong commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/group/list/GroupListBindingAdapters.kt
> +private const val UNPARTICIPABLE_NAME = "모집완료"
네 수정해볼께요

2024-07-19 06:07 UTC, jinuemong commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/group/list/GroupListBindingAdapters.kt
> +}
format 방식을 활용 안했네요.. 수정하겠습니다 !

2024-07-19 06:17 UTC, jinuemong commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/group/list/model/groupfilter/GroupFilter.kt
> +        private const val BIG_DOG_NAME = "대형견"
이건 좀 어렵겠는데요,, 컨텍스트를 GroupFilter를 생성할 때마다 활용해야 합니다.

2024-07-19 06:17 UTC, jinuemong commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/group/list/adapter/group/GroupViewHolder.kt
> +        val filterAdapter = FilterAdapter()
Adapter에서 init을 통해 한 번만 생성되도록 하였습니다 !

2024-07-19 06:22 UTC, junjange submitted a review, later dismissed
고생하셨습니다 ~~👍

2024-07-19 06:25 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/group/list/model/groupfilter/GroupFilter.kt
> +        private const val BIG_DOG_NAME = "대형견"
아ㅠㅠ 그럼 어쩔수 없네요ㅠㅠ

2024-07-19 06:25 UTC, gaeun5744 submitted a review, later dismissed
고생하셨습니다!!

2024-07-19 06:49 UTC, closed without merging