[AN] feat: 멍멍 짖기 기능 구현
woowacourse-teams/2024-friendogly pull request #108
Opened 2024-07-18 05:21 UTC by dpcks0509

## 이슈
- close #29 close #30 close #31 close #32 

## 개발 사항
- 멍멍 짖기 ui (아직 미완성)
- 멍멍 짖기 현재 위치 이동
- 멍멍 짖기 마커 찍기
- 멍멍 짖기 마커 클릭시 강아지 상세 정보 보기

# 전달 사항
- 발자국 정보는 더미 데이터로 넣어뒀고, 나중에 서버 배포 되면 연결해서 정보 받아오도록 수정하겠습니다!

2024-07-18 12:17 UTC, junjange requested changes

2024-07-18 12:17 UTC, junjange commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/woof/WoofFragment.kt
> +//        mapView.onCreate(savedInstanceState)
필요없는 코드라면 지워주세요!!

2024-07-18 12:17 UTC, junjange commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/woof/WoofFragment.kt
> +        marker.height = 160
상수화를 하면 더 좋을 것 같아요

2024-07-18 12:17 UTC, junjange commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/woof/WoofFragment.kt
> +        binding.lifecycleOwner = viewLifecycleOwner
이미 BaseFrament에 작성되어 있는 코드입니다!

2024-07-18 12:17 UTC, junjange commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/utils/ParcelExtension.kt
> +}
어떤 코드인지 설명해주세요!!

2024-07-18 12:17 UTC, junjange commented on android/app/src/main/res/drawable/rect_orange700_fill_12.xml
> +    <solid android:color="#FF821E" />
orange700이라면 colos.xml에 정의 후 사용하면 좋을 것 같아요!

2024-07-19 01:00 UTC, jinuemong approved these changes

2024-07-19 01:00 UTC, jinuemong commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/MainActivity.kt
> +    private fun requestLocationPermissions() {
메인 액티비티에 코드 작성이 많아지면 코드가 지나치게 비대해질 수 있습니다
개인적인 의견이지만 최상위 함수로 분리해보는 것도 좋을 것 같아요

2024-07-19 01:00 UTC, jinuemong commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/woof/DogUiModel.kt
> +@Parcelize
이거 전달이 안된 것 같은데 parcelize 대신에 Serializable로 통일하기로 했습니다!

2024-07-19 01:00 UTC, jinuemong commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/woof/WoofBindingAdapters.kt
> +    spannableString.setSpan(
색상변경 코드인거죠? 굳💪

2024-07-19 01:00 UTC, jinuemong commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/woof/WoofFragment.kt
> +                    DogUiModel(
특정값(id or location) 전달해서 바텀시트 프레그먼트에서 find 함수를 활용하능 것이 좋아보입니다

이유 : 추후 서버 api와 맞추기 위함

2024-07-19 01:00 UTC, jinuemong commented on android/app/src/main/res/values/colors.xml
>      <color name="orange07">#FF821E</color>
중복코드!

2024-07-19 01:01 UTC, jinuemong commented
고생하셨습니다
직렬화 함수 부분만 수정하면 될 것 같아요!
다른부분은 고민해보시면 좋을 것 같습니다

2024-07-19 02:14 UTC, dpcks0509 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/woof/WoofFragment.kt
> +//        mapView.onCreate(savedInstanceState)
지웠어요!

2024-07-19 02:15 UTC, dpcks0509 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/woof/WoofFragment.kt
> +        marker.height = 160
상수화 했습니다!

2024-07-19 02:16 UTC, dpcks0509 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/woof/WoofFragment.kt
> +        binding.lifecycleOwner = viewLifecycleOwner
몰랐네요 삭제했습니다!

2024-07-19 02:22 UTC, dpcks0509 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/utils/ParcelExtension.kt
> +}
Fragment의 Bundle에 Parcelize한 모델을 쉽게 전달하기 위해 만든 코드인데 Serealize로 통일하기로 했다고 해서 삭제하겠습니다!

2024-07-19 02:24 UTC, dpcks0509 commented on android/app/src/main/res/drawable/rect_orange700_fill_12.xml
> +    <solid android:color="#FF821E" />
color.xml 에 이미 있어서 활용하도록 수정했습니다!

2024-07-19 02:27 UTC, dpcks0509 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/woof/WoofFragment.kt
> +                    DogUiModel(
memrId 전달하는 걸로 수정할게요!

2024-07-19 02:27 UTC, dpcks0509 commented on android/app/src/main/res/values/colors.xml
>      <color name="orange07">#FF821E</color>
삭제했어요!

2024-07-19 02:34 UTC, dpcks0509 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/MainActivity.kt
> +    private fun requestLocationPermissions() {
다음에 반영해볼게여!

2024-07-19 05:49 UTC, junjange approved these changes
고생하셨습니다~~👍

2024-07-19 06:31 UTC, gaeun5744 approved these changes
고생하셨어용!!

2024-07-19 06:54 UTC, merged