[BE] feat: club 도메인 추가
woowacourse-teams/2024-friendogly pull request #119
Opened 2024-07-18 10:41 UTC by jimi567

## 이슈
- #88 

## 개발 사항
- club 도메인
- 도메인 관련 VO 검증 로직

## 리뷰 요청 사항 (없으면 삭제해 주세요)
- 꼼꼼하게 봐주시면 감사하겠습니당.

# 전달 사항 (없으면 삭제해 주세요)
- 필터링 값 제외하여 구현

2024-07-18 10:59 UTC, takoyakimchi requested changes

2024-07-18 10:59 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/MemberCapacity.java
> +        }
예외 메시지에도 `MIN_CAPACITY_SIZE`, `MAX_CAPACITY_SIZE`를 사용할 수 있겠네요.

2024-07-18 10:59 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Status.java
> +}
```suggestion
public enum Status {

    OPEN,
    CLOSED;
}
```

2024-07-18 10:59 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Status.java
> +}
직관적인 네이밍도 좋을 것 같아요. `OPEN`, `CLOSED` 어떤가요?

2024-07-18 10:59 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +
- 이미지를 등록하지 않은 경우 null이 될 수도 있을 것 같아요.
- URL도 원시값 포장을 진행하면 어떨까요?

2024-07-18 10:59 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    private LocalDateTime createdAt;
```suggestion
    @Column(nullable = false)
    private LocalDateTime createdAt;
```

`LocalDateTime`을 사용하면 생략 가능하다고 하네요!

2024-07-18 10:59 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +
`ArrayList` 생성은 생성자에서 하는 것도 좋을 것 같아요

2024-07-18 10:59 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Content.java
> +            throw new FriendoglyException("내용은 1글자 이상 1000글자 이하로 작성해주세요.");
```suggestion
            throw new FriendoglyException(String.format("내용은 %d글자 이상 %d글자 이하로 작성해주세요.", MIN_CONTENT_LENGTH, MAX_CONTENT_LENGTH));
```

2024-07-18 10:59 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/club/domain/ContentTest.java
> +}
```suggestion
    }
}
```

2024-07-18 10:59 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/club/domain/MemberCapacityTest.java
> +    }
예외 메시지도 함께 검증해 봐도 좋을 것 같아요!

2024-07-18 11:02 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/MemberCapacity.java
> +        }
메세지 자체가 변하는게 아니라면, 관리 포인트를 줄일 수 있겠네요 .

2024-07-18 11:03 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Status.java
> +}
모집 중, 모집 종료 라는 의미로 해당 워딩을 사용했는데,
저희 입장에서는 OPEN , CLOSED도 이해하는데 큰 불편함이 없을 수 있겠네용

2024-07-18 11:03 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +
url의 경우 S3에 이미지 url을 저장하기 전까지 래핑 하지 않는 것으로 얘기가 나와서 이대로 냅두었어요

2024-07-18 11:08 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +
헉 저도 유의해서 개발할게요 👍

2024-07-18 11:08 UTC, ehtjsv2 requested changes
굿굿

2024-07-18 11:08 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    private List<Member> participantMembers = new ArrayList<>();
양방향 의존관계를 2레벨에 공부했었는데, 안쓰고 해보는 것은 어떨까요
[JPA 양방향 연관관계 관련하여 질문 드립니다.](https://www.inflearn.com/questions/747142/jpa-%EC%96%91%EB%B0%A9%ED%96%A5-%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84-%EA%B4%80%EB%A0%A8%ED%95%98%EC%97%AC-%EC%A7%88%EB%AC%B8-%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4) <- 답변이 맛있더라구요
[양방향 의존관계-2](https://velog.io/@kyle/%EB%A7%88%EC%BC%93-%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%84%A4%EA%B3%84-1.-%EC%9C%A0%EC%9D%98%EC%A0%90)
위브가 양방향 의존관계를 써야했던 이유도 궁금하네요~!
남의 도메인을 참조해야하는 것이 걸려서인가요?

2024-07-18 11:08 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Title.java
> +        if (StringUtils.isBlank(title) || title.length() > MAX_TITLE_LENGTH) {
`StringUtils.isBlank()` 👍

2024-07-18 11:16 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    private LocalDateTime createdAt;
저희 배포 환경이 Mysql이라 , TIMESTAMP 타입으로 저장하려고 저렇게 명시해주긴 했어요.
제가 알기론 생략하면 Mysql에서  DATETIME으로 저장하는걸로 알고 있어서요
근데 좀 찾아보니깐 LocalDateTIme은 @Colume으로 지정해줘야된다고하네여 수정해야될 것 같아요

2024-07-18 11:19 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Title.java
> +        if (StringUtils.isBlank(title) || title.length() > MAX_TITLE_LENGTH) {
오 좋네요

2024-07-18 11:26 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    private LocalDateTime createdAt;
좀 더 고민해보니깐 지금 단계에서 DATETIME으로 저장하나 타임스템프쓰나 별 차이 없는 것 같아서 지우도록 하겠습니당

2024-07-18 11:52 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    private List<Member> participantMembers = new ArrayList<>();
양방향 의존 관계보다 곰곰히 생각해보니 
Club : Member(pets) 관계가 ManyToMany 였어요.
수정할게요.  리뷰 덕분에 리마인드 됐네요.

2024-07-18 11:54 UTC, jimi567 commented on backend/src/test/java/com/woowacourse/friendogly/club/domain/MemberCapacityTest.java
> +    }
이 부분도 다같이 얘기해보면 좋을 것 같아요.

예외 메세지는 기능적으로 중요한 부분은 아니라서 해당 메세지로 인해서 테스트가 깨지는건 불필요하다. vs 어떤 경우로 해당 예외가 나왔는데 검증해야된다 갈리는 것 같아요.

2024-07-18 12:23 UTC, J-I-H-O reviewed
고생했어요 위브~ 같이 얘기 나눠봐요

2024-07-18 12:23 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +
트레 의견에 동의합니다. 이미지 URL은 nullable로 두는게 맞을 것 같아요.

2024-07-18 12:23 UTC, J-I-H-O commented on backend/src/test/java/com/woowacourse/friendogly/club/domain/ContentTest.java
> +
😊👍

2024-07-18 15:40 UTC, takoyakimchi submitted a review, later dismissed
고생 많았습니다 👍

2024-07-19 02:56 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +
아 필드 초기화가 안전하다는 말도 있네요.

2024-07-19 05:54 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +
저는 생성자 초기화에 한표

2024-07-20 02:41 UTC, takoyakimchi approved these changes, later dismissed
사소한 코멘트 몇 개 남겨 보았습니다
고생했어요

2024-07-20 02:41 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Status.java
> +}
```suggestion
    CLOSED;
}
```

2024-07-20 02:41 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/club/domain/ContentTest.java
> +
경계값 테스트 해도 좋을 것 같네요.

2024-07-20 02:41 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/club/domain/TitleTest.java
> +
여기도 ParameterizedTest로 경계값 테스트 하면 좋겠어요

2024-07-20 02:50 UTC, takoyakimchi approved these changes, later dismissed

2024-07-20 04:53 UTC, ehtjsv2 approved these changes, later dismissed
백엔드-리뷰방 알람만 켜져있어서 늦었네요,,잘봤습니다~!

2024-07-20 04:53 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Content.java
> +    @Lob
저장된 데이터의 크기가 크지않더라도 조회할때 현저히 속도가 떨어지는 문제가 생기는 사람도 있다는데, 혹시라도 우리도 이러한 문제 접하게 되면 해결책을 찾아봅시다~!
모임 목록 조회에는 content가 필요하지않으니 lazy해도 좋겠네요!

2024-07-20 05:08 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Content.java
> +    @Lob
이 부분 저도 고민인데 따로 테이블 뺀게 없어서 lazy 비슷한 기능을 활용할 수 있는지 모르겠네요.ㅠㅠ

2024-07-20 05:09 UTC, jimi567 commented on backend/src/test/java/com/woowacourse/friendogly/club/domain/ContentTest.java
> +
예외 터지는 부분에서 경계 테스트해서 충분하다고 생각했는데 가능한 영역 내부에서 테스트하면 더 맛있을 것 같아요, 굿

2024-07-20 07:59 UTC, closed without merging