[BE] refactor: 반려견 도메인 리팩토링
woowacourse-teams/2024-friendogly pull request #120
Opened 2024-07-18 11:39 UTC by J-I-H-O

## 이슈
- close #107 

## 개발 사항
- 반려견 도메인 리팩토링

# 전달 사항
- 중성화 여부 성별로 통합했습니다.
- Pet 도메인이 Member를 가지고 있는게 맞는지 아직 잘 모르겠네요. memberId만 갖도록 했을 때 문제가 있을까요?

2024-07-18 12:33 UTC, ehtjsv2 submitted a review, later dismissed
굿굿

2024-07-18 12:33 UTC, ehtjsv2 commented on backend/src/test/java/com/woowacourse/friendogly/pet/domain/GenderTest.java
> +}
intelliJ에서 EOF방지하는 기능 사용하면 좋겠네요~!

2024-07-18 12:33 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/pet/domain/Gender.java
> +            return valueOf(gender);
굿 valueOf쓰니까 훨씬 갈견했네요

2024-07-18 12:33 UTC, ehtjsv2 commented on backend/src/test/java/com/woowacourse/friendogly/pet/domain/SizeTypeTest.java
> +}
😯

2024-07-18 12:33 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/pet/domain/Gender.java
> +            return valueOf(gender);
소문자로 들어와도 먹히려나요?

2024-07-18 12:48 UTC, takoyakimchi requested changes
고생하셨어요!!

2024-07-18 12:48 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/pet/controller/PetController.java
> +        return ResponseEntity.ok(response);
```suggestion
    @GetMapping("/{petId}")
    public ResponseEntity<FindPetResponse> findById(@PathVariable Long petId) {
        FindPetResponse response = petQueryService.findById(petId);
        return ResponseEntity.ok(response);
```

바로 밑에 `memberId`를 쓰는 메서드가 있어서 헷갈릴 것 같은데, 어떠신가요?

2024-07-18 12:48 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/pet/domain/Pet.java
> +            throw new FriendoglyException(String.format("이름은 1자 이상, %d자 이하여야 합니다.", MAX_NAME_LENGTH));
`MIN_NAME_LENGTH`도 변경 가능성이 있을 것 같은데
나중에 원시값 포장할 때 상수화도 같이 해보면 어떨까요?

2024-07-18 12:48 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/pet/domain/Pet.java
> +
어떤 정규식인지 간략하게 설명이 있으면 더 좋을 것 같아요.
주석을 예외적으로 허용하는 방향으로 가도 되겠네요.

2024-07-18 12:48 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/pet/service/PetCommandService.java
> +        Pet pet = request.toEntity(member);
member를 entity로 변환(toEntity)했더니 pet이 되는 건 좀 어색한 것 같아요.
`request`에 있는 정보랑 `member`를 이용해서 이 메서드 안에서 직접 `Pet`을 생성해봐도 좋을 것 같아요.

2024-07-18 12:48 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/pet/controller/PetControllerTest.java
> +                "내맘대로 URL주소 지정하기~"
```suggestion
                "SMALL",
                "FEMALE_NEUTERED",
                "ftp://www.google.com"
```
이런 테스트 케이스도 좋겠네요

2024-07-18 12:48 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/pet/domain/GenderTest.java
> +}
```suggestion
                .isExactlyInstanceOf(FriendoglyException.class)
                .hasMessage("존재하지 않는 Gender 입니다.");
    }
}

```

2024-07-18 12:48 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/pet/domain/PetTest.java
> +    @ParameterizedTest
어차피 `@ParameterizedTest`를 쓸 거라면 `@NullAndEmptySource`도 적용해 봐도 좋을 것 같네요.

2024-07-18 12:48 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/pet/domain/SizeTypeTest.java
> +}
```suggestion
    }
}

```

IntelliJ의 저장 시 자동으로 EOF 처리해주는 옵션을 사용해 봐도 좋을 것 같아요.

2024-07-18 15:42 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/pet/domain/Gender.java
> +            return valueOf(gender);
이왕 Enum 클래스에 테스트를 만든 김에 테스트 코드를 작성해 봐도 되겠네요

2024-07-18 15:43 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/pet/domain/SizeTypeTest.java
> +}
`isExactlyInstanceOf` 👍

2024-07-19 01:58 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/pet/domain/Gender.java
> +            return valueOf(gender);
저도 생성로직 정도는 테스트해봐도 좋을 것 같아요. 불필요하다면 굳이 안해도 됩니다.

2024-07-19 01:59 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/pet/domain/Pet.java
> +
@takoyakimchi 저는 상수 이름으로도 충분히 설명 하고 있다고 생각하는데, 어떠신가요?

2024-07-19 02:01 UTC, jimi567 commented on backend/src/test/java/com/woowacourse/friendogly/pet/domain/SizeTypeTest.java
> +}
https://jojoldu.tistory.com/673

2024-07-19 02:06 UTC, jimi567 submitted a review, later dismissed
고생하셨어요 땡이~

2024-07-19 02:06 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/pet/domain/Pet.java
> +
저희 빌더패턴 쓰기로 했고, 생성자에서 기본타입으로 받고 생성자 내부에서 VO로 감싸는것도 좋을 것 같은데 어떠신가요?

그렇게 되면 도메인 내부에서 null 체크 등의 코드도 줄일 수 있을 것 같아요.

2024-07-19 04:17 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/pet/domain/Gender.java
> +            return valueOf(gender);
@ehtjsv2 
대문자로만 입력하는 것이 API 스펙으로 정해둔 값이니 그 형식에 맞추어 보내줘야 하는 게 맞는 듯 합니다.
방어적인건 좋지만 과하다는 생각이 들어서요!

2024-07-19 04:19 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/pet/controller/PetController.java
> +        return ResponseEntity.ok(response);
저는 현재 수준에서는 괜찮아보여요. 추후에 메서드가 많아졌을 때 다시 살펴보도록 하겠습니당!

2024-07-19 04:20 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/pet/domain/Pet.java
> +            throw new FriendoglyException(String.format("이름은 1자 이상, %d자 이하여야 합니다.", MAX_NAME_LENGTH));
정책상 바뀔 여지가 있어보이네요 😄
우선 상수로 빼두되, 로직은 그대로 유지할게요!

2024-07-19 04:57 UTC, J-I-H-O commented
URL 검증 관련 부분은 S3에서 URL 응답이 어떻게 오는지 보고 손봐야 할 것 같습니다.

2024-07-19 05:18 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/pet/service/PetCommandService.java
> +        Pet pet = request.toEntity(member);
> member를 entity로 변환(toEntity)했더니 pet이 되는 건 좀 어색한 것 같아요.

member를 entity로 변환하니 pet이 되는 것이 아니라, 
Pet request DTO를 Pet entity로 변환(toEntity)할 때 member가 구성 요소로써 필요한 것이라고 생각해주시면 좋을 것 같아요!

Pet 도메인이 이미 Member에 강하게 의존하기 때문에 Pet DTO가 Member 도메인에 의존하는 것 정도는 문제되지 않는다고 생각해요.
메서드명을 `SavePetRequest.toEntityWith(member)` 라고 변경해주면 조금 더 명확하게 느껴질까요!!?

2024-07-19 05:22 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/pet/dto/request/SavePetRequest.java
>          Long memberId,
0이 들어오면 `@Positive` 검증은 어떻게 될까요?

2024-07-19 05:25 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/pet/dto/request/SavePetRequest.java
>          Long memberId,
`@Positive` 는 양수만 허용하는걸로 알고있어요. 즉  `@Valid` 검증에 걸리겠지용!?
0과 양수를 검증하기 위한 `@PositiveOrZero` 어노테이션이 따로 있습니다!

2024-07-19 06:36 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/pet/dto/request/SavePetRequest.java
>          Long memberId,
혹쉬 테스트 추가를 의도하신거라면 추가 완료했습니다!

2024-07-19 06:57 UTC, takoyakimchi submitted a review, later dismissed

2024-07-19 06:57 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/pet/dto/request/SavePetRequest.java
>          Long memberId,
`음수일 수 없습니다.`라는 메시지를 수정해 보면 좋을 것 같다는 의도로 남겨봤어요!

2024-07-19 06:57 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/pet/domain/Pet.java
> +
충분히 검증이 되고 있다면 넘어가도 괜찮을 것 같아요.

2024-07-19 06:57 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/pet/domain/Pet.java
> +
저도 이 방식이 좋아보여요

2024-07-19 06:57 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/pet/service/PetCommandService.java
> +        Pet pet = request.toEntity(member);
제가 컨벤션을 안 지키고 있었네요
그래도 네이밍 변경은 필요할 것 같아요

2024-07-19 07:56 UTC, takoyakimchi approved these changes
고생 많으셨어요

2024-07-19 08:07 UTC, jimi567 approved these changes
고생하셨어요 땡이

2024-07-19 08:07 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/pet/domain/BirthDate.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
어노테이션 선언 순서 컨벤션 정해졌어요.

2024-07-19 08:51 UTC, ehtjsv2 approved these changes

2024-07-19 08:51 UTC, merged