[BE] feat: 발자국 기능 추가
woowacourse-teams/2024-friendogly pull request #122
Opened 2024-07-18 12:08 UTC by takoyakimchi

## 이슈
- #84 

## 개발 사항

- 발자국은 30초마다 찍을 수 있다.
- 발자국에 image url 필드 추가(일단은 이미지가 1장이라고 생각하고 구현)
- 자신이 마지막으로 발자국 찍은 시간 조회 API 구현
  - 안드로이드에서 오른쪽 아래 시간초(쿨타임)를 렌더링할 때 필요해요.

## 리뷰 요청 사항
- 

## 전달 사항
- 앨범 기능이 확정되고 나서 기능을 더 붙여야 할 것 같아요.
- 발자국에 이미지가 몇 장까지 가능한지 회의로 정해 보아요.
- AWS S3 연동 관련 코드가 완성되고 나면 이미지 업로드 관련 작업할게요.
- 아직 다른 기능이 완성되지 않아 작성하지 못한 코드는 주석을 남겨 놓았어요.

2024-07-19 02:34 UTC, jimi567 reviewed
리뷰 남겼어요~~

2024-07-19 02:34 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/controller/FootprintController.java
> +    ) {
해당 핸들러는 이미지 업데이트를 위한 것 같은데
@PostMapping을 사용한 이유가 있을까요?

@PathVariable이랑 ModelAttribute를 같이 받기 보단 하나의 requestBody로 받으면 어떨까 싶은데 저렇게 한 이유가 있을까 궁금해요!!

2024-07-19 02:34 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Footprint.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
꼼꼼함 굿

2024-07-19 02:34 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Footprint.java
> +    }
해당 메서드는 jpa 변경감지를 위해 만들어진 setter같은데,
변경 감지를 위해 다른 로직이 들어 갈 가능성도 있으니, 기존의 setter와 목적과 의도가 조금 다르다고 생각합니다. update~ 또는 change~ 와 같은 형태로 메소드명을 통일하면 어떨까 싶어요

2024-07-19 02:34 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/request/SaveFootprintRequest.java
> +    Long memberId,
이왕이면 @Positive 검증도 해주면 좋겠네요

2024-07-19 02:34 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/response/FindMyLatestFootprintTimeResponse.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime createdAt
이 부분 날짜, 시간 형식에 대한 포맷팅 코드가 추가된 이후 잊지 않고 삭제해주세염

2024-07-19 02:34 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
>  @RequiredArgsConstructor
!!!

2024-07-19 02:34 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
> +    }
해당 로직은 foorPrint 도메인 내부에 내려줄 수 있을 것 같은데 어떠신가요?

2024-07-19 02:34 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintQueryService.java
> +            .map(footprint -> FindNearFootprintResponse.from(footprint, memberId))
어떤건 정적팩토리메소드를 사용하고 어떤건 생성자를 통해 응답 DTO를 생성하는데, 일관성이 유지되면 좋을 것 같아요.

일단 저희 팀은 생성자로 만드는 걸 컨벤션으로 정했었던 것 같아요.!

+ 매개변수가 2개 이상인 정적팩토리메소드의 네이밍 컨벤션은 일반적으로 of를 썼던 것 같아요.

2024-07-19 02:34 UTC, jimi567 commented on backend/src/test/java/com/woowacourse/friendogly/footprint/service/FootprintCommandServiceTest.java
> +
저희 JPA 사용하고 있는데 초기 데이터를 jdbcTemplate 사용해서 넣어주는 이유가 있을까요?

2024-07-19 04:08 UTC, J-I-H-O requested changes
트레 고생하셨어요~ 리뷰 남겼으니 확인 부탁드려요!

2024-07-19 04:08 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/request/FindNearFootprintRequest.java
```suggestion
    double longitude
) {
```

2024-07-19 04:08 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/request/SaveFootprintRequest.java
> +    double longitude) {
```suggestion
    double longitude
) {
```

2024-07-19 04:08 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/controller/FootprintController.java
> +    public ResponseEntity<List<FindNearFootprintResponse>> findNear(@Valid FindNearFootprintRequest request) {
List를 반환할 때에는 ResponseEntity를 생략해도 좋을 것 같아요.
추후 response 객체로 감쌀 것을 고려했을 때, 반환 타입이 너무 길어질 것 같습니다.

2024-07-19 04:08 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
> +            LocalDateTime.now().minusSeconds(FootprintCommandService.FOOTPRINT_COOLDOWN)
```suggestion
            LocalDateTime.now().minusSeconds(FOOTPRINT_COOLDOWN)
```

2024-07-19 04:08 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
>  @RequiredArgsConstructor
저희 컨벤션에서 `@RequiredArgsConstructor` 는 사용하지 않기로 했어요!

2024-07-19 04:08 UTC, J-I-H-O commented on backend/src/test/java/com/woowacourse/friendogly/footprint/domain/LocationTest.java
> +    @DisplayName("생성 실패 - 올바르지 않은 위도 범위")
```suggestion
    @DisplayName("위도 범위를 벗어난 값을 입력하는 경우 예외가 발생한다.")
```
`@DisplayName` 은 컨벤션에 맞춰 작성해주세요!

2024-07-19 04:08 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/response/FindNearFootprintResponse.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime createdAt,
`@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")` 가 없으면 어떤 형식으로 반환되나요?

2024-07-19 04:08 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/response/FindNearFootprintResponse.java
> +            memberId.equals(footprint.getMember().getId())
내 발자국인지 확인하는 로직은 도메인 로직 아닐까요? Footprint 도메인에 넣어주는 편이 좋겠습니다.

2024-07-19 04:08 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/response/FindNearFootprintResponse.java
> +            memberId.equals(footprint.getMember().getId())
추가로 이렇게 변경하면 DTO로 memberId를 넘겨주기보단, service에서 `footprint.isMine()` 메서드를 호출하고 DTO에는 그 결과값인 boolean을 넘겨주면 되겠어요.

2024-07-19 04:08 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintQueryService.java
>              .toList();
```java
return recentFootprints.stream()
        .filter(footprint -> footprint.isNear(currentLocation))
        .map(footprint -> FindNearFootprintResponse.from(footprint, footprint.isMine(memberId)))
        .toList();
```

위에서 말씀드린 방식으로 변경하면 이런식으로 변경되겠쭁?

2024-07-19 04:13 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/controller/FootprintController.java
> +    ) {
patch로 바꿔 봐도 좋겠네요.

2024-07-19 05:18 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/controller/FootprintController.java
> +    ) {
+ 파일을 받으려면 ModelAttribute를 써야 한다고 하더라구요. 이 부분은 S3 연동 잘 되는지에 따라 결정해야 할 것 같아요.

2024-07-19 05:18 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Footprint.java
> +    }
동의합니다 👍

2024-07-19 05:19 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/request/SaveFootprintRequest.java
> +    Long memberId,
좋아요!

2024-07-19 07:34 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/response/FindMyLatestFootprintTimeResponse.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime createdAt
TODO 써봐도 좋겠네요.

2024-07-19 07:43 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/request/FindNearFootprintRequest.java
아이고야

2024-07-19 07:44 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/request/SaveFootprintRequest.java
> +    double longitude) {
어익후야

2024-07-19 07:44 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/controller/FootprintController.java
> +    public ResponseEntity<List<FindNearFootprintResponse>> findNear(@Valid FindNearFootprintRequest request) {
제 생각은 좀 다르긴 한데 
일단 공통 응답을 만들고 생각해 보죠!

2024-07-19 07:44 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
> +            LocalDateTime.now().minusSeconds(FootprintCommandService.FOOTPRINT_COOLDOWN)
헉

2024-07-19 07:45 UTC, ehtjsv2 reviewed
고생하셨습니ㄷ

2024-07-19 07:54 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/response/FindNearFootprintResponse.java
> +            memberId.equals(footprint.getMember().getId())
좋은 생각이네요!

2024-07-19 08:53 UTC, ehtjsv2 submitted a review, later dismissed

2024-07-19 08:55 UTC, jimi567 approved these changes, later dismissed
반영 수고하셨슴다!!!!! 주말 화이팅

2024-07-19 23:49 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/response/FindNearFootprintResponse.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime createdAt,
```
{
    "createdAt": "2024-07-20T08:42:51.613518"
}
````

테스트 해보니 위와 같은 형태로 응답합니다. 소수점까지 함께 응답하네요

2024-07-19 23:49 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/response/FindNearFootprintResponse.java
> +            footprint.isCreatedBy(memberId)
이 부분 한 번만 다시 확인 부탁드릴게요!
DTO는 단순 데이터 전송의 책임만 가지는게 좋을 것 같아요.
도메인 로직 호출은 service에서 수행하고, DTO에는 그 결과값만 넣어주는게 좋겠어요.

2024-07-19 23:51 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/response/FindNearFootprintResponse.java
> +            footprint.isCreatedBy(memberId)
이것만 진행해주시고 DM 주시면 바로 어푸루부 가겠습니다!

2024-07-20 02:46 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/response/FindNearFootprintResponse.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime createdAt,
확인을 까먹고 있었네요
공통 포맷 작성할 때 다시 이야기해 보면 좋겠네요 :)

2024-07-20 02:46 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/response/FindNearFootprintResponse.java
> +            footprint.isCreatedBy(memberId)
DTO가 로직 호출하는 게 어색하네요~!~! 반영할게요 🙇‍♂️

2024-07-20 02:48 UTC, J-I-H-O approved these changes
고생 많으셨습니다!!

2024-07-20 04:36 UTC, ehtjsv2 approved these changes

2024-07-20 04:36 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/dto/response/FindNearFootprintResponse.java
> +            isMine
👍

2024-07-20 04:53 UTC, jimi567 approved these changes

2024-07-20 07:24 UTC, merged