[BE] 발자국 S3 연동, API 응답 일부 수정
woowacourse-teams/2024-friendogly pull request #195
Opened 2024-07-24 05:08 UTC by takoyakimchi

## 이슈
- #188 

## 개발 사항
- 발자국에 이미지 업로드 API 구현

## 리뷰 요청 사항
- **빠르게 리뷰 부탁드립니다.**

## 전달 사항
- 배포 후 Postman 등을 이용한 테스트 필수!!

2024-07-24 06:36 UTC, ehtjsv2 submitted a review, later dismissed
테스트도 더 추가됐네요~굳굳

2024-07-24 09:01 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
> +        if (!footprint.isCreatedBy(member.getId())) {
이건 무슨 차이인가용?

2024-07-24 09:01 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintQueryService.java
>      }
반려견을 가지고 있는지 여부는 왜 응답하는건가요!?

2024-07-24 09:51 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
> +        if (!footprint.isCreatedBy(member.getId())) {
별 차이는 없는데 이미 찾아진 `member`에서 id를 가져오는 게 더 확실한 값이라는 느낌이 들었어요!!!

2024-07-24 09:51 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintQueryService.java
>      }
채드 요청으로 넣었는데,
지도에 맨 처음 들어갔을 때 반려견이 없으면 발자국을 못 누르기 때문에 화면 렌더링 하려고 넣었어요~~

2024-07-24 10:03 UTC, J-I-H-O requested changes
트레~ 리뷰 남겼습니다! 확인 부탁드려요~

2024-07-24 10:03 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintQueryService.java
>      }
멍멍짖기 초기 화면에서 바로 호출하는 API 군용~
메서드명이나 클래스명을 좀 더 명확하게 바꿔봐도 좋겠어요.

2024-07-24 10:03 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintQueryService.java
> +        boolean hasPet = !petRepository.findByMemberId(memberId).isEmpty();
이부분은 exsistBy를 사용해도 되겠어요.
findBy를 사용하면 조건에 맞는 모든 row를 조회하지만, exsist는 조건에 맞는 row를 발견하면 탐색을 중단합니다.

2024-07-24 13:15 UTC, jimi567 submitted a review, later dismissed
고생하셨어용 트레 변경사항이 많지 않아서 읽고 이해하기 편했어요.
땡이 코멘트 반영하고 다시 요청주세욥

2024-07-25 03:37 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintQueryService.java
>      }
뷰에서 하는 동작을 메서드명에 명시하는 건 좀 애매할 것 같아서 일단은 dto 클래스명만 바꿀게요~
endpoint는 안드로이드 크루랑 이야기하고 나중에 바꿔야 할듯!!

2024-07-25 03:40 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintQueryService.java
> +        boolean hasPet = !petRepository.findByMemberId(memberId).isEmpty();
최고!!!

2024-07-25 03:46 UTC, J-I-H-O approved these changes
고생하셨습니다 트레~~~👍

2024-07-25 03:46 UTC, ehtjsv2 approved these changes

2024-07-25 03:59 UTC, merged