[BE] feat: Club 생성 참여 탈퇴 API
woowacourse-teams/2024-friendogly pull request #207
Opened 2024-07-24 17:59 UTC by jimi567

## 이슈
- #160 

## 개발 사항
- 모임 생성 API
- 모임 참여 API
- 모임 탈퇴 API
- 방장이 탈퇴하면, 가장 빨리 들어온 사람에게 자동 위임, 탈퇴 후 남은 인원이 없으면 모임 자동삭제

## 리뷰 요청 사항 (없으면 삭제해 주세요)
- 

# 전달 사항 (없으면 삭제해 주세요)
-

2024-07-25 02:36 UTC, takoyakimchi requested changes
복잡한 도메인 맡느라 고생 많으셨어요!!! 코멘트 몇 가지 남겨 보았습니다.

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/GlobalExceptionHandler.java
>                  .toList();
👍

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/controller/ClubController.java
> +    }
```suggestion
    @PostMapping
    public ResponseEntity<ApiResponse<SaveClubResponse>> save(
            @Auth Long memberId,
            @Valid @RequestBody SaveClubRequest request
    ) {
        SaveClubResponse response = clubCommandService.save(memberId, request);
        return ResponseEntity.created(URI.create("/clubs" + response.id())).body(ApiResponse.ofSuccess(response));
    }
```
개행~!~!

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    List<ClubPet> clubPets = new ArrayList<>();
```suggestion
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private Status status;
    
    @OneToMany(mappedBy = "club", orphanRemoval = true, cascade = CascadeType.ALL)
    List<ClubMember> clubMembers = new ArrayList<>();

    @OneToMany(mappedBy = "club", orphanRemoval = true, cascade = CascadeType.ALL)
    List<ClubPet> clubPets = new ArrayList<>();
```
여기도 개행이요

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    private void validateAlreadyExists(Member newMember) {
```suggestion
    }

    private void validateAlreadyExists(Member newMember) {
```

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/ClubMember.java
>      }
정적 팩토리를 사용할 거라면 생성자를 private으로 막으면 어떨까요?

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/dto/request/SaveClubRequest.java
> +        Set<SizeType> allowedSizes,
```suggestion
        @NotEmpty(message = "모임에 참여가능한 성별을 선택해주세요.")
        Set<Gender> allowedGenders,
        
        @NotEmpty(message = "모임에 참여가능한 댕댕이 사이즈를 선택해주세요.")
        Set<SizeType> allowedSizes,
```

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/dto/response/SaveClubResponse.java
> +        Long id,
```suggestion
public record SaveClubResponse(
        Long id,
```

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/service/ClubCommandService.java
> +    }
```suggestion
    public ClubCommandService(
            ClubRepository clubRepository,
            MemberRepository memberRepository,
            PetRepository petRepository,
            ClubMemberRepository clubMemberRepository
    ) {
        this.clubRepository = clubRepository;
        this.memberRepository = memberRepository;
        this.petRepository = petRepository;
    }
```

1. 개행 바꿔주세요~~
2. `ClubMemberRepository`는 어떻게 주입받고 있나요?

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/service/ClubCommandService.java
> +                .orElseThrow(() -> new FriendoglyException("모임 정보를 찾지 못했습니다."));
```suggestion
    public SaveClubMemberResponse addClubMember(Long clubId, Long memberId, SaveClubMemberRequest request) {
        Club club = clubRepository.findById(clubId)
                .orElseThrow(() -> new FriendoglyException("모임 정보를 찾지 못했습니다."));
```

`ClubMember`라는 매핑 테이블을 만들기는 했지만 `ClubCommandService` 입장에서 이 메서드를 보면 결국에는 Member를 Club에 추가하는 역할을 하고 있네요. `add`라는 네이밍은 어떨까요?

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/service/ClubCommandService.java
> +                .toList();
밑에 `mapToPets()` 메서드를 만든 김에 여기서도 활용해도 되겠네요

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/dto/request/SaveClubMemberRequest.java
> +) {
```suggestion
public record SaveClubMemberRequest(
        @NotEmpty(message = "모임에 참석 할 강아지를 1마리 이상 선택해주세요.")
        List<Long> participatingPetsId
) {
```

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/club/service/ClubCommandServiceTest.java
> +                .doesNotThrowAnyException();
모임 참여에 대한 테스트니까 모임의 회원 수를 검증하는 것이 좋을 것 같아요!

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/club/service/ClubCommandServiceTest.java
> +                Set.of(SizeType.SMALL));
이 부분이 계속 반복되는 것 같은데 테스트 클래스의 필드로 넣고 `@BeforeEach` 등으로 생성하는 것은 어떻게 생각하시나요?

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    }
```suggestion
    private boolean canDelegate(Member member) {
        return owner.getId().equals(member.getId()) && !isEmpty();
    }
```

`removeClubMember()`의 파라미터랑 직접 비교하면
(+ 나중에 equals and hashCode 구현되면)
덜 복잡할 것 같은데 어떠신가요??

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    }
```suggestion
        participatingMemberPets.forEach(clubPet -> clubPet.updateClub(null));
    }
```

2024-07-25 02:36 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/service/ClubCommandService.java
> +        newClub.addClubPet(participatingPets);
방을 만들 때 초기 멤버(방장)는 정적 팩토리 메서드에서 넣어주고 있는 것 같은데, 초기 펫(방장의 강아지들)은 넣지 않는 이유가 있을까요?

2024-07-25 03:16 UTC, ehtjsv2 submitted a review, later dismissed
연관관계 때문에 고생많이했습니다 위브~!

2024-07-25 03:16 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    List<ClubMember> clubMembers = new ArrayList<>();
클럽이랑 생명주기가 완전 같으니까 oneToMany적용해서 cascade할 수 있는게 장점이네요~!

2024-07-25 05:47 UTC, J-I-H-O requested changes
위브~ 고생 많으셨습니다~
전체적으로 Club에서 Member나 Pet과 직접 상호작용하지 않도록 변경해주시면 좋겠어요.
Club 코드가 훨씬 간결해질 것이라고 생각합니다.

추가된 코드 양이 많아서 일단 도메인 로직 위주로만 살펴봤어요.
리뷰 반영 후에 DM 주시면 추가로 확인하겠습니다!

2024-07-25 05:47 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/club/controller/ClubController.java
> +            @Valid @RequestBody SaveClubRequest request) {
```suggestion
    public ResponseEntity<ApiResponse<SaveClubResponse>> save(
            @Auth Long memberId,
            @Valid @RequestBody SaveClubRequest request
    ) {
```

2024-07-25 05:47 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    @OneToMany(mappedBy = "club", orphanRemoval = true, cascade = CascadeType.ALL)
```suggestion
    private Status status;
    
    @OneToMany(mappedBy = "club", orphanRemoval = true, cascade = CascadeType.ALL)
```

2024-07-25 05:47 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +            throw new FriendoglyException("모임에 데려갈 수 없는 강아지가 있습니다.");
```suggestion
            throw new FriendoglyException("모임에 데려갈 수 있는 강아지가 없습니다.");
```

2024-07-25 05:47 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/ClubMember.java
>      }
전 정적 팩토리 메서드 제거해도 괜찮을 것 같아요.

2024-07-25 05:47 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    }
`Pet` -> `ClubPet` 변환 로직이 Club에 들어있는게 부자연스러운 듯 합니다.
Club은 중간 테이블인 ClubPet을 통해 Pet과 상호작용해야 하는데, 어떻게 보면 Pet과 직접적으로 상호작용 하고 있네요.
해당 변환 로직을 ClubPet으로 밀어넣고, Service 에서 변환로직 호출 후 넣어주는 편이 좋겠어요.

2024-07-25 05:47 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    }
> Pet -> ClubPet 변환 로직이 Club에 들어있는게 부자연스러운 듯 합니다.
Club은 중간 테이블인 ClubPet을 통해 Pet과 상호작용해야 하는데, 어떻게 보면 Pet과 직접적으로 상호작용 하고 있네요.
해당 변환 로직을 ClubPet으로 밀어넣고, Service 에서 변환로직 호출 후 넣어주는 편이 좋겠어요.

이쪽도 마찬가지 입니다. 변환 로직을 ClubMember로 넣어주면 책임을 나눌 수 있을 것 같습니다.
또 이렇게 변경하면 바로 아래에 있는 `vlidateAlreadyExists()` 메서드 내부에서 `cotains()` 를 사용할 수도 있게 되겠지요?

2024-07-25 05:47 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/club/service/ClubCommandService.java
> +                .orElseThrow(() -> new FriendoglyException("모임 정보를 찾지 못했습니다."));
여기에 덧붙여서, 현재 `saveClubMember()` 메서드는 모임에 참여할 회원 뿐만 아니라, 모임에 참여할 강아지 정보도 추가하고 있습니다.
현재 네이밍이 Pet이 추가된다는 의미를 충분히 나타내지 못하는 것 같아요.
Club에 Pet이 추가되는 동작이 가려지지 않도록 네이밍을 고려해보시면 좋겠습니다.

2024-07-25 05:47 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +                .orElseThrow(() -> new FriendoglyException("참여 중인 모임이 아닙니다."));
```java
public void removeClubMember(ClubMember clubMember) {
        if (!clubMembers.remove(clubMember)) {
            throw new FriendoglyException("참여 중인 모임이 아닙니다.");
        }
        // ...
}
```
ClubMember를 인자로 받으면 로직을 더 간결하게 표현할 수 있겠습니다.

2024-07-25 05:47 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +        }
모임에서 탈퇴하려는 회원이 모임장인 경우 모임장의 역할을 위임하기 위한 메서드로 보입니다.
이 코드만 보았을 때에는 의도를 파악하기 힘든 것 같아요. 차라리 메서드를 나눠주는게 가독성이 좋겠습니다.
```java
if (isOwner(clubMember)) {
    delegateOwnerToNextMember();
}
```
```java
private void delegateOwnerToNextMember() {
    if (!clubMembers.isEmpty()) {
        this.owner = clubMembers.get(0).getMember();
    }
}
```

2024-07-25 05:47 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +        participatingMemberPets.forEach(clubPet -> clubPet.updateClub(null));
`clubPet.updateClub(null);`
이렇게 하면 해당 row가 지워지나요? 서비스에서 해당 row에 대한 delete 쿼리를 날려줘야할 것 같습니다.

2024-07-25 05:47 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +                .forEach(clubPets::add);
```suggestion
List<ClubPet> clubPets = pets.stream()
                .peek(this::validateParticipatePet)
                .map(pet -> new ClubPet(this, pet))
                .peek(clubPet -> clubPet.updateClub(this))
                .toList();
        this.clubPets.addAll(clubPets);
```

ArrayList는 요소 추가 시 가변적으로 배열 길이를 조절합니다. 
만약 많은 수의 ClubPet을 처리해야 한다면, 최대 배열 길이를 넘어선 add연산이 수행될 때마다 새로운 배열을 생성해 값을 복사해 넣습니다. 
따라서 foreach에서 add 연산을 수행하는 것 보단, 중간 연산 결과를 List로 모으고 한 번에 리스트에 추가하는 편이 좋아보입니다!
물론 ArrayList 내부의 배열 크기를 넘어설 만큼의 ClubPet이 입력될 일은 없을테니 참고만 해주세요.

2024-07-25 06:52 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/service/ClubCommandService.java
> +    }
연관 관계 리팩터링 하면서 더 이상 ClubMember~ ClubPet~ repository를 사용할 필요성이 없어졌는데, 까먹고 안 지웠네요

2024-07-25 06:57 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    }
entity에 동등성을 부여하는 부분은 논의해야 할 부분이라고 생각해서 따로 구현하진 않았어요.(너무 귀찮긴 했습니다.ㅎㅎ)

2024-07-25 06:58 UTC, jimi567 commented on backend/src/test/java/com/woowacourse/friendogly/club/service/ClubCommandServiceTest.java
> +                .doesNotThrowAnyException();
좋은 생각인 것 같아요.

2024-07-25 06:58 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +            throw new FriendoglyException("모임에 데려갈 수 없는 강아지가 있습니다.");
이거는 데려갈 수 있는 강아지가 있는데, 없는 강아지도 포함되어있어서 그런거 아냐?

2024-07-25 07:11 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/service/ClubCommandService.java
> +                .toList();
오 참여를 구현할 때 만들었던 메서드라 위에서 같은 로직이 쓰이고 있다는걸 망각했네요.

2024-07-25 07:41 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/service/ClubCommandService.java
> +                .orElseThrow(() -> new FriendoglyException("모임 정보를 찾지 못했습니다."));
비즈니스적인 내용이 메서드에 드러나도 괜찮다면, participate라는 네이밍이 간결하고 적절한 것 같은데 어떠신가요?

2024-07-25 07:55 UTC, jimi567 commented on backend/src/test/java/com/woowacourse/friendogly/club/service/ClubCommandServiceTest.java
> +                Set.of(SizeType.SMALL));
저희 DB 초기화를 리포지토리 끌어 쓰고 있기도 하고, 추후에 픽스처로 활용하려고, 따로 빼둔 거긴한데, 헷갈리게 만드는 것 같아서, 어노테이션으로 데이터 초기화 할게용

2024-07-25 08:05 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +        participatingMemberPets.forEach(clubPet -> clubPet.updateClub(null));
오히려 저 코드가 없어도 잘 동작합니다.
추후에 지울 예정인데 시간 내서 설명해드릴게요!

2024-07-25 08:07 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +            throw new FriendoglyException("모임에 데려갈 수 없는 강아지가 있습니다.");
지금 보니깐 , 모임에 데려갈 수 없는 강아지가 요청에 포함되어 있을 경우라서 저게 맞는 것 같아요.

2024-07-28 13:51 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    }
엔티티에 동등성을 아직 부여하고 있지 않아서 contains 함수를 사용하는건 별개의 문제인 것 같아용

2024-07-28 13:54 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +                .orElseThrow(() -> new FriendoglyException("참여 중인 모임이 아닙니다."));
엔티티에 동등성 부여하는게 가능하다면 저렇게 깔끔하게 해결할 수 있을 것 같아요.
저도 구현하면서 id 동등성이 엔티티에 있다면 정말 편하겠다는 생각은 했지만, 아직 다른 팀원들의 생각을 듣지 못해서 하진 않았어요

2024-07-28 13:58 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +        }
좋은 것 같아요.
메소드명의 경우 저희 컨벤션에도 알맞고 이해하기도 무리가 없을 것 같아서  updateOwner로 해봤는데 어떨까요?

2024-07-28 14:00 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +        target.updateClub(null);
oneToMany 옵션에 대해 따로 공유하는 시간 갖는 걸로 답변 대체하겠습니다.

2024-07-28 14:01 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/service/ClubCommandService.java
> +        newClub.addClubPet(participatingPets);
일관성 맞게 바꿨습니다. ㅎㅎ

2024-07-28 14:07 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    }
Pet, Member 두 부분 모두 entity 동등성 부여하는걸 고려한 이후에 수정해도 될까요?
아직 고민이 더 필요한 것 같습니다.
중간 테이블 엔티티가 서비스 나와도 상관이 없을까? 변환 로직을 서비스에서 하는게 적절할까? 이런 고민이 아직 있네요.! 좀 더 얘기 나눠보고 수정해봐도 될까요?

2024-07-28 16:39 UTC, takoyakimchi approved these changes
간단하게 코멘트 남겨봤어요 이번주도 화이팅입니다~~~~

2024-07-28 16:39 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +    private Club(
굿

2024-07-28 16:39 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +            updateOwner();
여기 가독성 훨씬 나아졌네요

2024-07-28 16:39 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/club/service/ClubCommandService.java
> +        newClub.addClubPet(participatingPets);
굿이에요~!

2024-07-28 16:39 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/club/service/ClubCommandServiceTest.java
> +    private Pet savedPet;
픽스처 좋아요

2024-07-28 16:39 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/club/service/ClubCommandServiceTest.java
> +    }
이건 상위 클래스에 있어도 될것 같기도 하고 ...

2024-07-28 16:39 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/club/service/ClubCommandServiceTest.java
> +        );
개행 좋네요

2024-07-29 04:16 UTC, ehtjsv2 approved these changes

2024-07-29 04:16 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/club/domain/Club.java
> +                .orElseThrow(() -> new FriendoglyException("참여 중인 모임이 아닙니다."));
나는 id에만 동등성 부여하는 것 동의합니다.

2024-07-29 06:54 UTC, J-I-H-O requested changes
Club의 메서드에서 Member나 Pet 대신 ClubMember나 ClubPet을 인자로 받도록 변경된 코드를 보고싶었는데, 이에 대한 언급이 없으셔서 다시 한 번 RC 보냅니다~

2024-07-29 07:12 UTC, J-I-H-O approved these changes

2024-07-29 07:18 UTC, merged