[AN] feat: 네트워크 에러 핸들링
woowacourse-teams/2024-friendogly pull request #241
Opened 2024-07-28 12:05 UTC by junjange

## 이슈
- close #236 

## 개발 사항
- 네트워크 에러 핸들링
- 발생한 에러에 따라서 UI 대응
- toast, snackbar base message 구현

## 전달 사항
- `Interceptor`에서 상태 코드를 기반으로 분기처리하여 `sealed class` 예외 생성(이때, 서버에서 내려준 정보를 포함시킨다)
- 상태 코드에 따라서 분기처리한 `sealed class`를 활용하여 서버에서 내려준 에러 코드에 따라서 다시 한번 분기처리 진행
- 분기처리 된 에러코드에 따라서 사용자에게 적절한 UI 대응(ex. toast, snackbar, dialog, 화면 전환 등)
- 현재 코드에서는 예시를 위해 프로필 만들기 페이지에서만 예외 처리를 진행했습니다.

2024-07-28 13:28 UTC, gaeun5744 requested changes
고생많으셨습니다!! 전반적으로 에디의 생각이 너무 궁금했던 pr이라서 마구마구 답장해주세요!!

2024-07-28 13:28 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/remote/error/ApiExceptionHandler.kt
> +    }
이펙티브 코틀린의 item 5?? 6?? 쯤을 보면 예외는 `정보를 전달하는 방법`으로서 사용되면 안된다고 되어있습니다! 모든 분기 상황이 예외가 아닌 `실패`에 해당함에도 불구하고, 예외를 던지는 로직이 어색해 보입니다

2024-07-28 13:28 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/domain/error/ApiException.kt
> +) : IOException(message, cause) {
`IOException`은 왜 상속받고 있나요? 보통 `IOException`은 입출력이나 네트워크 연결과 관련되어 있는데, `Unauthorized`이나 `NotFound`는 이와 상관없어 보입니다. 또한, 이펙티브 코틀린에서 **사용자 정의 오류보다는 표준 오류를 사용하라**라고 되어 있는데, 이 부분도 참고하면 좋을 것 같습니다! 

그리고 책을 해석하는 방식은 사람마다 다르지만, 저는 책을 보면서 예외를 

1. 앱을 종료시키는 것이 더 나을 만큼 중요한 순간에
2. 다른 개발자에게 코드를 알려주는 일종의 지침서로서

사용해야 한다고 생각했었습니다! 그리고 kotlin에서 `IOException`을 지원하지 않는 만큼, 예외를 다른 방식으로 다뤄보면 좋을 것 같습니다!

2024-07-28 13:28 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/domain/mapper/ApiExceptionMapper.kt
> +
api의 결과를 domain 레이어에서 맵핑하는 것이 어색해 보입니다! ui 레이어와 domain 레이어의 관계를 보면, ui 레이어가 일방적으로 domain 레이어를 참고하고 있습니다. 
현재 관계를 봤을 때, domain 레이어와 data 레이어가 서로 순환 참조가 되고 있는 형태네요! 어디 한 곳에 몰아넣어서, 순환참조가 되는 것을 막으면 좋을 것 같습니다!

2024-07-28 13:28 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/remote/error/ApiExceptionResponse.kt
> +) : IOException(message, cause) {
이펙티브 코틀린을 보면 `사용자 정의 오류보다는 표준 오류를 사용하라`라고 나와 있습니다! 책을 해석하는 방식은 사람마다 다르지만, 저는 책을 보면서 예외를 
1. 앱을 종료시키는 것이 더 나을 만큼 중요한 순간에
2. 다른 개발자에게 코드를 알려주는 일종의 지침서로서

사용해야 한다고 생각했었습니다! 그리고 kotlin에서 `IOException`을 지원하지 않는 만큼, 예외를 다른 방식으로 다뤄보면 좋을 것 같습니다!

2024-07-28 13:28 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseMessage.kt
> +}
Base가 과하게 많아지는 것 같습니다..! 전체적인 로직을 보니, viewModel에서 토스트를 보낼지, 스낵바를 보낼지 결정하고 있네요. 이러한 결정 사항이 **뷰가 아닌 비즈니스 로직**이라 생각했기 때문에 분기처리를 하고 있나요?
또한 에디의 **Base의 기준**이 궁금합니다!

2024-07-28 13:28 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/domain/error/ErrorData.kt
> +)
이 메시지는 `Api 통신 결과`에 해당하는 메시지인가요?  아니면 `뷰에 보여줄 메시지`인가요?
전자는 서버에서 클라이언트 개발자에게 알려주는 메시지이기에 여기에 두는 것이 부적절해 보이며, 후자라면 domain 레이어에 있는 것이 어색해 보여서 질문드립니다

2024-07-28 13:28 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/data/mapper/ApiExceptionMapper.kt
> +        }
`IOException`을 상속받는 비슷한 객체로 보이는데, 둘로 나눈 이유는 무엇인가요?

2024-07-28 14:47 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/domain/error/ApiException.kt
> +) : IOException(message, cause) {
> IOException은 왜 상속받고 있나요? 보통 IOException은 입출력이나 네트워크 연결과 관련되어 있는데, Unauthorized이나 NotFound는 이와 상관없어 보입니다.

맞습니다! 마땅히 뭐를 상속시켜야할 지 생각이 안나 네트워크 통신이니 IOExcption을 상속받았습니다. 그런데 지금 생각해보니 Exception을 상속받으면 해결될 것 같다는 생각이 듭니다.

> 또한, 이펙티브 코틀린에서 사용자 정의 오류보다는 표준 오류를 사용하라라고 되어 있는데, 이 부분도 참고하면 좋을 것 같습니다!

위 로직은 서버에서 실패 case로 내려주는 데이터를 감싸게 됩니다. 표준 오류로 해결할 수 없기 때문에 위와 같이 커스텀한 것입니다.

2024-07-28 14:52 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/domain/mapper/ApiExceptionMapper.kt
> +
헉 맞네여 수정하도록 하겠습니다!

2024-07-28 14:52 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/remote/error/ApiExceptionResponse.kt
> +) : IOException(message, cause) {
https://github.com/woowacourse-teams/2024-friendogly/pull/241#discussion_r1694262246
위 코멘트에 남겨두었습니다!

2024-07-28 14:58 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseMessage.kt
> +}
> Base가 과하게 많아지는 것 같습니다..! 전체적인 로직을 보니, viewModel에서 토스트를 보낼지, 스낵바를 보낼지 결정하고 있네요. 이러한 결정 사항이 뷰가 아닌 비즈니스 로직이라 생각했기 때문에 분기처리를 하고 있나요?

저는 에러 발생 시 어떤 사용자 피드백을 제공할지(예: 토스트, 스낵바, 다이얼로그, 화면 전환 등)는 비즈니스 로직의 일부분이라고 생각합니다. 따라서 이러한 분기 처리를 비즈니스 로직에서 수행하는 것이 적절하다고 봅니다.

> 또한 에디의 Base의 기준이 궁금합니다!

`Base`라는 명칭은 공통적으로 사용되는 컴포넌트나 로직을 지칭할 때 사용하려고 합니다.

2024-07-28 15:04 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/domain/error/ErrorData.kt
> +)
Api 통신 결과에 해당하는 메시지입니다.

> 서버에서 클라이언트 개발자에게 알려주는 메시지이기에 여기에 두는 것이 부적절해 보이며,

서버에서 내려주는 메시지를 활용할 수 있지 않을까?란 생각이 드는데, 왜 부적절한 지 궁금합니다! 
그리고 부적절하다면 어디에 둬야 좋을지도 궁금합니다!!

2024-07-28 15:05 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/data/mapper/ApiExceptionMapper.kt
> +        }
`remote`, `data` 레이어에서 각각 사용하는 `ApiException`이기 때문에 나누었습니다.

2024-07-28 15:15 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/remote/error/ApiExceptionHandler.kt
> +    }
> 이펙티브 코틀린의 item 5?? 6?? 쯤을 보면 예외는 정보를 전달하는 방법으로서 사용되면 안된다고 되어있습니다!

item 77777 맞습니다!! 위 로직은 서버에서 실패 케이스로 내려주는 데이터를 감싸서 `throw`하고 `source`에서 `catch`하기 위해 구현한 것입니다. 

```kotlin
val result = runCatching { service.postMember(body = body, file = file).data.toData() }

return when (val exception = result.exceptionOrNull()) {
        null -> result
        is ApiExceptionResponse -> Result.failure(exception.toData())
        else -> throw exception
    }
}
```
Result.failure()를 통해 커스텀한 예외를 던지게 됩니다.

이 방법 외 네트워크 통신이 실패했을 때 서버에서 내려주는 데이터를 감싸는 다른 방법이 있다면 알려주시면 감사하겠습니다!!


> 모든 분기 상황이 예외가 아닌 실패에 해당함에도 불구하고, 예외를 던지는 로직이 어색해 보입니다

네트워크 통신이 실패했을 때 예외가 발생하기 때문에 예외를 던진다고 생각했습니다.

2024-07-28 17:09 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/domain/error/ApiException.kt
> +) : IOException(message, cause) {
으음.. 저는 실패와 예외가 다르다고 생각합니다! 실패는 엄연히 `정보 전달`의 방법 중 하나이고, 왜 실패했는지 설명해주고, 이에 대해 일정하게 처리할 수 있도록 해줍니다. 실패에 대한 결과가 exception이 아닌 `에러 코드`인 이유도 앞과 마찬가지라고 생각합니다.

다른 방법으로 포장하는 방법으로는, [이 영상](https://www.youtube.com/watch?v=MiLN2vs2Oe0)을 추천드려요!

2024-07-28 17:21 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/domain/error/ErrorData.kt
> +)
말 그대로 `domain 영역`이기에 부적절해 보입니다. 클라이언트 개발자로서 생각해야하는 지점은, `View`와 `안드로이드이드 코드`만 봤을 때, 의미있는 메시지를 추출해서 domain 영역에 둬야 한다고 생각합니다.

예를 들어서 204 에러와 404 코드는 둘다 `없다` 를 의미해요. 아니면 null을 반환해서 `없다`라는 의미를 줄 수 있고요. 만약 에러 메시지를 그대로 전달받아 사용한다면, 서버의 수많은 종류의 에러메시지에 너무 종속적일 것 같습니다. 서버와 최대한 분리해서 생각해보면 좋을 것 같습니다!

2024-07-28 17:21 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/data/mapper/ApiExceptionMapper.kt
> +        }
remote는 엄연히 따지만 data 레이어에 종속되어 있는데,,, 오히려 패키지를 나눴기 때문에 불필요한 로직이 추가되었다고 생각되네요

2024-07-28 17:22 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/remote/error/ApiExceptionHandler.kt
> +    }
으음.. 저는 실패와 예외가 다르다고 생각합니다! 실패는 엄연히 정보 전달의 방법 중 하나이고, 왜 실패했는지 설명해주고, 이에 대해 일정하게 처리할 수 있도록 해줍니다. 실패에 대한 결과가 exception이 아닌 에러 코드인 이유도 앞과 마찬가지라고 생각합니다.

다른 방법으로 포장하는 방법으로는, [이 영상](https://www.youtube.com/watch?v=MiLN2vs2Oe0)을 추천드려요!

2024-07-28 17:37 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseMessage.kt
> +}
음... 제 안에서, 네트워크 끊김에 대해 피드백을 제공하는 방법이 대충 5가지가 있네요
1. 토스트
2. 스낵바
3. appbar(예시: 카카오톡)
4. 다이얼로그
5. 뷰 자체로 inflate해서 알리기 (예시: 당근)

그렇다면, 위의 5가지에 대해 모두 뷰를 구현할 예정인가요..? 지금 toast와 snackbar도 둘 중 하나면 구현하면 되지만, 분기처리를 위해 불필요한 구현이 들어가 있다고 생각합니다. 저는 저런 형태가 지속된다면, 디자인 확장성에 좋지 않아 보이네요ㅠㅠ

2024-07-28 23:24 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/remote/error/ApiExceptionHandler.kt
> +    }
동의합니다. 저도 이부분을 고민을 많이 했는데 영상 참고해서 수정해보도록 하겠습니다!

2024-07-28 23:34 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseMessage.kt
> +}
모든 뷰를 구현할 수 있을지는 잘 모르겠지만, 최대한 여러가지 측면으로 처리하려고 합니다. 그리고 위에 메시지타입이라고 지정한 것은 토스트와 스낵바만 해당되고 더 이상 추가되지 않을 것 같습니다!

그리고 불필요한 로직이라면 토스트와 스낵바 등 사용자와 인터렉션 할 수 있는 로직을 어떤식으로 풀어가는 게 좋을지 궁금합니다!

2024-07-28 23:46 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/data/mapper/ApiExceptionMapper.kt
> +        }
동의합니다.

하지만 remote 레이어를 분리하면서 얻은 이점도 있다고 생각합니다. 네트워크 통신 방식이나 API 변경 시 data 레이어에 미치는 영향을 최소화할 수 있고, data 레이어는 remote 레이어와의 의존성을 통해 네트워크 통신의 변경을 처리할 수 있습니다.

2024-07-29 00:01 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/domain/error/ErrorData.kt
> +)
아직 에러 처리에 대한 정책이 없기 때문에, 서버에서 내려주는 메시지를 통해 메시지를 전달했습니다. 벼리말처럼 서버의 의존적이면 안되기 때문에 수정이 필요할 것 같습니다! 생각해보니 메시지의 내용은 뷰에 대한 로직이니 `Presentation` 레이어에 있는 게 가장 적합하겠군요!

2024-07-29 04:00 UTC, jinuemong approved these changes, later dismissed
굳 !! 고민의 흔적이 보이네요.. 고생하셨습니다.

2024-07-29 04:00 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/domain/error/ErrorData.kt
> +)
저도 동의합니다! !
뷰에 대한 로직이 더 적합해보이네요.

2024-07-29 04:00 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseMessage.kt
> +}
저는 컴포넌트 식의 개발 (미리 Base를 작성해두고 편리하게 코드를 작성하는 방식)에 익숙해서
Base는 많을 수록 좋다는 의견이 있습니다.
이번에 BottomSheet를 많이 활용하게 되었는데 데이터 바인딩이나 옵션값을 주는 부분에서 공통된 코드가 너무 많다는 것을 느꼈어요.
디자인 확장성에 제약이 생기지만, 어느 정도의 통일이 보장되어서 좋다고 봐요.. 좀 더 얘기를 해봐야할 것 같습니다.

2024-07-29 04:00 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseViewModel.kt
> +    fun sendErrorMessage(
두 함수에 어떤 차이가 있나요? (그냥 질문)

2024-07-29 04:00 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/profilesetting/ProfileSettingActivity.kt
> +                is BaseMessage.Toast -> showToastMessage(message = baseMessage.message)
토스트&스낵바 기본 안드로이드 컴포넌트를 활용하나요 아니면 UI 커스텀이 가능한가요?

2024-07-29 04:00 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseViewModel.kt
> +    protected fun launch(
launch가 생겼군요 👍

2024-07-29 04:00 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/remote/error/ApiExceptionResponse.kt
> +sealed class ApiExceptionResponse(
분기처리 굳 👍

2024-07-29 04:08 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseMessage.kt
> +}
이 부분은 공통 컴포넌트에 대한 이야기 보다는, 과연 에러를 보여주는 방식을 toast나 snackbar로 한정짓는게 맞는가? 에 대한 이야기인 것 같아요. 
에러를 보여주기 위한 방법은 수많가지인데, 다른 개발자가 봤을 때, 해당 코드를 보고 의문이 들수 있을 것 같습니다! 지금 코드만 봤을 때는, 에러에 관한 메시지 타입인지는 모를 것 같아요ㅠ 
공통 컴포넌트에 관한 base는 저도 동의하고 있습니다

2024-07-29 04:11 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/data/mapper/ApiExceptionMapper.kt
> +        }
레이어를 나누는 이유가 궁극적으로 **유지보수**와 **가독성**인 만큼, 무조건 의존성을 완전히 분리해야 하는가? 에 대해서는 저는 회의적입니다.
domain 객체를 가공할 이유가 없다면 그대로 ui 레이어에서 사용하는 것처럼, 이 부분도 가공할 필요가 없기 때문에 그대로 가져다 써도 좋을 것 같아요!
저는 개인적으로, 순환참조가 되지 않고 참조 방향만 일정하다면 괜찮다는 주의에요

2024-07-29 04:20 UTC, gaeun5744 requested changes

2024-07-29 04:20 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseMessage.kt
> +}
> 그리고 불필요한 로직이라면 토스트와 스낵바 등 사용자와 인터렉션 할 수 있는 로직을 어떤식으로 풀어가는 게 좋을지 궁금합니다!

저는 에러 타입에 대해, sealed나 enum 객체만 던지는 편입니다. 그리고 이런 에러에 대해 어떻게 보여줄지는 온전히 각 뷰의 결정에 따라야 한다고 생각합니다. 뷰에 따라 적절한 안내 방식은 서로 다르니깐요!

2024-07-29 06:14 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseMessage.kt
> +}
> 이 부분은 공통 컴포넌트에 대한 이야기 보다는, 과연 에러를 보여주는 방식을 toast나 snackbar로 한정짓는게 맞는가? 에 대한 이야기인 것 같아요.
> 에러를 보여주기 위한 방법은 수많가지인데, 다른 개발자가 봤을 때, 해당 코드를 보고 의문이 들수 있을 것 같습니다! 지금 코드만 봤을 때는, 에러에 관한 메시지 타입인지는 모를 것 같아요ㅠ.

에러를 보여주는 방식은 위에서도 언급했듯이, 토스트, 스낵바, 다이얼로그, 화면 전환 등이 있을 것 같습니다. 메시지 타입은 toast, snackbar 중에 어떤 것을 선택하여 사용자에게 메시지를 보낼 것인지 알기 위해 만들어놓은 enum class 입니다. 또한, 지금은 에러 메시지에 사용되지만, 에러 메시지 뿐만 아니라 다른 메시지를 전달할 때도 사용될 것 같습니다!

2024-07-29 06:15 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseViewModel.kt
> +    fun sendErrorMessage(
예외 메시지를 전달 할 때는 Throwable! 
그냥 메시지를 전달 할 때는 String!

위처럼 상황에 맞게 메시지를 전달하기 위해 만들었습니다!

2024-07-29 06:19 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/profilesetting/ProfileSettingActivity.kt
> +                is BaseMessage.Toast -> showToastMessage(message = baseMessage.message)
스낵바는 커스텀 가능하게 구현해놨고, 토스트는 커스텀하지 못할 것 같습니다!!

2024-08-11 00:16 UTC, junjange commented
## 개발 사항
- 네트워크 에러 핸들링
- 발생한 에러에 따라서 UI 대응
- toast, snackbar base message 구현

## 전달 사항
### `Interceptor`에서 상태 코드를 기반으로 분기처리하여 `sealed class` 예외 생성(이때, 서버에서 내려준 정보를 포함시킨다)

```kotlin

fun createErrorResponse(responseBodyString: String): ErrorResponse? =
    try {
        Json.decodeFromString<ErrorResponse>(responseBodyString)
    } catch (e: Exception) {
        null
    }

fun createApiException(
    httpCode: Int,
    errorResponse: ErrorResponse,
): ApiExceptionResponse? {
    return when (httpCode) {
        400 -> BadRequest(message = errorResponse.data.errorMessage, error = errorResponse)
        403 -> Forbidden(message = errorResponse.data.errorMessage, error = errorResponse)
        404 -> NotFound(message = errorResponse.data.errorMessage, error = errorResponse)
        500 -> ServerError(message = errorResponse.data.errorMessage, error = errorResponse)
        else -> null
    }
}

```

`ErrorResponseInterceptor`는 `OkHttp`의 `Interceptor`로, HTTP 응답을 검사하고 오류를 처리합니다. 응답이 성공적이면 그대로 반환하고, 실패 시에는 서버에서 내려주는 실패 응답을 `ErrorResponse` 객체로 변환합니다. 이후 HTTP 상태 코드와 변환된 오류 응답을 바탕으로 `ApiExceptionResponse` 객체를 생성하여 예외를 던집니다. 

### Data Source Layer에서는 원시적인 에러를 처리하고, 이를 repository 레이어로 전달합니다.(remote -> data)

``` kotlin
class AuthDataSourceImpl(
    private val service: AuthService,
) : AuthDataSource {
    override suspend fun postKakaoLogin(accessToken: String): Result<LoginDto> {
        val body = PostLoginRequest(accessToken = accessToken)
        val result = runCatching { service.postKakaoLogin(body = body).data.toData() }

        return when (val exception = result.exceptionOrNull()) {
            null -> result
            is ApiExceptionResponse -> Result.failure(exception.toData())
            else -> throw exception
        }
    }
}

```


`AuthDataSourceImpl` 클래스는 원시적인 에러를 처리하고 이를 `Result` 형태로 반환하는 데이터 소스 레이어 구현체입니다. `postKakaoLogin` 함수는 `AuthService`를 호출하여 로그인 요청을 수행합니다. 요청이 성공하면 결과를 `Result`로 반환하며, 실패할 경우 `ApiExceptionResponse`를 변환하여 `Result.failure`로 반환합니다. 그 외 예외는 그대로 던져 처리합니다. 이를 통해 데이터 소스 레이어는 에러를 캡처하고 적절한 형식으로 변환하여 상위 레이어로 전달합니다.

- Repository Layer에서는 data source에서 전달된 에러를 도메인 레이어에서 사용할 수 있는 형태로 변환하고, 비즈니스 로직에 맞게 처리합니다.(data -> domain)
- 상태 코드에 따라서 분기처리한 `sealed class`를 활용하여 서버에서 내려준 에러 코드에 따라서 다시 한번 분기처리 진행
- 분기처리 된 에러코드에 따라서 사용자에게 적절한 UI 대응(ex. toast, snackbar, dialog, 화면 전환 등)
- 현재 코드에서는 예시를 위해 프로필 만들기 페이지에서만 예외 처리를 진행했습니다.

2024-08-11 05:18 UTC, junjange commented
## 개발 사항
- 네트워크 에러 핸들링
- 발생한 에러에 따라서 UI 대응
- toast, snackbar base message 구현

## 전달 사항
### `Interceptor`에서 상태 코드를 기반으로 분기처리하여 `ApiExceptionResponse` 예외 생성(이때, 서버에서 내려준 정보를 포함시킨다)

```kotlin

fun createErrorResponse(responseBodyString: String): ErrorResponse? =
    try {
        Json.decodeFromString<ErrorResponse>(responseBodyString)
    } catch (e: Exception) {
        null
    }

fun createApiException(
    httpCode: Int,
    errorResponse: ErrorResponse,
): ApiExceptionResponse {
    return ApiExceptionResponse(
        httpCode = httpCode,
        error = errorResponse,
        message = errorResponse.data.errorMessage,
    )
}

```

`ErrorResponseInterceptor`는 `OkHttp`의 `Interceptor`로, HTTP 응답을 검사하고 오류를 처리합니다. 응답이 성공적이면 그대로 반환하고, 실패 시에는 서버에서 내려주는 실패 응답을 `ErrorResponse` 객체로 변환합니다. 이후 HTTP 상태 코드와 변환된 오류 응답을 바탕으로 `ApiExceptionResponse` 객체를 생성하여 예외를 던집니다.



### Data Source에서는 원시적인 에러를 처리(remote -> data)

``` kotlin
class AuthDataSourceImpl(
    private val service: AuthService,
) : AuthDataSource {
    override suspend fun postKakaoLogin(accessToken: String): Result<LoginDto> {
        val body = PostLoginRequest(accessToken = accessToken)
        val result = runCatching { service.postKakaoLogin(body = body).data.toData() }

        return when (val exception = result.exceptionOrNull()) {
            null -> result
            is ApiExceptionResponse -> Result.failure(exception.toData())
            else -> throw exception
        }
    }
}

```

`XXXDataSourceImpl`에서 API 요청이 성공하면 결과를 `Result`로 반환하며, 실패할 경우 `ApiExceptionResponse`를 `ApiExceptionDto`로 변환하여 `Result.failure`로 반환합니다. 그 외 예외는 예상치 못한 예외로 그대로 던져 처리합니다. 이를 통해 데이터 레이어는 서버에서 내려주는 에러를 캡처하고 상위 레이어로 전달하게 됩니다.


### Repository에서는 data source에서 전달된 에러를 도메인 레이어에서 사용할 수 있는 형태로 변환하고, 비즈니스 로직에 맞게 처리(data -> domain)


```kotlin

class AuthRepositoryImpl(
    private val source: AuthDataSource,
) : AuthRepository {
    override suspend fun postKakaoLogin(accessToken: String): Result<Login, DataError.Network> {
        return source.postKakaoLogin(accessToken = accessToken).fold(
            onSuccess = { login ->
                Result.Success(login.toDomain())
            },
            onFailure = { e ->
                if (e is ApiExceptionDto) {
                    Result.Error(e.error.data.errorCode.toDomain())
                } else {
                    Result.Error(DataError.Network.NO_INTERNET)
                }
            },
        )
    }
}

```

`XXXRepositoryImpl`는 데이터 소스에서 반환된 결과를 Result<D, E> 형태로 변환하고, 성공적인 경우에는 도메인 모델로 변환하여 반환합니다. 실패한 경우에는 `ApiExceptionDto`를 기반으로 적절한 `DataError.Network`를 생성하여 `Result.Error`로 반환합니다. 만약 예외가 예상된 범위에 포함되지 않으면 기본적인 네트워크 오류로 처리합니다. 이를 통해 에러를 일관되게 처리하고, 도메인 레이어에 적합한 형식으로 반환합니다.


### 분기처리 된 에러코드에 따라서 사용자에게 적절한 UI 대응(ex. toast, snackbar, dialog, 화면 전환 등)


```kotlin

// Result 확장함수
inline fun <D, E : RootError, R> Result<D, E>.fold(
    onSuccess: (data: D) -> R,
    onError: (error: E) -> R,
): R =
    when (this) {
        is Result.Success -> onSuccess(data)
        is Result.Error -> onError(error)
    }

// viewmodel 
  postKakaoLoginUseCase(accessToken = accessToken).fold(
            onSuccess = { login ->
                if (login.isRegistered) {
                    val tokens = login.tokens ?: return
                    saveJwtToken(tokens)
                } else {
                    _navigateAction.emit(RegisterNavigationAction.NavigateToProfileSetting(idToken = kakaAccessToken.accessToken))
                }
            },
            onError = { error ->
                when (error) {
                    DataError.Network.SERVER_ERROR -> _message.emit(RegisterMessage.ServerErrorMessage)
                    else -> _message.emit(RegisterMessage.DefaultErrorMessage)
                }
            },
        )

```

`Result<D, E>` 타입의 `fold` 확장 함수를 사용하여 `XXXUseCase`의 결과를 처리합니다. fold 함수는 성공과 실패를 구분하여 각각에 대해 적절한 콜백을 호출합니다. 이를 통해 결과를 직관적이고 효율적으로 처리할 수 있습니다. onError 스코프를 보게되면 에러코드에 따라서 사용자에게 적절한 UI 대응(ex. toast, snackbar, dialog, 화면 전환 등)을 하는 것을 볼 수 있습니다.

2024-08-11 12:47 UTC, gaeun5744 approved these changes
고생하셨습니다~!! 이전보다 구조가 유기적으로 흐르는것 같아요!!

2024-08-11 12:47 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/domain/Result.kt
> +): R =
혹시 일부러 컬렉션 메서드의 `fold`와 유사하게 지었나요..? 
저는 fold를 보면 컬렉션이 생각나서 질문 드립니당

2024-08-11 12:47 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseViewModel.kt
> +            }
BaseViewModel에서 에러 핸들링을 해도 좋을것 같아요..! 서버/네트워크 처럼 공통적인 에러를 넣어도 좋을 것 같고, 에러 발생시 유저에게 메시지를 줘서 앱을 다시 실행하도록 유도해도 좋을 것 같아요

2024-08-11 13:07 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseViewModel.kt
> +            }
이건 만나서 이야기해봐요!!

2024-08-11 13:11 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/domain/Result.kt
> +): R =
아닙니다! `Reuslt`에도 `fold` 메서드가 있어서 이와 유사하게 구현한 것입니다!

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-result/#extension-functions

2024-08-12 03:44 UTC, jinuemong approved these changes
고생하셨습니다 ~

2024-08-12 08:35 UTC, merged