Feature/setting
woowacourse-teams/2024-friendogly pull request #265
Opened 2024-07-31 06:18 UTC by junjange

## 이슈
- close #13

## 개발 사항
- 설정페이지 구현
- 다이얼로그 색상 수정

<img width="30%" src="https://github.com/user-attachments/assets/b36ff599-01e4-4fa4-8cf2-2b3b415b7063">   
<img width="30%" src="https://github.com/user-attachments/assets/ce82828f-64c1-46a1-a4db-25b09d81ef38">   
<img width="30%" src="https://github.com/user-attachments/assets/df8e51c8-b696-41f3-a481-d1f706f83b1a">

2024-07-31 07:42 UTC, gaeun5744 requested changes
고생하셨습니당~

2024-07-31 07:42 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/setting/SettingActivity.kt
> +                    finish()
혹시 finish를 중복으로 두번 한 이유가 있을까요?

2024-07-31 07:42 UTC, gaeun5744 commented on android/app/src/main/res/layout/activity_setting.xml
> +        <Switch
[switch deprecated](https://github.com/material-components/material-components-android/blob/master/docs/components/Switch.md#switch-deprecated) ㅠㅠ
다른 switch로 바꿔주세요!!

2024-07-31 07:42 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/mypage/MyPageUiState.kt
> +interface PetViewType {
혹시 sealed를 왜 뺐는지 알 수 있을까요?!

2024-07-31 07:42 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/mypage/MyPageUiState.kt
> +    val id: Long = -1,
개인적으로 `INVALID_ID`라고 상수화를 하면 좋을 것 같습니다!

2024-07-31 15:41 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/setting/SettingActivity.kt
> +                    finish()
헉 `finishAffinity()`가 현재 `Activity`를 제외한 상위 `Activity`들만 종료하는 줄 알았는데, 현재 `Activity`도 종료시키네요?!
그럼 `finishAffinity()`가 실행되면, `startActivity(RegisterActivity.getIntent(this))`가 실행되기 전에 화면이 전환되면서, 이 호출이 실행되지 않아야 한다는 생각이 드는데 잘 실행이 되네요..

알아보니 `finishAffinity()`는 `Activity` 종료 작업을 비동기적으로 처리한다고 해요! 따라서 `Activity` 종료가 완료되기 전에 `startActivity()`가 호출될 수 있는 것이죠.

하지만 `startActivity(RegisterActivity.getIntent(this))`가 먼저 실행되고 비동기적으로 `finishAffinity()`가 수행되는 것에 대해 보장될 수 없다고 생각해서 이 로직을 Intent 플래그를 활용하여 개선했습니다!!

2024-07-31 15:42 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/mypage/MyPageUiState.kt
> +interface PetViewType {
충돌 해결하다가 커밋이 잘못들어갔나봐여ㅠㅠ

2024-07-31 16:11 UTC, junjange commented on android/app/src/main/res/layout/activity_setting.xml
> +        <Switch
네네!! 그냥 벼리 스위치 쓸게요!! 디자인 색상은 살짝 바꿨습니다..!😊

<img width="30%" src="https://github.com/user-attachments/assets/4d448781-f52e-45ea-84e2-6c7d75c6b78c">   

<img width="30%" src="https://github.com/user-attachments/assets/149ed6f8-44c2-4e7e-805d-95f4e5ba515c">

2024-08-01 02:08 UTC, jinuemong approved these changes
고생하셨습니다 ~~~

2024-08-01 02:08 UTC, jinuemong commented on android/app/src/main/AndroidManifest.xml
> -            android:windowSoftInputMode="adjustPan"
이거 #271  pr 코드에도 적용되어 있어서 머지 되면 충돌 해결하겠습니다~

2024-08-01 02:08 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/mypage/MyPageFragment.kt
> +        viewModel.fetchMemberMine()
resume에서 하는 이유는 무엇인가요?

2024-08-01 02:13 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/mypage/MyPageFragment.kt
> +        viewModel.fetchMemberMine()
프로필 및 강아지 수정시에 데이터를 다시 로드해야하기 때문입니다!! 지금은 `onResume()` 할 때마다 데이터를 로드하지만, `registerForActivity`할 때 프로필 및 강아지를 수정했는지 확인하고 수정했을 때마다 실행되게끔 리팩터링하려고 합니다!

2024-08-01 02:19 UTC, dpcks0509 approved these changes
고생했어요~

2024-08-01 02:22 UTC, gaeun5744 approved these changes
고생하셨습니다!!!

2024-08-01 02:22 UTC, merged