[AN] 멍멍짖기 기획 수정에 따른 리팩토링
woowacourse-teams/2024-friendogly pull request #286
Opened 2024-08-02 08:14 UTC by dpcks0509

## 이슈
- close #132

## 개발 사항
- 멍멍짖기 기획 수정에 따른 리팩토링 진행했습니다. 갈거에요 마커 위치 설정 부분은 다음 pr에서 추가하겠습니다!

# 전달 사항 (없으면 삭제해 주세요)
- (오류) 지도화면에서 권한이 허용돼있다가 권한을 껐을때 다이얼로그만 뜨고 화면 창은 홈 화면이다.
- 마커 생성에 walkStatus 받아야함. (api 생성되면 수정 예정)

2024-08-03 13:55 UTC, jinuemong submitted a review, later dismissed
고생하셨습니다~ 
승인하고 코맨트 달았습니다

2024-08-03 13:55 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/woof/WoofViewModel.kt
> +    private val _footprintSave: MutableLiveData<FootprintSave> = MutableLiveData()
현재 사용자가 저장한 마커가 맞나요? 
그렇다면 네이밍 수정이 좋아보여요 
savedfootprint나 myfootprint 등 직관적이었으면 좋겠습니다

2024-08-03 13:55 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/woof/WoofViewModel.kt
> +            }.onFailure {
실패 로직은 없나요?

2024-08-03 13:55 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/woof/adapter/FootprintInfoAdapter.kt
> +
Membername을 따로 설정하는 이유가 궁금합니다 
서버에서 내려주는 도메인에서는 membername에 대한 정보가 포함되어 있지 않나요?

2024-08-03 13:55 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/woof/adapter/PetDetailViewHolder.kt
> +        binding.memberName = memberName
데이터바인딩이 아닌 직접 뷰 바인딩을하는 이유거 궁금해요

2024-08-03 13:55 UTC, jinuemong commented on android/app/src/main/res/layout/fragment_woof.xml
> +            android:layout_width="wrap_content"
이건 몬가요?

2024-08-03 13:55 UTC, jinuemong commented on android/app/src/main/res/layout/fragment_woof.xml
>              android:id="@+id/layout_woof_loading"
로띠를 framelayout으로 감싸서 한 계층을 추가하신 이유가 무엇인가요?

2024-08-03 14:59 UTC, gaeun5744 requested changes
고생하셨습니다!

2024-08-03 14:59 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/woof/WoofBindingAdapters.kt
> +}
날짜 계산하는 로직이 @junjange 와 굉장히 유사하군요.. 둘이 합의 봐서 `domain`으로 로직을 옮긴 다음에 통일시키는게 확장성에 좋아 보입니다

2024-08-03 14:59 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/woof/WoofBindingAdapters.kt
>              )
아마 `XX의 강아지`라는 텍스트에서, 특정 부분만 색깔을 바꾸고 강조하고 싶어서 만든 코드 같네요. 개인적으로 저는 이런 뷰는 `memberName`을 나타내는 TextView를 따로, `의 강아지`라는 string을 가진 TextView를 따로 만들어서 둘을 이어붙이는 편입니다. 둘 중 더 가독성 좋아보이는 것으로 채드가 선택하면 좋겠네요!

2024-08-03 14:59 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/woof/adapter/PetDetailViewHolder.kt
> +        binding.petDetail = petDetail
채드! 이부분은 이전에 제가 잘못 설명한 부분이 있어서 추가로 링크를 달겠습니다!
변경이 잦은 데이터에 대해 따로 uiModel로 묶고 + `diffUtil`에 `payload를 추가로 구현`해야 하네요.. listAdapter 내부적으로 자동으로 하는 것으로 착각했습니다..
RecyclerView에서 payLoad를 구현하는 것보다 훨씬 쉬워 보이니깐 이참에 도전해 보는것도 좋을것 같네요^^ 헤헿,,,,

관련된 설명으로는 해당 [링크1](https://medium.com/@domen.lanisnik/efficiently-updating-recyclerview-items-using-payloads-1305f65f3068) [링크2](https://collectingbuttons.tistory.com/entry/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-ListAdapter-DiffUtil-%EC%A0%9C%EB%8C%80%EB%A1%9C-%EC%93%B0%EA%B8%B0-2)를 첨부합니당

2024-08-03 15:04 UTC, gaeun5744 commented
주말에 pr을 올릴 경우, 영상도 같이 첨부하면 더 좋은 리뷰를 많이많이 받을 수 있을 것 같습니다!! 지금으로서는 피그마를 보고 채드의 의도를 파악하는 것이 한계인지라,,,

2024-08-04 04:11 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/base/BaseFragment.kt
> +            }
음 이건 어떤 `Fragment`에서나 스낵바를 커스텀 가능하게 하려고 구현해 놓은 거 였는데, 사용하는 곳에서 위처럼 커스텀할 수 있지 않나요?!

2024-08-04 04:11 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/woof/WoofBindingAdapters.kt
>              )
뷰를 그리는 방식의 차이라고 생각해서, 저도 이건 취향차이 라고 생각합니다~~

2024-08-04 04:11 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/woof/WoofBindingAdapters.kt
> +}
이부분은 수정하지 말고 나중에 다같이 코드 리뷰할 때 함께 수정해보아요~~

2024-08-04 04:11 UTC, junjange commented on android/app/src/main/res/layout/item_pet_detail.xml
> +            android:text="정보"
상수화 부탁드립니다아

2024-08-04 05:20 UTC, jinuemong commented on android/app/src/main/res/layout/item_pet_detail.xml
> +            android:text="정보"
근데 정보가 뭐죠?

2024-08-04 14:29 UTC, junjange commented on android/app/src/main/res/layout/item_pet_detail.xml
> +            android:text="정보"
![image](https://github.com/user-attachments/assets/f08deaa6-644b-406c-bc5b-ec54de6915c7)

2024-08-08 07:02 UTC, closed without merging