[BE] 발자국 산책 상태 변경 기능 구현
woowacourse-teams/2024-friendogly pull request #289
Opened 2024-08-03 07:02 UTC by ehtjsv2

## 이슈
- #264 

## 개발 사항(이슈내용에 상세 내용존재)
- 현재위치에 따라 발자국 산책 상태가 변경 되도록 구현했습니다.
- Footrprint의 모든 필드 제어하는 생성자 추가(isDeleted추가 한 것이 끝)

### 전달 사항
- 이 PR이후 땡이가 말했던 주 생성자 부생성자 나누는 작업 해보겠습니다

2024-08-03 08:12 UTC, takoyakimchi requested changes
마음이 급해서 빠르게 리뷰해버렸네요 ㅎㅎ,,

2024-08-03 08:12 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
> +        return new UpdateWalkStatusResponse(footprint.getWalkStatus());
```suggestion
        Footprint footprint = footprintRepository.getRecentByMemberId(memberId);
        footprint.changeWalkStatus(new Location(request.latitude(), request.longitude()));
        return new UpdateWalkStatusResponse(footprint.getWalkStatus());
```

```java
// repository
    @Query("""
            SELECT footprint
            FROM Footprint footprint
            WHERE footprint.member.id = :memberId AND footprint.isDeleted = false
            """)
    Optional<Footprint> findRecentByMemberId(@Param("memberId") Long memberId);

    default Footprint getRecentByMemberId(Long memberId) {
        return findRecentByMemberId(memberId)
                .orElseThrow(() -> new FriendoglyException("exception"));
    }
```

1. 다른 도메인에서 하는 것처럼 default 메서드 두고 getBy~ 쓰면 좋겠네요~! 예외 처리 로직 분리 + 가독성까지 챙겨갈 수 있겠어요
2. 논리 삭제 판단은 DB에서 해도 될 것 같아요!

2024-08-03 08:12 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Footprint.java
> +    }
개행이 빠져 있네요!

2024-08-03 08:12 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Footprint.java
> +    }
`isNear()`은 조회 범위에 쓰이는 메서드라서(현재 1000m)

이거는 다른 메서드 + 상수를 만들어서 해야 할 것 같아요!

2024-08-03 08:12 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/footprint/service/FootprintCommandServiceTest.java
> +
갑자기 떠오른 건데 1미터의 경도 차이가 `0.0000089831` 정도라네요...!
이걸 fixture로 넣고 곱해서 쓰면 어떨까 싶네요
(반경 범위는 수정의 여지가 다분해서...)

2024-08-03 08:44 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
> +        return new UpdateWalkStatusResponse(footprint.getWalkStatus());
@takoyakimchi 정성스러운 코멘트..감동
코드도 다 짜준..
1. getBy한다고 find를 못쓰는 것이 아닌데 혼동하다가 안써버렸네요! 수정하겠습니다
2. 논리 삭제 판단을 service에서 한 이유는 상황에 따라 어떤 service 메서드에서는 삭제된 발자국을 불러와야 할 수도 있다고 생각했기 때문입니다. 
논리 삭제 판단 DB에서 할 경우 -> repository에 논리 삭제된enitity조회용 메서드,  논리 삭제안되것 포함 entity 조회용메서드 이렇게 2개씩 생김
삭제된 발자국을 부를 일이 없다면 repo단으로 내려도 괜찮겠네요. 지금 다른 발자국 기능도 hotfix해야하는데 그 메서드들 hotfix하고도 삭제된 발자국 필요없다면 repo로 내려보겠습니다~!

2024-08-03 08:46 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Footprint.java
> +    }
전체 미팅때 이야기 했는 지 기억이 안나지만 조회는 이제 범위제한이 없어져서 isNear를 발자국 산책 상태 변경이 가져 갈겁니다 하하
* 범위 제한 푸는 거 hotfix해야함.. hotfix할때는 private메서드로 변하겠네요~!

2024-08-03 08:47 UTC, ehtjsv2 commented on backend/src/test/java/com/woowacourse/friendogly/footprint/service/FootprintCommandServiceTest.java
> +
저도 상수로 관리하면 좋겠다 생각은 했는데, 기준점에따라 1km 위도 경도가 달라져서 어떻게 할까 고민하다가 저렇게 했는데 조금 더 고민해봐야겠네요.
좋은 방법있나요?

2024-08-04 04:53 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
> +        return new UpdateWalkStatusResponse(footprint.getWalkStatus());
좋아용~~~

2024-08-04 04:54 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/footprint/service/FootprintCommandServiceTest.java
> +
`0.0000, 0.0000`을 기준으로 픽스한다면 테스트 할 때는 괜찮을 것 같아요!

2024-08-04 08:08 UTC, jimi567 reviewed
범위 제한 푸는 부분 다시 적용되면 함 더 보겠슴당

2024-08-04 08:08 UTC, jimi567 commented on backend/src/test/java/com/woowacourse/friendogly/docs/FootprintApiDocsTest.java
> +        mockMvc
잊지 않고 400 케이스도 문서화 해주셨네요 굿

2024-08-04 08:08 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
> +        return new UpdateWalkStatusResponse(footprint.getWalkStatus());
저희 변경감지 update 쓰기로해서 참고만 부탁드려요(그게 그거긴 한데..)

2024-08-05 03:53 UTC, takoyakimchi approved these changes

2024-08-05 03:53 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/footprint/service/FootprintCommandServiceTest.java
> +        );
오 굿

2024-08-05 03:53 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Footprint.java
> +        );
👍

2024-08-05 03:53 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/repository/FootprintRepository.java
> +    }
굿이네요!!
이러면 어차피 메서드명 바꿀 수 있으니까 가독성 있는 이름으로 바꿔봐도 좋을 것 같아요.

2024-08-05 03:53 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Footprint.java
> +        if (walkStatus.isBefore() && isInsideBoundary(currentLocation)) {
메서드명이 깔끔해졌네요~

2024-08-05 13:39 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/repository/FootprintRepository.java
> +    }
저는 이런 흐름으로 지금이 좋다고 생각했었습니다.
`findTop~AtDesc`를 쓰려는데 예외처리를 한 메서드가 없을까?->`getTopOne~AtDesc() `이게 누가봐도 예외처리한 `findTop~AtDesc`구나
처럼 한눈에봐도 서로 연관있다는 것을 보여주고싶었습니다

2024-08-06 00:42 UTC, J-I-H-O approved these changes

2024-08-06 05:16 UTC, merged