[AN] feat: 내 위치 등록 기능 구현
woowacourse-teams/2024-friendogly pull request #292
Opened 2024-08-03 09:02 UTC by jinuemong

## 이슈
- close #291 

## 개발 사항
- 내 위치 등록 기능 구현하였습니다.

# 전달 사항 
- 가끔 불러오지 못하는 경우가 있는데 Geocoder 에런지 모르겠네요. (수정 예정)
- 마커가 작은 이유는 여러 기기에서 테스트 해봤는데 특정 기기에서 마커가 너무 크게 나옵니다. 
- 일단 default 크기로 지정했습니다.(수정 예정)

https://github.com/user-attachments/assets/b9986aef-586c-414d-982b-92631b20405c

2024-08-03 16:22 UTC, gaeun5744 submitted a review, later dismissed
고생하셨습니당~

2024-08-03 16:22 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/local/di/AddressModule.kt
> +    private val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = DATA_STORE_NAME)
파라미터가 아닌 필드로 선언되어 있네요! 
혹시 이런 클래스를 만들 때, `applicationContext`를 넘길 것이라 확신하고 만드는 편인가요? 다른 예시 코드들도 보면, context를 파라미터가 아닌 `필드`로 선언하고, appllicationContext를 넘기는 경우가 많네요,,,
++ 공식문서를 보면 applicationContext를 힐트 어노테이션으로 선언했네요

2024-08-03 16:22 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/mylocation/SettingMyLocationActivity.kt
> +                1000,
혹시 이 1000은 무엇을 의미하나요?

2024-08-03 16:41 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/local/di/AddressModule.kt
> +    private val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = DATA_STORE_NAME)
필드 선언으로 인한 메모리 누수가 생각나서 질문 드립니당!!

2024-08-04 04:01 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/mylocation/SettingMyLocationActivity.kt
> +                1000,
1초 딜레이 입니다 !

2024-08-04 04:05 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/local/di/AddressModule.kt
> +    private val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = DATA_STORE_NAME)
토큰을 저장하는 LocalModule과 통일성을 위해서 동일하게 context로 선언하였습니다.
DataStore나 di를 사용할 때 컨텍스트로 인한 문제를 피하기 위해서 applicationContext를 넘겨주는 것이 좋은 것으로 알고 있습니다.
대화 후에 수정해봐야할 것 같아요
LocalModule의 네이밍을 재정의할 때 리팩토링해야 할 것 같습니다.

2024-08-04 04:17 UTC, junjange requested changes

2024-08-04 04:17 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/group/list/GroupListViewModel.kt
> +    val uiState: MutableLiveData<GroupListUiState> get() = _uiState
LiveData로 수정해야할 것 같습니다!

2024-08-04 04:17 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/group/list/GroupListViewModel.kt
> +                    }
메서드 분리해도 좋을 것 같아요!

2024-08-04 04:17 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/mylocation/SettingMyLocationViewModel.kt
> +    }
`companion object`는 컨벤션에 맞게 위치를 옮겨야 할 것 같습니다!

2024-08-04 05:22 UTC, junjange approved these changes
고생하셨습니다 ~~👍

2024-08-04 05:23 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/mylocation/SettingMyLocationActivity.kt
> +                1000,
혹시 딜레이는 왜 필요한가요?!

2024-08-04 05:23 UTC, gaeun5744 approved these changes
고생하셨어요!!

2024-08-04 05:25 UTC, jinuemong commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/mylocation/SettingMyLocationActivity.kt
> +                1000,
왜냐면...






로딩 에니매이션 때문입니다 !

2024-08-04 05:25 UTC, merged

2024-08-04 05:29 UTC, dpcks0509 approved these changes
수고하셨습니다~ 화면 UI랑 로직이 제 WoofFragment랑 겹치는게 많아서 나중에 한번 비교하면서 통일해는게 좋을것같아요!

2024-08-04 05:29 UTC, dpcks0509 commented on android/app/src/main/AndroidManifest.xml
>              android:exported="false"
android:screenOrientation="portrait" 회전방지 넣어주시면 감사하겠슴다~

2024-08-04 05:29 UTC, dpcks0509 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/mylocation/SettingMyLocationActivity.kt
> +    private val mapView: MapView by lazy { binding.mapViewMyLocation }
이 화면에 대한 코드가 WoofFragment에 있던거 인것 같은데 제꺼 코드가 많이 바껴서 나중에 다시 같이 수정하는 시간이 있어야 할 것 같아요~