[BE] 주변 발자국 조회 hotfix & 더미데이터 추가
woowacourse-teams/2024-friendogly pull request #294
Opened 2024-08-05 02:05 UTC by ehtjsv2

## 이슈
- #285 

## 개발 사항
- 주변 발자국 조회 반경을 대한민국 전체로 변경
- 주변 발자국 조회시 삭제된 발자국은 조회되지 않는다
- 더미 WalkStatus 다양하게, 한사람이 여러강아지 들고 있도록 추가

2024-08-05 07:33 UTC, takoyakimchi requested changes
사소한 코멘트 남겨봤어요~~

2024-08-05 07:33 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/footprint/controller/FootprintControllerTest.java
> +    }
fyi
보통은 tearDown이라고 쓰는 것 같아요!!!

2024-08-05 07:33 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/footprint/service/FootprintQueryServiceTest.java
> +    @Disabled
아예 삭제하거나, assert 문을 바꿔도 좋겠네요!

2024-08-05 07:33 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintQueryService.java
>                  .map(footprint -> new FindNearFootprintResponse(footprint, footprint.isCreatedBy(memberId)))
```suggestion
        return recentFootprints.stream()
                .filter(footprint -> !footprint.isDeleted() && footprint.isNear(currentLocation))
                .map(footprint -> new FindNearFootprintResponse(footprint, footprint.isCreatedBy(memberId)))
```

혹시라도 범위 내 조회가 부활한다면 이렇게 수정하면 좋을 것 같아요.

1. filter를 중복으로 쓰면 불필요한 객체 생성이 일어나서 성능에 좋지 못해요. [참고 링크](https://www.baeldung.com/java-streams-multiple-filters-vs-condition)
2. 나중에 데이터가 쌓이면 논리 삭제 되어 있는 발자국이, 그렇지 않은 발자국보다 많아질 것 같아요. `&&`는 도도도 잘 아시겠지만 앞의 조건이 false이면 뒤 조건을 검사하지 않기 때문에, 이렇게 바꾸면 불필요한 `isNear` 검사가 줄어들 것 같네요!

2024-08-06 00:51 UTC, ehtjsv2 commented
+ 발자국 저장 시 WalkStatus보내줘야됨(구현예정)

2024-08-06 00:58 UTC, J-I-H-O approved these changes, later dismissed

2024-08-06 00:58 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Footprint.java
> +        return this.location.isWithin(location, NEAR_RADIUS_AS_METER);
조회 반경을 제한을 없앤다면 해당 메서드도 제거해도 되지 않을까요?

2024-08-06 00:58 UTC, J-I-H-O commented on backend/src/test/java/com/woowacourse/friendogly/footprint/service/FootprintQueryServiceTest.java
> +        System.out.println(footprintRepository.findAll().size());
출력문은 제거해주세요~

2024-08-06 01:02 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/footprint/service/FootprintQueryServiceTest.java
> +        System.out.println(footprintRepository.findAll().size());
예리하네요

2024-08-06 04:48 UTC, ehtjsv2 commented on backend/src/test/java/com/woowacourse/friendogly/footprint/service/FootprintQueryServiceTest.java
> +        System.out.println(footprintRepository.findAll().size());
이거뭐지?

2024-08-06 04:48 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Footprint.java
> +        return this.location.isWithin(location, NEAR_RADIUS_AS_METER);
다시 부활할 가능성이 높다생각했기에 지우지않고 반경을 대한민국전체로 바꿨습니다

2024-08-06 11:21 UTC, takoyakimchi approved these changes
LGTM!!

2024-08-07 01:00 UTC, jimi567 approved these changes

2024-08-07 02:40 UTC, merged