[BE] feat: 단체 채팅방 추가
woowacourse-teams/2024-friendogly pull request #298
Opened 2024-08-05 06:06 UTC by takoyakimchi

## 이슈
- #272 

## 개발 사항
- 1대1 채팅방 삭제
- 단체 채팅방 구현
- Club과 ChatRoom 사이 연관관계 설정
- 채팅방에 들어가거나 나가면, 채팅방을 구독하는 사용자에게 알림 메시지가 전달됨
- `data.sql`에서 단체 채팅방 데이터 추가
- Club에 참여했을 때, 채팅방 ID를 함께 응답

## 리뷰 요청 사항
- 8/6 오전까지 리뷰 부탁드립니다.

## 전달 사항
- [이전 PR](https://github.com/woowacourse-teams/2024-friendogly/pull/280)에서 conflict가 발생하여, 현재 develop 브랜치 기준으로 작업하고 새로 PR 보냅니다.
- 다음 PR에서는 1대1 채팅방까지 작업해서 보낼 예정입니다.

2024-08-05 13:36 UTC, ehtjsv2 requested changes
고생했습니다! 트레! chatRoom이 아닌 Club이 연관관계 주인으로 한 이유도 궁금하네요!

2024-08-05 13:36 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/chat/service/ChatRoomCommandService.java
> +        club.addMemberToChat(member);
chatRoom.addMember()가 아니라 club.addMemberToChat()이 어색하게 느껴지네요.
chat의 도메인에서 해결해야할 것 같은 기능인데 club을 거치는 것이 어색합니다.
이유가있나요?

2024-08-05 13:36 UTC, ehtjsv2 commented on backend/src/test/java/com/woowacourse/friendogly/chat/service/ChatRoomCommandServiceTest.java
> +        invalidMember = memberRepository.save(new Member("a", "b", "b@b.com", "https://b.com"));
테스트이지만, 필드를 유추할 수 있는 데이터를 넣어주세요~ 인지비용이 올라갑니다
n과 t가 name과 tag라는 것을 Member클래스 들어가서 확인했습니다. 맨뒤는 이미지였군요

2024-08-05 13:46 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/chat/service/ChatRoomCommandService.java
> +        club.addMemberToChat(member);
원래는 모임에 들어가는 것 == 채팅방에 들어가는 것
이렇게 동일시해서 개발했었는데, 제가 봐도 어색한 것 같아서 현재 local 작업 브랜치에서는 chat이 club을 의존하지 않도록 다 뺀 상태입니다!

<img width="533" alt="image" src="https://github.com/user-attachments/assets/56e7b145-5efb-4b0f-bac1-e022d44f51b7">

2024-08-05 13:49 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/chat/service/ChatRoomCommandServiceTest.java
> +        invalidMember = memberRepository.save(new Member("a", "b", "b@b.com", "https://b.com"));
필드값이 크게 의미 없는 테스트라서 line 수 길어지는 게 싫어서 이렇게 쓰긴 했는데
오히려 더 의문이 들 수 있겠군요! 반영할게요 🫡

2024-08-05 14:00 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/chat/service/ChatRoomCommandService.java
> +        club.addMemberToChat(member);
Club을 연관관계 주인으로 둔 이유는
모임이 생성되면 무조건 채팅방이 생성되기 때문에 모임은 채팅방을 알아야 하는 게 맞는데
채팅방은 1대1 채팅방까지 고려한다면 굳이 모임을 알지 않아도 되기 때문입니다.

이렇게 구현하면 나중에 모임이랑 채팅방의 생명주기가 달라져도 유연하게 정책을 변경할 수 있어요!

2024-08-06 00:50 UTC, ehtjsv2 approved these changes
따봉

2024-08-06 11:15 UTC, closed without merging