[BE] 주변 발자국 알림 기능 구현
woowacourse-teams/2024-friendogly pull request #378
Opened 2024-08-12 08:58 UTC by ehtjsv2

## 이슈
- 

## 개발 사항
-

## 리뷰 요청 사항 (없으면 삭제해 주세요)
- 

# 전달 사항 (없으면 삭제해 주세요)
-

2024-08-15 08:11 UTC, takoyakimchi requested changes

2024-08-15 08:11 UTC, takoyakimchi commented on .github/workflows/.idea/modules.xml
> +</project>
![image](https://github.com/user-attachments/assets/608caf2d-da66-45d9-8de5-8d3a7df426d4)

이 파일들은 auto generated 파일이라고 뜨네요...!
버전 관리 필요한 파일들인가요??

2024-08-15 08:11 UTC, takoyakimchi commented on backend/build.gradle
> +    implementation 'com.google.firebase:firebase-admin:9.2.0'
9.3.0 버전도 있는 걸로 확인되는데, 너무 최신이라서 사용하지 않은 걸까요?!

2024-08-15 08:11 UTC, takoyakimchi commented on backend/.gitignore
> +/src/main/resources/firebase-friendogly-private-key.json
이건 정말 사소하지만...
`### secrets ###` 안에다가 넣어도 될 듯 해요 !!

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/config/FirebaseAppConfig.java
> +        InputStream firebaseCredentialsInputStream = getFirebaseCredentialsInputStream();
개행이 되어 있네요!

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/footprint/service/FootprintCommandService.java
>          this.footprintRepository = footprintRepository;
```suggestion
            NotificationService notificationService,
            DeviceTokenRepository deviceTokenRepository
    ) {
        this.footprintRepository = footprintRepository;
```

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/domain/DeviceToken.java
> +    }
```suggestion
    public void updateDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken;
    }
```

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/domain/DeviceToken.java
> +    private Member member;
not null 붙여주면 어떨까요?

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/service/DeviceTokenService.java
> +public class DeviceTokenService {
`@Transactional` 안 붙여도 될까요?!

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/service/DeviceTokenService.java
> +    private final MemberRepository memberRepository;
```suggestion
    private final DeviceTokenRepository deviceTokenRepository;
    private final MemberRepository memberRepository;
```

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/service/FcmNotificationService.java
> +    }
트랜잭션 + 개행 확인 해주세요!

```suggestion
@Service
@Transactional
@Profile("!local")
public class FcmNotificationService implements NotificationService {

    private final FirebaseApp firebaseApp;

    public FcmNotificationService(FirebaseApp firebaseApp) {
        this.firebaseApp = firebaseApp;
    }
```

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/service/FcmNotificationService.java
> +                .putData("body",content)
전체적으로 확인 부탁해요!

```suggestion
                .putData("title", title)
                .putData("body", content)
```

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/service/FcmNotificationService.java
> +            throw new FriendoglyException("FCM을 통해 사용자에게 알림을 보내는 과정에서 에러가 발생했습니다.");
500 에러로 해도 될 것 같아요!

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/service/NotificationService.java
> +    void sendNotification(String title, String content, List<String> receiverToken);
List는 명시적으로 복수형으로 쓰면 어떨까요??

```suggestion
    void sendNotification(String title, String content, String receiverToken);

    void sendNotification(String title, String content, List<String> receiverTokens);
```

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/dto/request/UpdateDeviceTokenRequest.java
> +}
`@NotBlank` 검증 있어도 좋겠네요

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/service/DeviceTokenService.java
> +    }
```suggestion
    public UpdateDeviceTokenResponse update(Long memberId, UpdateDeviceTokenRequest updateDeviceTokenRequest) {
        DeviceToken deviceToken = deviceTokenRepository.findByMemberId(memberId)
                .map(token -> {
                    token.changeDeviceToken(updateDeviceTokenRequest.deviceToken());
                    return token;
                })
                .orElse(deviceTokenRepository.save(
                        new DeviceToken(memberRepository.getById(memberId), updateDeviceTokenRequest.deviceToken())));

        return new UpdateDeviceTokenResponse(deviceToken.getDeviceToken());
    }
```

map, orElse 써서 약간의 개선이 가능할 것 같아요.

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/service/NotificationService.java
> +    void sendNotification(String title, String content, List<String> receiverToken);
List는 명시적으로 복수형으로 쓰면 어떨까요??

2024-08-15 08:11 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/footprint/service/FootprintQueryServiceTest.java
> +        );
```suggestion
        deviceTokenRepository.save(
                new DeviceToken(otherMember, "token")
        );
```

2024-08-16 01:57 UTC, ehtjsv2 commented on backend/build.gradle
> +    implementation 'com.google.firebase:firebase-admin:9.2.0'
![image](https://github.com/user-attachments/assets/8bdccb15-97c6-45fa-b479-b692da9c7c69)
공식 사이트에서 started에서 권하는 것이 2.0이였습니다.
3.0에서 추가된 기능도 확인했었는데, 특별한 것이 없고 권하고(?)있는 2.0을 사용하기로..

2024-08-16 01:58 UTC, ehtjsv2 commented on backend/.gitignore
> +/src/main/resources/firebase-friendogly-private-key.json
secrets가 생기기 이전에 개발 하던 거라 merge하면서 secret생겼네요.
 secret으로 옮기겠습니다~!

2024-08-16 02:01 UTC, ehtjsv2 commented on .github/workflows/.idea/modules.xml
> +</project>
gitignore는 제 private 파일이 다른 사람이 가져갔을 때도 적용되야해서 추가했습니다.
나머지는 뭔지 모르겠네요., auto generated라는 것은 어떻게 알았나요??
@takoyakimchi

2024-08-16 02:12 UTC, takoyakimchi commented on backend/build.gradle
> +    implementation 'com.google.firebase:firebase-admin:9.2.0'
오오 이런 문서가 있군요 굿

2024-08-16 02:12 UTC, takoyakimchi commented on .github/workflows/.idea/modules.xml
> +</project>
<img width="718" alt="image" src="https://github.com/user-attachments/assets/cd974ce7-121a-4169-952b-2a81f938f2b5">

깃허브에서 알려주더라구요~~!!~

2024-08-16 02:27 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/notification/service/DeviceTokenService.java
> +public class DeviceTokenService {
현재 존재하는 메서드 내에서는 Transactional이 필요한 곳은 없지만, 추후 메서드 생성 시 혼란방지를 위해 미리 추가하겠습니다.

2024-08-16 02:33 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/notification/service/FcmNotificationService.java
> +    }
여기 서비스에는 `@Transactional` 이 필요한 이유가 있을까요??
제 생각에는 commit, rollback 필요한 곳이 없고, 영속성 컨텍스트 연장이 필요한 곳도 없어보여서요!

2024-08-16 04:19 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/service/DeviceTokenService.java
> +    }
(수정) orElseGet을 써야 하는군요... !!!!

2024-08-16 04:30 UTC, takoyakimchi submitted a review, later dismissed
깔끔해졌어요!!!

2024-08-16 04:30 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/domain/NotificationType.java
> +public enum NotificationType {
👍

2024-08-16 04:30 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/notification/service/DeviceTokenCommandServiceTest.java
> +        assertThat(afterSize).isNotEqualTo(beforeSize);
```suggestion
        assertThat(afterSize).isEqualTo(beforeSize + 1);
```

2024-08-16 04:39 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/notification/service/DeviceTokenCommandServiceTest.java
> +
```suggestion
        // given
        long beforeSize = deviceTokenRepository.count();

```

성능 조금이라도 챙겨가면 좋을 것 같아요!!

2024-08-16 05:11 UTC, jimi567 reviewed
어렵네요 fcm 고생하셨습니다.

2024-08-16 05:11 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/footprint/service/FootprintCommandService.java
> +        List<Footprint> footprints = footprintRepository.findByIsDeletedFalse();
리스트 반환하는 쿼리 메소드는 all 붙여주심 안될까욥 ㅠㅠ

2024-08-16 05:11 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/notification/domain/DeviceToken.java
> +    @Column(nullable = false)
이름 옵션 추가해주심 감사용

2024-08-16 05:11 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/notification/dto/request/UpdateDeviceTokenRequest.java
> +        @NotBlank(message = "빈 문자열이나 null을 입력할 수 없습니다.")
어떤게 빈 문자열이나 null갑이 들어왔는지 모를 것 같습니다.

2024-08-16 07:08 UTC, takoyakimchi approved these changes

2024-08-16 07:08 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/notification/controller/DeviceTokenController.java
> +    @PutMapping
👍

2024-08-16 11:03 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/notification/service/FcmNotificationService.java
> +}
한 명의 사용자에게 알림을 보낼 때에도 이 메서드를 사용할 수 있을 것 같아요.
이미 대체제가 있는 상황에서 사용하지 않는 메서드를 남겨두어야 할까요?

2024-08-16 11:03 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/footprint/service/FootprintCommandService.java
> +            DeviceTokenRepository deviceTokenRepository
FootprintService가 너무 많은 역할을 수행하고 있는 것 같아요.
Footprint와 관련된 비즈니스 로직 뿐만 아니라 알림과 관련된 역할까지 수행하고 있는듯 한데, 책임을 분리해주면 좋겠어요.

2024-08-16 11:24 UTC, J-I-H-O approved these changes

2024-08-16 12:18 UTC, merged