[BE] feat: 채팅방에서 모임 정보 조회 API 구현
woowacourse-teams/2024-friendogly pull request #381
Opened 2024-08-12 09:25 UTC by takoyakimchi

## 이슈
- closes #370 

## 개발 사항
- 채팅방에서 모임 정보 조회 가능 -> 모임 ID, 허용되는 강아지 사이즈, 허용되는 강아지 성별
- 채팅방 REST Docs 테스트 코드 추가

2024-08-12 11:17 UTC, jimi567 approved these changes
프로덕트 코드가 짧아서 볼게 많이 없네요.
문서 작성 고생하셨어요.

2024-08-12 11:17 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/chat/dto/response/FindClubDetailsResponse.java
> +    }
응답 dto 따로 가져간거 굿이요

2024-08-13 00:14 UTC, J-I-H-O reviewed
Club 정보를 조회하는데 ChatRoom API를 타는게 다소 어색하게 느껴지네요. 현재 Club에 ChatRoom을 단방향으로 넣어주었는데 조회할 때에는 ChatRoom API를 통해 Club을 조회하는 흐름이에요.
Club쪽에 findByChatRoomId와 같은 API를 만들어주는게 어떨까요?

추가로 Club이 ChatRoom을 가지고 있는 이유 다시 한 번만 설명해주실 수 있을까요!? 이전에 잘 이해를 못해서 ㅎㅎ;

2024-08-13 00:42 UTC, takoyakimchi commented
@J-I-H-O https://github.com/woowacourse-teams/2024-friendogly/pull/298#discussion_r1704170436

2024-08-13 03:06 UTC, jimi567 requested changes

2024-08-13 03:06 UTC, jimi567 commented on backend/src/test/java/com/happy/friendogly/chat/service/ChatRoomQueryServiceTest.java
> +    @Transactional
테스트마다 다 트랜잭션 걸고 있는 것 같아요.
제 생각에 이런 테스트에는 걸 필요가 없을 것 같은데 어찌생각하시나영

2024-08-13 09:03 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/chat/service/ChatRoomQueryServiceTest.java
> +    @Transactional
필요 없는 부분 지워야겠네요
변경감지라고 생각했는데 아니었던 부분이 몇 개 있어서

2024-08-13 11:55 UTC, jimi567 approved these changes
리뷰 반영 감사합니다.~ 고생하셨어욤

2024-08-13 12:16 UTC, ehtjsv2 approved these changes
저도 아침에 말한 것 처럼 땡이와 같은 의견이였는데, 채팅 도메인에서 클럽의 정보를 알기위한 것이기에 Chat컨트롤러에 있는것도 괜찮다 생각이드네요.
response가 클럽에 관한 내용뿐이라 어색해보이지만, 만약 다른 테이블의 정보가 추가된다면 club이 아니라 chat 도메인의 controller에 있는 것이 더 자연스러워보였겠다 싶네요.
마치, footprint 디테일에서 member, pet 관련 다른 모든 내용이 있는 것처럼!
LGTM 👍

2024-08-14 03:25 UTC, J-I-H-O approved these changes

2024-08-14 04:21 UTC, merged