[AN] feat: 프로필 세팅 페이지 에러 핸들링
woowacourse-teams/2024-friendogly pull request #414
Opened 2024-08-15 06:17 UTC by junjange

## 이슈
- close #406

## 개발 사항
- 프로필 설정 에러 핸들링
- 프로필 설정 시 로딩 화면 구현

<img width="40%" src="https://github.com/user-attachments/assets/87da6b6c-f1d4-4ab5-8500-ab0cc6ef0005">

2024-08-15 10:56 UTC, gaeun5744 requested changes

2024-08-15 10:56 UTC, gaeun5744 commented on android/gradle/libs.versions.toml
> +
이거는 `#6기-기술검토` 채널에서 허락받아야할 것 같네요.. 혹시 해당 라이브러리를 꼭 써야하나요?!

2024-08-15 11:30 UTC, junjange commented on android/gradle/libs.versions.toml
> +
하핳 자연스레 썼네옄ㅋㅋㅋㅋㅋ 수정하고 스크린샷 다시 첨부하도록 하겠습니다!!

2024-08-15 13:00 UTC, gaeun5744 approved these changes, later dismissed
수고많았어여~~~!!!!!

2024-08-16 01:32 UTC, jimi567 commented
고생하셧어요.~ 깔끔하네요

2024-08-16 06:23 UTC, dpcks0509 approved these changes
고생했어요~~

2024-08-16 07:37 UTC, gaeun5744 approved these changes

2024-08-16 07:50 UTC, merged