Feature/group detail
woowacourse-teams/2024-friendogly pull request #49
Opened 2024-07-14 15:15 UTC by jinuemong

## 이슈
- close #16 

## 개발 사항
- 멍개 상세 ui 구현했습니다.
- viewModel 생성 후 연결하였습니다.

# 전달 사항 
- 폰트 관련해서 일단 적용 안했는데, 디자인 구체화 작업으로 적용할 예정입니다.
- 이전 pr 관련 ui가 있어서 TODO 달았습니다 !

2024-07-14 15:59 UTC, junjange commented on android/app/src/main/res/layout/fragment_group_detail.xml
> +                app:layout_constraintTop_toTopOf="parent" />
팀 컨벤션 확인해주세요!!

2024-07-14 16:00 UTC, junjange requested changes
고생하셨습니다!!🫡
전체적으로 xml 팀 컨벤션 확인해주세여~~

2024-07-14 16:56 UTC, dpcks0509 submitted a review, later dismissed
고생하셨습니다아! id 값 팀 컨벤션만 수정해주시면 좋을 것 같아요!!

2024-07-14 16:56 UTC, dpcks0509 commented on android/app/src/main/res/values/strings.xml
> +    <string name="group_dog_list_subject">댕댕이들</string>
strings.xml 활용 좋습니다!!👍

2024-07-15 08:47 UTC, gaeun5744 approved these changes, later dismissed
굿굿

2024-07-15 09:10 UTC, jinuemong commented on android/app/src/main/res/layout/fragment_group_detail.xml
> +                app:layout_constraintTop_toTopOf="parent" />
웁스 죄송해요 ~

2024-07-15 11:22 UTC, closed without merging