[BE] feat: 채팅 DB 저장 구현
woowacourse-teams/2024-friendogly pull request #555
Opened 2024-09-10 11:01 UTC by takoyakimchi

## 이슈
- closes #256 

## 개발 사항
- `ChatMessage` 엔티티 정의 및 service, repository 클래스 생성
- 채팅 내역을 DB에 저장
- `ChatSocketController`가 가지던 복잡한 로직을`chatCommandService`가 가지도록 수정

## 리뷰 요청 사항
- 패키지 구조는 추후 개선할 예정입니다. 리뷰에서 제외해주세요.
- 채팅 응답 DTO는 기존에 웹소켓에서 사용하던 명세를 그대로 사용하고 있습니다.

## 전달 사항
- **merge는 스키마 생성 및 dev 서버에서의 테스트 이후 진행해야 합니다.**

2024-09-11 01:28 UTC, jimi567 requested changes
고생하셨어욘,
궁금한게 몇 가지 있어서 코멘트남겨봤습니다.

2024-09-11 01:28 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/chat/domain/ChatMessage.java
> +    private String content;
채팅 내용은 nullable한가요?

2024-09-11 01:28 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/chat/repository/ChatMessageRepository.java
> +
entitygraph는 제가 알기론 디폴트가 eager로 동작하도록 바꿔주는걸로 알아서 type은 생략가능한걸로 알아요.

2024-09-11 01:28 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/chat/repository/ChatMessageRepository.java
> +    }
쿼리크리에이션으로 만든 메소드명이 살벌해서 이런식으로 한 것 같아요.
이렇게 해도 되는데 jpql 작성해도 될 것 같습니다.
위 방식을 채택한 이유가 궁금해요.

2024-09-11 01:28 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/chat/service/ChatCommandService.java
> +        template.convertAndSend("/topic/chat/" + chatRoomId, chat);
/topic/chat/ 계속 반복되는데 상수로 빼주시면 좋을 것 같습니다.

2024-09-11 01:28 UTC, jimi567 commented on backend/src/test/java/com/happy/friendogly/chat/service/ChatCommandServiceTest.java
> +    }
하나로 묶어도 되지 않나요?

2024-09-11 01:34 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/chat/service/ChatCommandServiceTest.java
> +    }
데이터 셋업 -> 테스트 진행 -> 데이터 drop의 플로우가 더 자연스러워 보여서 이렇게 썼어요.

2024-09-11 01:35 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/chat/repository/ChatMessageRepository.java
> +    }
jpql쓰면 코드 라인 길어지기도 하고 query method로 가능한 범위 내에서는 query method 쓰는걸 더 선호해서 이렇게 작성했습니다!

2024-09-11 01:36 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/chat/domain/ChatMessage.java
> +    private String content;
채팅방 참여, 채팅방 나가기도 채팅 테이블 안에 들어가게 될 것 같은데 이 경우 null 혹은 empty string이 됩니다

2024-09-11 01:47 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/chat/repository/ChatMessageRepository.java
> +
오 default가 FETCH로 설정되어 있네요

2024-09-12 00:20 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/chat/repository/ChatMessageRepository.java
> +
@jimi567 
EntityGaphType이 FETCH -> 선택한 속성만 함께 불러옴
EntityGraphType이 LOADING -> 선택한 속성과 EAGER로 설정한 애들은 함께 불러옴
`deafult가 eager로 동작하는 것으로 바꿔주는 것 -> EntityGraphType생략이 가능하다 ` 가 연관관계가 있는 것이 맞나요?

2024-09-12 02:29 UTC, J-I-H-O requested changes
트레~~ 바쁜 와중에 고생 많으셨어요.
코멘트 남겼으니 확인 부탁해요~

2024-09-12 02:29 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/chat/controller/ChatMessageController.java
> +    }
같은 조회 메서드 같은데 따로 분리한 이유가 있을까요?
`findAllByChatRoomId()` 는 넓게 보면 전체 기간으로 조회한 `findRecent()` 아닐까요?

2024-09-12 02:29 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/chat/service/ChatCommandService.java
> +        chatMessageRepository.save(new ChatMessage(chatRoom, LEAVE, senderMember, ""));
이 네 라인이 계속 중복되고 있네요. private 메서드로 분리하는건 어떤가요?
```java
doSomthing(
    new ChatMessageResponse(...),
    new ChatMessage(...)
);
```

2024-09-12 02:29 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/chat/service/ChatCommandService.java
> +        chatMessageRepository.save(new ChatMessage(chatRoom, LEAVE, senderMember, ""));
`ChatMessageResponse` 라는 클래스명이 조금 어색하게 느껴지네요.
지금까지 API 응답 DTO를 response로 네이밍해온 만큼 해당 객체도 클라이언트로 응답될 것이라고 기대했는데, 실제로는 알림을 보내고 채팅을 전송하는 로직에서 사용되고 있어요.
조금 더 명확한 이름으로 바꿔보는건 어떤가요?

2024-09-12 02:29 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/chat/service/ChatQueryService.java
> +        }
데이터 존재 여부 자체를 숨기기 위해 FORBIDDEN 대신 NOT FOUND를 내려주는 경우도 있다고 해요.
참고만 해주세요!

2024-09-12 02:29 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/chat/service/ChatCommandService.java
> +    private final SimpMessagingTemplate template;
`ChatCommandService` 에 책임이 과중된게 아닌가 싶어요.
채팅방 참여 및 탈퇴 + 알림 및 채팅 전송 + 채팅 메시지 저장의 역할을 수행하고 있는데,
채팅방 참여 및 탈퇴 정도는 이전 방식대로 `ChatRoomCommandService` 에 두는게 어떨까요?

2024-09-12 02:29 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/chat/service/ChatCommandService.java
> +        chatMessageRepository.save(new ChatMessage(chatRoom, LEAVE, senderMember, ""));
`ChatMessageResponse`와 `ChatMessage`의 많은 필드가 겹치는 것 같은데, 정적 팩토리 메서드를 사용해보는건 어떨까요?

```java
ChatMessage chatMessage = chatMessageRepository.save(new ChatMessage(chatRoom, LEAVE, senderMember, ""));
ChatMessageResponse chatMessageResponse = ChatMessageResponse.from(chatMessage);
notificationService.sendChatNotification(chatRoomId, chatMessageResponse);
template.convertAndSend("/topic/chat/" + chatRoomId, chatMessageResponse);
```

2024-09-20 04:50 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/chat/controller/ChatMessageController.java
> +    }
API 명세가 확정되지 않아 임의로 개발했어요.

2024-09-20 05:40 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/chat/service/ChatCommandService.java
> +    private final SimpMessagingTemplate template;
그게 더 자연스럽겠네요 👍

2024-09-20 10:04 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/chat/service/ChatCommandService.java
> +        chatMessageRepository.save(new ChatMessage(chatRoom, LEAVE, senderMember, ""));
`ChatMessageResponse`도 엄연히 웹소켓을 이용해서 클라이언트로 응답을 하고 있습니다.
REST API 응답이랑 혼란이 생긴다면 `ChatMessageSocketResponse`라는 이름을 사용할까요?

2024-09-21 08:02 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/chat/repository/ChatMessageRepository.java
> +
제가 말을 이상하게 했나 보네요.
저희 엔티티 연관 관계 패치타입 특별한 이유가 없으면 다 lazy인데,
entitygraph에 속성으로 지정된 연관 관계는 기본적으로 패치타입을 무시하고 eager로 동작하니깐 불필요한 옵션이라고 코멘트한거였어요.

2024-09-21 08:07 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/chat/repository/ChatMessageRepository.java
> +    }
제 생각은 findRecent라는 비즈니스 요소를 포함하고 있는 메소드는 리포지토리에 있으면 안될 것 같다는 생각이 들어서 코멘트 드렸어요.
지금도 괜찮은 것 같습니다.

2024-09-21 08:14 UTC, jimi567 approved these changes, later dismissed

2024-09-21 08:14 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/chat/domain/ChatMessage.java
> +    private String content;
안내 메세지가 테이블에 저장되는 이유를 잘 모르겠어요...
이 부분은 담주에 직접 설명듣겠습니다.!!!!!

2024-09-21 08:15 UTC, jimi567 commented
고생하셨습니다.!!!
채팅 저장도 언능 머지시키고 이것도 쿼리성능 작업에 포함시켜요!!!

2024-09-21 12:06 UTC, ehtjsv2 submitted a review, later dismissed
트레 고생했습니다~! 그동안 많은 코드가 생겼네요. 여러 클래스가 섞여가며 기능을 구현해야되서 구조도 고민했을 것 같아요
시간범위로 채팅 조회하는 것은 findAll하기에는 부담이크니까 클라이언트쪽의 요청으로 만들어진 api인가요?

2024-09-24 01:10 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/chat/controller/ChatMessageController.java
> +    }
중복을 차치하더라도, 한번에 조회하는건 조금 위험할 수 있다는 생각이 드네요.
채팅 메시지 특성상 많은 row가 저장될 수 있다고 생각하는데, 그 많은 데이터를 한 번에 메모리에 올려야 하니까요.
기간과 같은 1차적인 방어 장치가 있어야하지 않나 생각합니다.

2024-09-24 01:23 UTC, J-I-H-O requested changes
책임이 더 분명해져서 좋네요~~
중복 로직도 메서드 추출로 더 깔끔해진 것 같구요. 코멘트 확인 후 답변 주시면 빠르게 어푸루브 하겠습니당

2024-09-24 01:23 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/chat/service/ChatQueryService.java
> +    }
꼼꼼한 검증 좋습니다 👍

2024-09-24 01:23 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/chat/service/ChatRoomCommandService.java
> +    }
검증 로직이 `leave()` 메서드에서 사용되지 않는데, 의도하신걸까요!?

2024-09-24 01:23 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/chat/service/ChatRoomCommandService.java
> +        }
privateChat 일 때, 참가 여부를 확인하는 이유는 무엇인가요?

2024-09-24 01:24 UTC, J-I-H-O commented
https://github.com/woowacourse-teams/2024-friendogly/pull/555#discussion_r1772403330
요것도 확인 부탁드려요 😅

2024-09-24 01:25 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/chat/service/ChatRoomCommandService.java
> +    }
넵 `chatRoom.removeMember(member);` 안에 있습니다

2024-09-24 04:24 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/chat/controller/ChatMessageController.java
> +    }
API 명세가 어떻게 될지 아직 모르는 상황이기도 하고, 나중에 페이징 처리로 개선할 수 있을 것 같네요.
일단은 채팅 DB에 저장되는지부터 확인하고 별도 PR로 작업할게요.

2024-09-24 04:27 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/chat/domain/ChatMessage.java
> +    private String content;
OOO님이 입장하셨습니다.
XXX님이 퇴장하셨습니다.

이런 메시지를 보여주기 위해서 저장하는 거예요.

2024-09-24 04:37 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/chat/service/ChatRoomCommandService.java
> +        }
메서드명이 `validateInvitation()`이 더 맞지 않았을까 싶네요.
그런데 현재는 이 부분 코드를 삭제했어요.

(1) 1대1 채팅방에 초대를 받거나 (2) 모임에 들어간 경우
ChatRoom - Member 매핑 테이블에 매핑 데이터를 추가시키고 있기 때문에
API를 다시 호출할 필요가 없어요.

**-> 그러면 채팅방 입장은 어떻게 검증하고 있는가?**
`WebSocketInterceptor.validateChatSubscription()` 메서드에서 사실 비슷한 내용의 검증을 진행하고 있었어요.
1. 1대1 채팅방의 경우, 내가 초대받은 채팅방만 구독할 수 있음.
2. 모임 채팅방의 경우, 내가 참여한 모임의 채팅방만 구독할 수 있음.

이 차이 때문에 검증을 나눠서 따로 진행하고 있습니다!

2024-09-25 13:06 UTC, J-I-H-O requested changes

2024-09-25 13:06 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/club/service/ClubCommandService.java
> +
Club과 Chat 도메인의 결합도가 점점 높아지고 있는 것 같아요.
현재 기획 상 Club과 Chat의 생명주기가 달라질 수 있는만큼, 추후 기능 확장에 불리한 구조가 되어가고 있는 듯 합니다.
트레는 어떻게 생각하시나요?

2024-09-26 01:27 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/club/service/ClubCommandService.java
> +
새로운 버전 API 만들게요

(기존) 모임 참여하면 채팅방에도 참여
(추가) 모임 참여 API, 채팅방 참여 API를 분리

2024-09-26 01:52 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/club/service/ClubCommandService.java
> +
나중에 `@SubscribeMapping` 메서드 만들면 그 때 추가하면 좋을듯하네요 이건

2024-09-26 02:02 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/club/service/ClubCommandService.java
> +
**모임에 참여 == 채팅방에 참여**인 현재 시점에서는, 채팅방 참여 API를 따로 분리하지 않는 이상 채팅방에 입장했다는 메시지를 이 메서드에서밖에 전송할 수 없을 것 같아요. 이전 버전이 배포되어 있는 만큼 API 분리는 버저닝 등 고려해야 할 사항이 많기 때문에, 생명주기가 달라지면 그 때 고려하기로 하고, 일단은 이렇게 두는 게 좋겠네요.

2024-09-26 02:03 UTC, J-I-H-O approved these changes

2024-09-26 02:07 UTC, ehtjsv2 approved these changes

2024-09-26 02:08 UTC, jimi567 approved these changes

2024-09-26 02:26 UTC, merged