놀이터 도메인 생성 및 Mock API 구현
woowacourse-teams/2024-friendogly pull request #597
Opened 2024-09-28 08:29 UTC by ehtjsv2

## 이슈
- close #595 
- close #596  

## 개발 사항
- 놀이터 도메인 구현
- Mock API 구현

## 리뷰 요청 사항 
- 놀이터 도메인 쪽 설계 부분 괜찮은 지 확인 부탁드립니다
- 놀이터 Controller에서 메소드 시그니처는 그대로 가져갈 것 같으니 해당 부분만 리뷰 부탁드립니다

2024-09-28 08:45 UTC, jimi567 requested changes
주말에도 고생많으셨어요.
mock api 좋은 시도인 것 같아요.

2024-09-28 08:45 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/playground/domain/Location.java
> +        return abs(dist * 60 * 1.1515 * 1609.344);
매직넘버 없애 주세요.
수학을 못해서 각 숫자가 무슨 의미인지 모를 것 같아요ㅠㅠ

2024-09-28 08:45 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/playground/dto/request/UpdatePlaygroundArrivalRequest.java
> +        @DecimalMax(value = "90.0", message = "위도는 -90도 이상 90도 이하로 입력해 주세요.")
@Range 어노테이션 못 쓸라나요?

2024-09-28 09:01 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/domain/Location.java
> +        return abs(dist * 60 * 1.1515 * 1609.344);
엇 이거는 이전 발자국할때도 나온 리뷰였는데 각각 숫자가 아무의미없습니다! 유명한 공식인데 그 공식에도 의미가없습니다

2024-09-28 09:01 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/dto/request/UpdatePlaygroundArrivalRequest.java
> +        @DecimalMax(value = "90.0", message = "위도는 -90도 이상 90도 이하로 입력해 주세요.")
@range한번 알아볼게요~

2024-09-28 09:26 UTC, takoyakimchi requested changes
고생하셨어요 도도!!
덕분에 안드로이드 크루들이 빠르게 작업할 수 있겠네요!!
네이밍 제안만 몇 개 해봤어요.
특히 응답 DTO 부분에서, 다른 도메인에서는 동사 + 도메인 + Response 이런 식으로 쓰고 있어서 맞춰주시면 좋을 것 같습니다!!

2024-09-28 09:26 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/domain/Location.java
> +        return abs(dist * 60 * 1.1515 * 1609.344);
개선한다고 해도 이미 복잡한 공식이라 크게 의미 없을 것 같습니다!!
그냥 믿고 써야 할 듯...

2024-09-28 09:26 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/dto/response/PlaygroundArrivalResponse.java
> +) {
```suggestion
public record UpdatePlaygroundArrivalResponse(
        boolean isArrived
) {
```

2024-09-28 09:26 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/domain/PlaygroundMember.java
> +    private Long id;
```suggestion

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
```

2024-09-28 09:26 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/domain/Location.java
> +    }
메서드 사용 순서대로 정렬하면 어떨까요?
ex)
<img width="429" alt="image" src="https://github.com/user-attachments/assets/e0dd864a-a946-4ba2-9c21-0a1a2b2ae612">

2024-09-28 09:26 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/dto/response/PlaygroundLocationResponse.java
> +public record PlaygroundLocationResponse(
```suggestion
public record FindAllPlaygroundsResponse(
```

2024-09-28 09:26 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/dto/response/PlaygroundDetailResponse.java
> +public record PlaygroundDetailResponse(
```suggestion
public record FindPlaygroundDetailResponse(
```

2024-09-28 09:26 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/dto/response/PlaygroundSummaryResponse.java
> +public record PlaygroundSummaryResponse(
```suggestion
public record FindPlaygroundSummaryResponse(
```

2024-09-28 09:26 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/controller/PlaygroundController.java
> +        return ApiResponse.ofSuccess(new PlaygroundDetailResponse(
```suggestion
    @GetMapping("/{id}")
    public ApiResponse<PlaygroundDetailResponse> findDetailById(@PathVariable Long id) {
        return ApiResponse.ofSuccess(new PlaygroundDetailResponse(
```

2024-09-28 09:26 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/controller/PlaygroundController.java
> +    }
```suggestion
    @GetMapping("/{id}/summary")
    public ApiResponse<PlaygroundSummaryResponse> findSummaryById(@PathVariable Long id) {
        return ApiResponse.ofSuccess(new PlaygroundSummaryResponse(1L, 10));
    }
```

2024-09-28 09:26 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/controller/PlaygroundController.java
> +                List.of(
```suggestion
    @GetMapping("/locations")
    public ApiResponse<List<PlaygroundLocationResponse>> findAll() {
        return ApiResponse.ofSuccess(
                List.of(
```

Playground의 메인 정보가 어차피 Location이기 때문에 Location이라는 말은 없어도 될 것 같아요!

2024-09-28 09:26 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/controller/PlaygroundController.java
> +    }
ID로 조회하는 메서드끼리 서로 붙여 놓으면 어떨까요??

2024-09-28 09:26 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/docs/PlaygroundApiDocsTest.java
귀찮을 수 있는 작업인데 꼼꼼하게 문서화 하셨네요!!

2024-09-28 09:26 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/dto/response/detail/PlaygroundPetDetail.java
> +    ) {
나중에 헷갈리지 않게 dummy라는 이름 붙이신 것 좋습니다!

2024-09-28 09:31 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/dto/response/PlaygroundArrivalResponse.java
> +) {
dto 명세는 이미 확정이면 넘어가도 됩니다!!!

2024-09-28 11:05 UTC, J-I-H-O requested changes
도도 고생 많았어요~ 리뷰 확인 부탁드려용

2024-09-28 11:05 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/playground/domain/PlaygroundMember.java
> +    private LocalDateTime exitTime;
컬럼명은 snake case로 통일시키는게 좋지 않을까요?

2024-09-28 11:05 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/playground/dto/request/UpdatePlaygroundArrivalRequest.java
> +        @DecimalMax(value = "90.0", message = "위도는 -90도 이상 90도 이하로 입력해 주세요.")
![image](https://github.com/user-attachments/assets/a78394f6-6f39-4844-a32e-e1e97ba2a573)

참고로 `@DecimalMax`, `@DeimalMin`, `@Max`, `@Min`, `@Range` 와 같은 어노테이션들은 오차 때문에 공식적으로는 double 타입을 지원하지 않는다고 합니다.
이런 이유로 `-90.000000000000001` 같은 값들을 넣어보면 검증에 실패해야 하는 값인데도 통과하기도 하구요.
정밀한 값이 필요한 부분이 아니라 전혀 신경 쓸 필요는 없지만, 알고 사용하는게 좋을 것 같아요.

2024-09-28 11:05 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/playground/dto/response/PlaygroundDetailResponse.java
> +        long participatePetCount,
그냥 int 타입으로 가져가도 될 듯 합니다.

2024-09-28 11:05 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/playground/dto/request/UpdatePlaygroundArrivalRequest.java
현재 위치를 담아주면 service에서 playground 반경 내에 들어왔는지 확인 후 update 하는 흐름으로 가는게 맞을까요?

2024-09-28 11:05 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/playground/controller/PlaygroundController.java
> +        return ApiResponse.ofSuccess(new PlaygroundDetailResponse(
아래 summary를 조회하는 메서드가 있으니, 트레가 작성해준 것 처럼 확실히 구분이 되었으면 좋겠어요~

2024-09-28 11:05 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/playground/controller/PlaygroundController.java
> +    }
저두 동의합니다~

2024-09-28 11:17 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/domain/PlaygroundMember.java
> +    private LocalDateTime exitTime;
와우 큰일날뻔했다

2024-09-28 11:18 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/dto/request/UpdatePlaygroundArrivalRequest.java
맞습니다!

2024-09-28 16:06 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/domain/PlaygroundMember.java
> +        this.playground = playground;
id가 auto-increment하는 만큼 id 넣는 생성자가 열려있으면 위험할 것 같아요!

2024-09-30 05:13 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/domain/Location.java
> +        return abs(dist * 60 * 1.1515 * 1609.344);
각도를 미터로 바꾸는 공식이라 메서드로 의미부여하는 방법으로 변경했습니다

2024-09-30 05:14 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/dto/response/PlaygroundArrivalResponse.java
> +) {
변경했씁니다!

2024-09-30 05:18 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/controller/PlaygroundController.java
> +        return ApiResponse.ofSuccess(new PlaygroundDetailResponse(
Controller는 외부와 소통하는 곳이라 도메인내부 설계에 의존하지 않으려고 했씁니다.
놀이터를 조회-> 놀이터의 모든 정보가 담긴 정보를 기대
놀이터의 위치만 조회 -> 놀이터의 위치들만 담긴 정보를 기대
놀이터의 요약정보만 조회 -> 놀이터들의 참여정보를 기대

그래서 find가 놀이터Detail이라고 따로 적지는 않고 나머지에 다른 조회 API에 의미들을 부여했습니다

2024-09-30 05:19 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/controller/PlaygroundController.java
> +                List.of(
위의 답변과 동일합니다!

2024-09-30 05:48 UTC, ehtjsv2 commented
![image](https://github.com/user-attachments/assets/783fd7fb-4660-4183-aa95-bde432622507)
response에 위 필드 추가됨

2024-10-01 16:25 UTC, takoyakimchi approved these changes, later dismissed
LGTM 👍

2024-10-01 16:25 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundCommandService.java
> +public class PlaygroundCommandService {
트랜잭션도 미리 붙일까요?

2024-10-02 01:04 UTC, J-I-H-O submitted a review, later dismissed
굳 좋습니당~

2024-10-02 01:04 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/playground/controller/PlaygroundController.java
> +        return ApiResponse.ofSuccess(new FindPlaygroundDetailResponse(
그럼 `findById()` 라는 컨벤션을 따라가는건 어떨까요?

2024-10-02 01:04 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/playground/domain/Location.java
>      }
훤씬 보기 좋네요~~ 😊👍👍

2024-10-02 02:13 UTC, J-I-H-O approved these changes

2024-10-02 02:24 UTC, takoyakimchi approved these changes
👍

2024-10-02 05:19 UTC, jimi567 approved these changes

2024-10-02 05:50 UTC, merged