[BE] fix: .jpg 이외의 이미지도 업로드할 수 있게 수정
woowacourse-teams/2024-friendogly pull request #605
Opened 2024-10-02 05:34 UTC by takoyakimchi

## 이슈
- close #216 

## 개발 사항
- `.jpg` 이외의 이미지 업로드 가능
- 확장자 유지, 파일명은 UUID로 변경
  - `example.jpeg` -> `6f4914d3-144d-4e0c-8859-d0b8ff7d0120.jpeg`
- 이미지 파일이 아닌 경우 예외 발생
- 이미지 파일인지 판단하는 방법: MIME 타입이 `image/`로 시작하는지 판단한다 [참고링크](https://developer.mozilla.org/ko/docs/Web/HTTP/MIME_types#%EC%9D%B4%EB%AF%B8%EC%A7%80_%ED%83%80%EC%9E%85)

## 전달 사항 (없으면 삭제해 주세요)
- dev 환경에서 다른 이미지 파일 업로드, 검증 로직 작동 확인했습니다.

2024-10-02 07:03 UTC, ehtjsv2 reviewed
코멘트 하나 확인부탁드립니다~

2024-10-02 07:03 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/infra/S3StorageManager.java
> +            return "";
확장자가 없는 파일이 s3에 업로드 될 수도 있는 걸 의도한건가요??

2024-10-02 07:38 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/infra/S3StorageManager.java
> +            return "";
넵 맞아요~~~

2024-10-02 13:10 UTC, jimi567 requested changes
확장자 부분 잘 이해가 안갔어요. 제가 놓친 도메인 규칙이 이씅ㄹ까용?

2024-10-02 13:10 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/infra/S3StorageManager.java
> +            return "";
확장자 없는 경우 포함하고 이미지에 관련한 확장자가 아닐 경우에도 예외 주면서 막아야되지 않나요?

2024-10-02 13:17 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/infra/S3StorageManager.java
> +            return "";
content type으로 막고 있슴다

> 이미지 파일인지 판단하는 방법: MIME 타입이 image/로 시작하는지 판단한다 [참고링크](https://developer.mozilla.org/ko/docs/Web/HTTP/MIME_types#%EC%9D%B4%EB%AF%B8%EC%A7%80_%ED%83%80%EC%9E%85)

2024-10-04 01:52 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/infra/S3StorageManager.java
> +                .contentType(contentType)
https://www.iana.org/assignments/media-types/media-types.xhtml#image

순수한 궁금증.. image/jpg 라는 MIME 타입은 없는데 그동안 어떻게 동작하고 있던걸까요..?
자동으로 image/jpeg로 변환되는걸까요?

2024-10-04 02:08 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/infra/S3StorageManager.java
> +                .contentType(contentType)
그러게요 ㄷ ㄷ ㄷ

2024-10-04 06:56 UTC, ehtjsv2 approved these changes, later dismissed
확장자가 없이 이미지가 오는 경우는 거의 없다고 보고, 이미지에 관련된 확장자가 아닐 경우도 MIME로 막고있는 것으로 보아 approve합니다

추정)MIME의 타입은 파일의 확장자로 자동으로 된다!?

2024-10-06 08:17 UTC, J-I-H-O requested changes

2024-10-06 08:17 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/infra/S3StorageManager.java
> +            return "";
요청 헤더는 충분히 조작될 수 있지 않을까요?

[multipart 구조](https://developer.mozilla.org/ko/docs/Web/HTTP/MIME_types#multipartform-data)를 보면 각각의 파트는 고유의 Content-Type을 가집니다.

만약 악성 파일의 Content-Type을 image/... 로 전송하면 현재 구조에서는 S3 업로드를 허용하게 될 것 같아요. Content-Type만 믿으면 안될 것 같고, 추가적인 검증이 필요한 부분 같습니다.

물론 어떻게 검증할지는 좀 더 생각해봐야 하겠지만요!

2024-10-06 08:17 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/infra/S3StorageManager.java
> +            return "";
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/StringUtils.html#getFilenameExtension(java.lang.String)

추가로 StringUtils.getFilenameExtension() 메서드를 사용하면 확장자를 추출하는 현재 메서드는 제거할 수 있겠습니다!

```java
StringUtils.getFilenamExtension(filename);
```

2024-10-06 08:58 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/infra/S3StorageManager.java
> +            return "";
> 요청 헤더는 충분히 조작될 수 있지 않을까요?

이건 당장 생각이 나지 않아서 Issue로 남겨도 좋을 것 같네요.

> 추가로 StringUtils.getFilenameExtension() 메서드를 사용하면 확장자를 추출하는 현재 메서드는 제거할 수 있겠습니다!

반영 완료

2024-10-08 07:34 UTC, ehtjsv2 approved these changes
👍

2024-10-10 03:45 UTC, J-I-H-O approved these changes

2024-10-10 07:52 UTC, jimi567 approved these changes

2024-10-10 08:00 UTC, merged