[BE] fix: .jpg 이외의 이미지도 업로드할 수 있게 수정
woowacourse-teams/2024-friendogly pull request #606
Opened 2024-10-02 07:05 UTC by J-I-H-O

## 이슈
- close #586 

## 개발 사항
- member fetch 전략 LAZY로 수정
- 단건 조회 시 N+1 문제가 발생하는 현상 수정

## 전달 사항
- 이슈에 세부 내용 있습니다~ 참고 부탁드려요!

2024-10-02 07:30 UTC, ehtjsv2 approved these changes, later dismissed
이번 N+1은 더 좋은 공부가 됐네요~! 고생했습니다

2024-10-02 07:30 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/pet/repository/PetRepository.java
> +    Long countByMember(Member member);
이 메서드는 7월부터 사용하던 메서든데, 왜 변경사항으로 잡혔을까요..

2024-10-02 07:30 UTC, ehtjsv2 commented on backend/src/test/java/com/happy/friendogly/pet/service/PetQueryServiceTest.java
> +        assertThat(responses.get(0).id()).isEqualTo(pet.getId());
assertAll사용안한 이유가 따로 있나요?

2024-10-02 07:38 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/pet/repository/PetRepository.java
> +    Long countByMember(Member member);
아 메소드 순서가 바꼈네요~!

2024-10-02 08:12 UTC, takoyakimchi requested changes
고생하셨어요~~

2024-10-02 08:12 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/pet/domain/Pet.java
>      private Member member;
`JoinColumn`에 `name` 옵션 줍시다!

2024-10-02 13:14 UTC, jimi567 approved these changes, later dismissed

2024-10-03 04:32 UTC, takoyakimchi approved these changes

2024-10-03 04:56 UTC, ehtjsv2 approved these changes

2024-10-04 01:25 UTC, merged