놀이터 상세 조회 API 구현
woowacourse-teams/2024-friendogly pull request #607
Opened 2024-10-02 07:15 UTC by ehtjsv2

## 이슈
- close #602 

## 개발 사항
- 놀이터 상세 조회 API 구현
![image](https://github.com/user-attachments/assets/58bb01e0-2d13-4c81-97eb-bc8f13d06354)

## 리뷰 요청 사항
- service를 최대한 짧게 해보려 했으나 비즈니스 로직 상, 더 줄일 수가 없었음. 혹시 방법 떠오르는 사람 있으면 말해주세요
- pet에 대해서는 member수 만큼 N+1터지는데 어쩔 수 없는 부분이겠죠?

## 전달 사항 
- response 응답 값 설명
  - totalPetCount와 arrivedPetCount는 사진상에는 없지만, 왠지 사용할 것 같다고 요청와서 존재하는 필드(피그마에 사용하는 버전 그림도 있음)
  - isParticipating: 참여 여부에 따라,  버튼이 참여하기, 나가기로 다르게 보임
  - PlaygroundPetDetail: 강아지 정보들, 강아지의 상태메세지와 도착유무 또한 있음.

2024-10-02 10:18 UTC, takoyakimchi requested changes
새로운 도메인 개발 고생했어요.
서비스 코드 개선 관련해서는 저도 좀 더 생각해볼게요!

2024-10-02 10:18 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/controller/PlaygroundController.java
> +        return ApiResponse.ofSuccess(response);
```suggestion
    public ApiResponse<FindPlaygroundDetailResponse> findById(@Auth Long memberId, @PathVariable Long playgroundId) {
        FindPlaygroundDetailResponse response = playgroundQueryService.findDetail(memberId, playgroundId);
        return ApiResponse.ofSuccess(response);
```

혼란을 최대한 줄여보면 어떨까요?!

2024-10-02 10:18 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/domain/PlaygroundMember.java
> +)
이거는 왜 필요했나요??

2024-10-02 10:18 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundQueryService.java
> +                .anyMatch(playgroundMember -> playgroundMember.equalsMemberId(callMemberId));
`Playground` 내부로 도메인 로직 넣을 수 있을 것 같네요!

2024-10-03 04:30 UTC, jimi567 requested changes
고생하셧슴다~~~~
코멘트 확인해주세용. 꼭 반영해야 할 건 아니긴해요.
시간이 널널한건 아니니깐. .ㅠ

2024-10-03 04:30 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/playground/domain/PlaygroundMember.java
> +)
저거 제가 썻다가 괜히 이상한 약팔이가 된 것 같네요. 모임쪽에서도 지울 예정입니다.

2024-10-03 04:30 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundQueryService.java
> +                .toList();
이거 dto인데 내부로 밀어 넣을 수 있을 것 같아요.

2024-10-03 04:30 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundQueryService.java
> +            );
지금도 서비스 코드가 좀 길어서, dto 생성하는 로직을 내부로 밀어넣어주시면 좋을 것 같아요.

2024-10-03 04:46 UTC, J-I-H-O requested changes

2024-10-03 04:46 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/playground/domain/PlaygroundMember.java
> +)
개인적으로 `@NamedEntityGraph` 사용은 피하는걸 선호합니다.
연관관계를 맺고있는 엔티티를 한 번에 조회한다는 사실 확인을 위해 repository 뿐만 아니라 도메인까지 확인해야 합니다.

특히 PlaygroundMember 엔티티의 경우 Member 단 하나의 엔티티와 연관관계를 맺고있는데, EntityGraph를 사용하고  싶다면 `@NamedEntityGraph` 대신 `@EntityGraph` 만으로도 충분한 것 같아요.

2024-10-03 04:46 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/playground/domain/PlaygroundMember.java
>  public class PlaygroundMember {
```java
@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "member_id", nullable = false)
private Member member;
```

한 회원은 한 번에 하나의 playground에 참여할 수 있도록 정책을 잡은걸로 기억해요.
그럼 PlayGround와 PlaygroundMember는 일대다 관계가 맞지만, PlaygroundMember와 Member는 일대일 관계가 되어야하지 않을까요?

2024-10-03 04:46 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/playground/repository/PlaygroundMemberRepository.java
> +    List<PlaygroundMember> findByPlaygroundId(Long playgroundId);
```suggestion
    @EntityGraph(value = "graph.PlaygroundMember")
    List<PlaygroundMember> findAllByPlaygroundId(Long playgroundId);
```

2024-10-03 04:46 UTC, J-I-H-O commented on backend/src/test/java/com/happy/friendogly/playground/service/PlaygroundServiceTest.java
> +    }
요건 왜 필요한가요?

2024-10-03 08:27 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/domain/PlaygroundMember.java
> +)
PlaygroundMember는 쿼리 조회시 member는 어떤 상황(기능)에서도 필요한 정보라고 생각했습니다.
그렇기에, JPQL로 항상 쿼리를 작성하는 것보다 한번 엔티티 그래프 지정해주고 repository에서 해당네임만 붙이는 것이 편리하다 생각해서 엔티티그래프 사용했습니다.
중복되는 JPQL fetch join문을 상수화 했다고 생각하면 될 것 같습니다.(80%)

+내 손으로 엔티티그래프 코드 작성해보고 싶었다.(20%)

2024-10-03 08:37 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/domain/PlaygroundMember.java
> +)
1개가 있는데 NamedEntityGraph를 왜썼냐고 물어보면 Playground까지 있었는데 삭제했는데 그대로 Named로 사용된 잔해네요
현재는 아래 처럼 바꿨습니다
```java
@EntityGraph(attributePaths = "member")
    List<PlaygroundMember> findByPlaygroundId(Long playgroundId);
```

2024-10-03 08:40 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/domain/PlaygroundMember.java
> +)
`저거 제가 썻다가 괜히 이상한 약팔이가 된 것 같네요. 모임쪽에서도 지울 예정입니다.`
우테코 4레벨 정도 됐으면, 약팔이에는 당하지 않습니다!

2024-10-03 08:43 UTC, ehtjsv2 commented on backend/src/test/java/com/happy/friendogly/playground/service/PlaygroundServiceTest.java
> +    }
무슨 의미일까요? 테스트에서 사용중이라 필요합니다.
놀이터 상세 정보에서 전체 강아지 마리수, 도착한 강아지 마리수 때문에 강아지 정보도 저장해줘야합니다.

2024-10-03 08:57 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundQueryService.java
> +            );
좋은 생각이네요 service클래스 private 메서드 하나 지웠네요!

2024-10-03 09:00 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundQueryService.java
> +                .anyMatch(playgroundMember -> playgroundMember.equalsMemberId(callMemberId));
```Java
public class Playground {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Embedded
    private Location location;
}
```
playground는 member를 가지고 있지않아서, playground에 넣을 수는 없을 것 같습니다
대신 지금도 비교하는 로직은 도메인내부에 있습니다!

2024-10-03 09:26 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/domain/PlaygroundMember.java
>  public class PlaygroundMember {
중요한 부분 캐치 감사합니다 다행이다

2024-10-03 14:23 UTC, takoyakimchi submitted a review, later dismissed
👍

2024-10-03 14:52 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/playground/domain/PlaygroundMember.java
> +)
관심사의 차이라고 이해하시면 좋을 것 같아요
저희는 엔티티늘 도메인으로 보고 있으니..

2024-10-03 14:53 UTC, jimi567 submitted a review, later dismissed

2024-10-03 17:34 UTC, takoyakimchi commented
pr title 컨벤션에 맞게 수정했어요~

2024-10-04 01:52 UTC, J-I-H-O submitted a review, later dismissed
도도 고생하셨습니다~~~~

2024-10-04 01:52 UTC, J-I-H-O commented on backend/src/test/java/com/happy/friendogly/playground/service/PlaygroundServiceTest.java
> +    }
아~ abstract 클래스인걸 확인하지 못했네요!
해당 클래스 내부에서 사용되지 않고있어 궁금해서 여쭤보았습니다~

2024-10-04 02:26 UTC, takoyakimchi approved these changes
good

2024-10-04 02:27 UTC, J-I-H-O approved these changes

2024-10-04 02:27 UTC, jimi567 approved these changes

2024-10-04 02:27 UTC, merged

2024-10-04 22:25 UTC, takoyakimchi reviewed
유틸 클래스 정의 굿입니다!
테스트도 꼼꼼한게 느껴지네요!

2024-10-04 22:25 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundCommandService.java
> +
말이 좀 어려운 것 같은데 `PLAYGROUND_RADIUS_METER = 150` 이렇게 해놓고 밑에서는 *2 해서 쓰는게 어떨까요
"예외가 발생하는 거리의 경계"는 결국 `RADIUS * 2`이기도 하고 변경에도 유연할 것 같아요.

2024-10-04 22:25 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundCommandService.java
> +                PLAYGROUND_EXCEPTION_DISTANCE_THRESHOLD);
Location한테 물어봐도 좋을 것 같아요

```java
// Location
    public double plusLatitude(double meter) {
        return GeoCalculator.calculateLatitudeOffset(latitude, meter);
    }
    public double minusLatitude(double meter) {
        return plusLatitude(-meter);
    }
    public double plusLongitude(double meter) {
        return GeoCalculator.calculateLongitudeOffset(latitude, longitude, meter);
    }
    public double minusLongitude(double meter) {
        return plusLongitude(-meter);
    }
```

2024-10-04 22:25 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundCommandService.java
> +                PLAYGROUND_EXCEPTION_DISTANCE_THRESHOLD);
```suggestion
        Location location = new Location(latitude, longitude);
        double startLatitude = location.minusLatitude(PLAYGROUND_RADIUS_METER);
        double endLatitude = location.plusLatitude(PLAYGROUND_RADIUS_METER);
        double startLongitude = location.minusLongitude(PLAYGROUND_RADIUS_METER);
        double endLongitude = location.plusLongitude(PLAYGROUND_RADIUS_METER);
```

그럼 이렇게 쓸 수 있을듯! `Location` 정의해놓은 이상 최대한 활용하면 좋을 것 같아서요

2024-10-04 22:25 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/playground/repository/PlaygroundRepositoryTest.java
> +        assertThat(playgrounds.size()).isOne();
`assertThat(playgrounds).hasSize(1)` 이렇게 하면 어떨까요? 점 하나라도 줄이기

2024-10-04 22:25 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/playground/repository/PlaygroundRepositoryTest.java
> +                .findAllByLocation_LatitudeBetweenAndLocation_LongitudeBetween(9, 11, 9, 11);
위도 경도가 int가 아닌만큼
더 작은 단위로 경계값 챙겨가도 좋을 것 같아요

2024-10-04 22:25 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/playground/service/PlaygroundCommandServiceTest.java
> +    @DisplayName("멤버가 놀이터를 등록하면 해당 멤버는 놀이터에 자동으로 참가")
new line 2개네요!

2024-10-04 22:25 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/playground/service/PlaygroundCommandServiceTest.java
> +        double longitudeFar299mFromA = 127.123430;
`longitudeFar299mFromA `는 `GeoCalculator`로 만들어도 좋겠네요

2024-10-04 22:25 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/playground/service/PlaygroundCommandServiceTest.java
> +        double longitudeFar299mFromA = 127.123430;
latitude가 299m 차이 나는 테스트 케이스도 만들면 어떨까요?

2024-10-04 22:25 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/playground/service/PlaygroundQueryServiceTest.java
> +    void findLocationsWithIsParticipatingFalse() {
true -> false

2024-10-04 22:25 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/utils/GeoCalculator.java
> +
요긴하게 쓰일 수 있을 것 같아요.
`Location`에 있는 `calculateDistanceInMeters()`의 세부 로직도 여기로 넣어도 될 것 같네요.

2024-10-04 22:36 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/playground/dto/response/SavePlaygroundResponse.java
> +    }
저희 초기 개발할때 DTO에서 팩토리 메서드 제거하고 부생성자로 쓰기로 했었습니다!

2024-10-07 07:17 UTC, ehtjsv2 commented on backend/src/test/java/com/happy/friendogly/playground/repository/PlaygroundRepositoryTest.java
> +                .findAllByLocation_LatitudeBetweenAndLocation_LongitudeBetween(9, 11, 9, 11);
정확히 오차가 어느만큼 나는 지도 알기 어려운 뿐더러, 1m의 오차범위로 검증하는 것은 충분하다고 생각합니다.

2024-10-07 08:24 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundCommandService.java
> +
RADIUS * 2가 하나의 수식처럼 느껴저서 변경한 부분이었는데요, 
RADIUS * 2 라는 것이 왜 예외가 발생하는 숫자인가를 생각하게 하는 것이 좋을지,
PLAYGROUND_EXCEPTION_DISTANCE_THRESHOLD = 300 로 그냥 300m넘으면 예외가 발생하는구나 라고 느끼게 하는 것이 좋을지를 생각했습니다.

도메인 규칙을 이해하는 것이 더 중요하다고 생각하여 트레의 추천대로 바꿨습니다

2024-10-07 08:26 UTC, ehtjsv2 commented on backend/src/test/java/com/happy/friendogly/playground/repository/PlaygroundRepositoryTest.java
> +                .findAllByLocation_LatitudeBetweenAndLocation_LongitudeBetween(9, 11, 9, 11);
meter가 아니네요..,

2024-10-07 08:30 UTC, ehtjsv2 commented on backend/src/test/java/com/happy/friendogly/playground/repository/PlaygroundRepositoryTest.java
> +                .findAllByLocation_LatitudeBetweenAndLocation_LongitudeBetween(9, 11, 9, 11);
이 테스트는 쿼리메소드가 잘 작동하는 지에 대한 테스트이고 구현이 제가 한게 아니니까 경계값 테스트 안해도 되겠네요!

2024-10-07 08:49 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundCommandService.java
> +
```suggestion
   private static final int PLAYGROUND_RADIUS = 150;
    private static final int MAX_NON_OVERLAP_DISTANCE = PLAYGROUND_RADIUS * 2;
```

2024-10-10 04:26 UTC, J-I-H-O reviewed
도도~~~~~ 고생하셨습니다. 리뷰 꼭 확인해주세요~

2024-10-10 04:26 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundQueryService.java
> +                        playgroundMemberRepository.existsByPlaygroundIdAndMemberId(playground.getId(), memberId)
스트림에서 쿼리를 날리고 있네요!
조회된 모든 playgrounds 수만큼 쿼리가 나갈텐데, N+1 문제를 직접 만든 상황 아닐까요? 🥺

먼저 현재 Member가 참여한 Playground를 조회해온 다음, 스트림에서는 현재 보고있는 Playground가 이전에 조회된 Playgound인지 확인하도록 개선할 수 있을 것 같아요~

```java
public List<FindPlaygroundLocationResponse> findLocations(Long memberId) {
    List<Playground> playgrounds = playgroundRepository.findAll();
    Playground joinedPlayground = playgroundMemberRepository.findByMemberId(memberId);
    
    return playgrounds.stream()
                .map(playground -> new FindPlaygroundLocationResponse(
                        playground.getId(),
                        playground.getLocation().getLatitude(),
                        playground.getLocation().getLongitude(),
                        playground.isSameWith(joinedPlayground)
                )).toList();
}
```

2024-10-10 04:45 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundQueryService.java
> +                        playgroundMemberRepository.existsByPlaygroundIdAndMemberId(playground.getId(), memberId)
스트림에서 쿼리를 날리고 있네요!
조회된 모든 playgrounds 수만큼 쿼리가 나갈텐데, N+1 문제를 직접 만든 상황 아닐까요? 🥺

먼저 현재 Member가 참여한 Playground를 조회해온 다음, 스트림에서는 현재 보고있는 Playground가 이전에 조회된 Playgound인지 확인하도록 개선할 수 있을 것 같아요~

```java
public List<FindPlaygroundLocationResponse> findLocations(Long memberId) {
    List<Playground> playgrounds = playgroundRepository.findAll();
    Playground joinedPlayground = playgroundMemberRepository.findByMemberId(memberId);
    
    return playgrounds.stream()
                .map(playground -> new FindPlaygroundLocationResponse(
                        playground.getId(),
                        playground.getLocation().getLatitude(),
                        playground.getLocation().getLongitude(),
                        playground.isSameWith(joinedPlayground)
                )).toList();
}
```

2024-10-10 06:12 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/playground/service/PlaygroundQueryService.java
> +                        playgroundMemberRepository.existsByPlaygroundIdAndMemberId(playground.getId(), memberId)
와 그렇네요~! 두번의 쿼리로 해결될 문제였네요!! 너무 좋은 의견입니다!