[BE] feat: 놀이터 등록, 전체 놀이터 위치 조회 API 구현
woowacourse-teams/2024-friendogly pull request #618
Opened 2024-10-04 06:31 UTC by ehtjsv2

## 이슈
- close #609 
- close #608 
- close #613 
- close #617

## 개발 사항
- 놀이터 등록 API
- 전체 놀이터 위치 API
- 내 강아지 존재 유무 API

## 리뷰 요청 사항 
- 특정 commit push 사고로 인해, 여기서 리뷰...해주세요....죄송합니다...
https://github.com/woowacourse-teams/2024-friendogly/pull/607/files/793eaee1c21b5108812281ae8444d8e013d4a76e..ab7e50632397faa3e2aa8288a4553e4fa09c6016

## 전달 사항 
- GeoCalculator에 대해서 궁금하다면 #613 이슈 참고

2024-10-04 22:28 UTC, takoyakimchi requested changes
[이전 PR에 있는 리뷰 참고해주세요](https://github.com/woowacourse-teams/2024-friendogly/pull/607#pullrequestreview-2349321834)

2024-10-04 22:34 UTC, takoyakimchi requested changes
👍

2024-10-04 22:34 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/pet/controller/PetController.java
> +    }
```suggestion
    @GetMapping("/exists/mine")
    public ApiResponse<FindPetExistenceResponse> checkPetExistence(@Auth Long memberId) {
        FindPetExistenceResponse response = petQueryService.checkPetExistence(memberId);
        return ApiResponse.ofSuccess(response);
    }
```

existMine은 어색한 것 같아요. 네이밍 제안해봅니다~

2024-10-04 22:34 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/pet/service/PetQueryServiceTest.java
> +    @Test
```suggestion

    @DisplayName("멤버가 가진 펫이 한마리라도 있는 지 알 수 있다 : True")
    @Test
```

2024-10-06 09:11 UTC, jimi567 submitted a review, later dismissed

2024-10-07 08:56 UTC, takoyakimchi submitted a review, later dismissed
고생했어요 도도 ~~ 🦤

2024-10-08 08:52 UTC, takoyakimchi approved these changes, later dismissed
👍

2024-10-09 05:23 UTC, jimi567 submitted a review, later dismissed
고생하셨어요. 유틸 클래스 지양해야 한다는 건 알지만, geo계산기를 
utilClass로 빼니깐 더 깔끔하네용

2024-10-10 04:38 UTC, J-I-H-O requested changes
고생하셨습니다! 
이번 PR에서 말씀드릴만한건 없는 것 같구, 이전 PR에 남긴 리뷰 꼭 확인 부탁드릴게요. 
N+1 문제를 직접 만들고 있어요!!!

https://github.com/woowacourse-teams/2024-friendogly/pull/607#pullrequestreview-2358864560

2024-10-10 08:40 UTC, takoyakimchi approved these changes
LGTM

2024-10-10 08:41 UTC, J-I-H-O approved these changes

2024-10-10 08:42 UTC, merged