feat: 강퇴 API 구현
woowacourse-teams/2024-friendogly pull request #629
Opened 2024-10-08 12:57 UTC by jimi567

## 이슈
- close #

## 개발 사항
- 모임 강퇴 API 구현했습니다.
- 방장이 아니면 403, 자기 자신을 강퇴하려고 하면 예외처리를 추가했어요.

2024-10-09 12:49 UTC, takoyakimchi approved these changes
위브 고생했어요!!

2024-10-09 12:49 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/club/service/ClubCommandService.java
> +        }
사소하지만 둘의 순서를 바꾸면 좋겠네요.
예를 들면 member ID = 1(방장), 2, 3, 4 가 있는 모임이 있고
모종의 이유로 4번이 1번을 강퇴 시도하는 경우,
가장 먼저 마주하는 예외 메시지는 `자기 자신은 강퇴할 수 없습니다.`인데요.
실제로는 `강퇴 권한이 없습니다.`가 먼저 발생해야 할 것 같아서요!

2024-10-09 12:49 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/club/service/ClubCommandService.java
> +    private void validateKick(Club club, Member owner, Member kickedMember) {
```suggestion

    private void validateKick(Club club, Member owner, Member memberToKick) {
```

이름 제안해봅니다. 과거형 쓰면 메서드 호출 시점에 이미 kick 되었다는 느낌이 들 것 같아요.

2024-10-09 12:49 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/club/service/ClubCommandServiceTest.java
> +    void kickMember_FailForbidden() {
예외 상황 테스트죠?
displayname 수정이 누락된 것으로 보이네요!

2024-10-09 12:49 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/docs/ClubApiDocsTest.java
> +        doNothing()
```suggestion
    void kick_204() throws Exception {
        DeleteKickedMemberRequest request = new DeleteKickedMemberRequest(2L);
        doNothing()
```

2024-10-09 12:49 UTC, takoyakimchi commented on backend/src/test/java/com/happy/friendogly/docs/ClubApiDocsTest.java
> +        DeleteKickedMemberRequest request = new DeleteKickedMemberRequest( 2L);
```suggestion
    @Test
    void kick_403() throws Exception {
        DeleteKickedMemberRequest request = new DeleteKickedMemberRequest(2L);
```

2024-10-09 12:50 UTC, takoyakimchi requested changes
.

2024-10-10 02:53 UTC, J-I-H-O requested changes
위브 고생하셨습니다~

2024-10-10 02:53 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/club/dto/request/DeleteKickedMemberRequest.java
> +) {
![image](https://github.com/user-attachments/assets/619c4d18-4afc-475a-beaf-8e622a979188)
적어주신 예외 메시지와 달리 `@Positive` 어노테이션만으로는 null 검증을 수행할 수 없는 것 같아요~
`@NotNull` 어노테이션을 추가하고, `@Positive`의 예외 메시지는 다르게 적어주는게 좋겠어요

2024-10-10 02:53 UTC, J-I-H-O commented on backend/src/main/java/com/happy/friendogly/club/service/ClubCommandService.java
> +        }
트레 의견에 덧붙이자면, 위 조건문 자체가 혼란을 일으키는 것 같아요. 아래처럼 명시적으로 가는건 어떨까요?

```java
if (!club.isOwner(owner)) {
    throw new FriendoglyException("강퇴 권한이 없습니다.", HttpStatus.FORBIDDEN);
}
if (owner.isSameMember(kickedMember)) {
    throw new FriendoglyException("자기 자신은 강퇴할 수 없습니다.");
}
```
대신 이렇게 하려면 Member에 `isSameMember()` 라는 새로운 메서드를 만들어야하는데, 만들어두면 ClubPet과 ClubMember의 `isSameMember()` 에서도 활용할 수 있으니 괜찮지 않나 싶어요.
주제가 좀 다르다 싶으면 다른 PR에서 작업해도 되구요.

2024-10-10 12:04 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/club/service/ClubCommandService.java
> +    private void validateKick(Club club, Member owner, Member kickedMember) {
과거형이라기보다 수동태 생각하고 쓴 느낌인데 좀 이상한가요?

2024-10-10 12:06 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/club/service/ClubCommandService.java
> +        }
1. 강퇴자가 방장을 강퇴한다.
2. 방장만 강퇴 권한이 있으니깐 피강퇴자가 방장이면 자기 자신이다.
이런 플로우로 생긴 예외처리에요. 
트레 말대로 순서가 바뀌면 더  좋을 것 같아요.

2024-10-10 12:06 UTC, jimi567 commented on backend/src/test/java/com/happy/friendogly/club/service/ClubCommandServiceTest.java
> +    void kickMember_FailForbidden() {
네 복붙했어요 ㅎㅎ

2024-10-10 12:06 UTC, jimi567 commented on backend/src/test/java/com/happy/friendogly/docs/ClubApiDocsTest.java
> +        doNothing()
코드 리포맷팅을 docs에서는 쓸 수 없다보니.. 이런상황이 생겼네요

2024-10-10 12:07 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/club/dto/request/DeleteKickedMemberRequest.java
> +) {
positeveOrZero는 notnull이라서 positive도 그럴거라 생각했어용.

2024-10-13 20:29 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/club/service/ClubCommandService.java
> +    private void validateKick(Club club, Member owner, Member kickedMember) {
수동태라고 해도 member to be kicked가 되어야 할 것 같네요. 아직 강퇴당한 상태가 아니니까요!

2024-10-14 10:31 UTC, takoyakimchi approved these changes
잘 반영됐네요 굿입니다.

2024-10-14 11:28 UTC, ehtjsv2 approved these changes
👍

2024-10-14 11:55 UTC, J-I-H-O approved these changes
굿~ 고생하셨습니당!

2024-10-14 11:55 UTC, merged