[AN] v0.4.1 QA 유저 관련 이슈
woowacourse-teams/2024-friendogly pull request #635
Opened 2024-10-09 14:08 UTC by junjange

## 이슈
- close #574 

## 개발 사항
- 강아지 네이밍 공통화
- 강아지 등록 완료시, 등록 완료! 라는 문구 수정
- 강아지 생성 → 생일 미래 날짜 관련
- 상대 유저 프로필 페이지 햄버거 바 수정

## 전달 사항
"댕댕이 사진을 추가하세요 → 사진 추가 인식 범위 너무 넓어요" 라는 이슈는 한번 더 이야기 해보면 좋을 것 같아 반영하지 않았습니다.

2024-10-10 04:51 UTC, gaeun5744 requested changes
브랜치명이 에띠네요
코멘트 확인해주시면 감사하겠습니다! 짱 수고하셨어요~

2024-10-10 04:51 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/registerpet/bottom/EditPetBirthdayBottomSheet.kt
> +            maxValue = currentMonth
이렇게하면 올해가 아닌 년도에도 적용되지않나요?
2023년 11월이 안되는것 같습니다ㅠㅠ

2024-10-10 06:21 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/registerpet/bottom/EditPetBirthdayBottomSheet.kt
> +            maxValue = currentMonth
헉,, 그러네여,,,

2024-10-10 07:01 UTC, jinuemong submitted a review, later dismissed
고생하셨습니다 !!! 깔끔하네요

2024-10-10 08:19 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/registerpet/bottom/EditPetBirthdayBottomSheet.kt
> +            maxValue = currentMonth
수정했습니다~~

2024-10-11 05:14 UTC, jinuemong approved these changes
굳굳 로직 오류도 해결되었군요

2024-10-11 05:50 UTC, gaeun5744 approved these changes
넘 잘 고쳤다!! 짱이다!!

2024-10-11 07:35 UTC, merged