[BE] 모임 최대 인원 요구사항 변경 반영
woowacourse-teams/2024-friendogly pull request #653
Opened 2024-10-14 10:19 UTC by jimi567

## 이슈
- close #

## 개발 사항
-  제목이 곧 내용

-

2024-10-14 10:34 UTC, takoyakimchi requested changes
`SaveClubRequest`
`chat/domain/MemberCapacity`
누락되었습니다! 채팅 제가 작업 안하는 파일이라 수정해도 됩니다!

2024-10-14 11:52 UTC, takoyakimchi approved these changes
LGTM

2024-10-14 11:59 UTC, J-I-H-O approved these changes
굿~ 좋습니다!

2024-10-15 01:19 UTC, ehtjsv2 approved these changes

2024-10-15 01:19 UTC, merged