[AN] feat: 놀이터 기능 개발
woowacourse-teams/2024-friendogly pull request #660
Opened 2024-10-16 01:10 UTC by dpcks0509

## 이슈
- close #659 

## 개발 사항
- 기존 친구 찾기 -> 놀이터로 기능 수정하였습니다.

## 전달 사항 (없으면 삭제해 주세요)
- 패키지 woof -> playground로 수정해서 file changed가 많아요~
- service 버전 대응은 다음 pr에 추가로 해서 올리겠습니다~

2024-10-16 02:28 UTC, junjange requested changes
진짜 진짜 고생 많으셨습니다!!
코멘트 한 번 확인해주세요!!

2024-10-16 02:28 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +            }
ViewModel로 분리하면 좋을 것 같아요

2024-10-16 02:28 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +            patternInterval = 60
이미 많은 매직 넘버를 상수화했으니! 이것도 하면 좋을 것 같아요!

2024-10-16 02:28 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +        myPlaygroundMarker.circleOverlay.map = null
ViewModel로 뺄 수 있을 것 같아요!

2024-10-16 02:28 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +    }
ViewModel로 뺄 수 있을 것 같아요!

2024-10-16 02:28 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +                        viewModel.loadPlaygroundInfo(myPlayground.id)
ViewModel로 뺄 수 있을 것 같아요!

2024-10-16 02:28 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +                        viewModel.updateUiState(PlaygroundUiState.ViewingPlaygroundInfo)
ViewModel로 뺄 수 있을 것 같아요!

2024-10-16 02:28 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +                }
ViewModel로 뺄 수 있을 것 같아요!

2024-10-16 02:28 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +            }
ViewModel로 뺄 수 있을 것 같아요!

2024-10-16 02:28 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +            myPlayground.circleOverlay.center = myPlayground.marker.position
ViewModel에 있는 프로퍼티를 직접 조작하는게 좀 어색해보여요!

2024-10-16 02:28 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +    }
ViewModel로 뺄 수 있을 것 같아요!

2024-10-16 02:28 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/viewmodel/PlaygroundViewModel.kt
> +            viewModelScope.launch {
BaseViewModel에서 커스텀 코루틴 스코프를 사용하면 좋을 것 같아요!

2024-10-16 02:28 UTC, junjange commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/viewmodel/PlaygroundViewModel.kt
> +            viewModelScope.launch {
PlaygroundViewModel에 모든 부분에 해당됩니다!

2024-10-16 04:52 UTC, gaeun5744 requested changes
수고하셨습니다~ 가장 기능 구현이 많았는데 정말 고생 많으셨어요!
코멘트 몇가지만 확인해주시면 감사하겠습니다! 혹시 이해 안가는 부분 있으면 말씀해주세요~

2024-10-16 04:52 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/message/MessageActivity.kt
> +    BaseActivity<ActivityMessageBinding>(R.layout.activity_message) {
지금 채팅에서 다양한 Message라는 네이밍을 사용하고 있습니다..!
둘을 명확하게 구분할 수 있도록 `PlayGroundStateMessage` 등의 네이밍처럼 구체화 해주세요!!

2024-10-16 04:52 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +                    )
로직에서 스낵바가 과도하게 많아 보입니다! 
dialog와 ballon을 제외하고는 로직이 비슷해 보이는데, 따로 파일을 만들어 로직을 분산하는게 어떨까요?!

확장메서드를 이용해 
```
@StringRes
fun PlaygroundAlertAction.toUiText():Int = 
    // ...
```
이런 식으로 하면 로직이 간단해질 것 같습니다!

2024-10-16 04:52 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +            )
postDelay 코드를 제거해도 기능이 잘 작동하는것 같습니다..! 한번 확인해주시면 감사하겠습니다!

2024-10-16 04:52 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +                        viewModel.updateRefreshBtnVisibility(false)
```suggestion
                        binding.btnWoofFootprintRefresh.isVisible = false
```

바로 activity에서 뷰를 바꿀 수 있네요..! 
`activity -> viewModel -> xml -> bindingAdapter` 로 불필요한 과정을 거치는 것 같습니다!

2024-10-16 04:52 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +        )
bottomSheet Animation과 연관있기 때문에 `delay`를 준 것이라면, 기존에 있던 `ANIMATE_DURATION_MILLIS`를 써서 애니메이션을 위한 지연임을 명시하는 것이 좋을 것 같습니다.

2024-10-16 04:52 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +                petDetailAdapter.submitList(emptyList())
liveData의 default value로 emptyList()를 넣어주세요!!

2024-10-16 04:52 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/viewmodel/PlaygroundViewModel.kt
> +        val playgroundInfo: LiveData<PlaygroundInfoUiModel?> get() = _playgroundInfo
왜 nullable 타입으로 선언하셨나요? 
null을 활용한 분기처리가 없어 보여서 질문 드립니다.

2024-10-16 04:52 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +                    }
지금 고칠 부분은 아니지만, 추후 activity에서 dispatcher를 확장할 때 제약사항이 생길 것 같습니다! 
또한 fragment에서 activity에 대한 중요한 로직을 제어하는게 어색해 보이네요..!

2024-10-16 04:52 UTC, gaeun5744 commented on android/app/src/main/java/com/happy/friendogly/presentation/ui/playground/PlaygroundFragment.kt
> +        }
viewModel이 viewModel에게 일을 시키는 로직은 최대한 지양해주세요!

2024-10-17 08:46 UTC, junjange approved these changes
리뷰 반영은 다음에 부탁해요~~ 수고하셨습니다~~

2024-10-17 08:46 UTC, gaeun5744 approved these changes
구우웃

2024-10-17 08:47 UTC, merged