[BE] chore: 단일 DB로 변경, 인메모리 메시지 브로커 적용
woowacourse-teams/2024-friendogly pull request #746
Opened 2024-12-01 12:59 UTC by takoyakimchi

## 이슈
- close #744 
- close #745 

## 개발 사항
- AWS 비용 지원이 종료됨에 따라 DB replication을 적용 해제하고 단일 DB 사용하는 방식으로 변경

## 전달 사항 (없으면 삭제해 주세요)
- 기존 코드는 최대한 살리는 방향으로 수정했습니다.
- DB는 테스트 완료했습니다. 무중단 배포 스크립트에서 설정값을 수정한 후 merge하면 될 것 같아요.
- 메시지 브로커는 S3 설정이 완료되면 테스트 하면 될 것 같습니다.

2024-12-02 14:12 UTC, jimi567 requested changes, later dismissed

2024-12-02 14:12 UTC, jimi567 commented on backend/src/main/resources/application-prod.yml
> +
저희 mysql rds쓰나요..?

2024-12-02 14:12 UTC, jimi567 commented on backend/src/main/java/com/happy/friendogly/chatsocket/config/WebSocketInMemoryConfig.java
> +@Profile("local | dev | prod")
저희 모든 환경에서 인메모리 메세지로 바꿀 것 같은데
굳이 프로파일 설정안해도 될 것 같아요.
추가하신 특별한 이유가 있는지 궁금합니다.

2024-12-03 02:19 UTC, ehtjsv2 submitted a review, later dismissed
👍

2024-12-03 02:21 UTC, ehtjsv2 commented on backend/src/main/java/com/happy/friendogly/chatsocket/config/WebSocketInMemoryConfig.java
> +@Profile("local | dev | prod")
제 생각에는 InMemory를 현재 상황에서 local, dev, prod 모두에서 사용중이다 라는 것을 명시적으로 코드에서 보여주고 싶었던 것일 거 같아요. 그렇게 생각하니 좋아보이네요! 나중에 봤을 때 생각의 여지도 적어질 것 같구요

2024-12-03 06:42 UTC, takoyakimchi commented on backend/src/main/java/com/happy/friendogly/chatsocket/config/WebSocketInMemoryConfig.java
> +@Profile("local | dev | prod")
원래 환경별로 분리하는 것을 염두에 두고 작성한 코드였어서 그대로 두려고 했었는데 
지금 상황에서는 생략해도 좋아보이네요

2024-12-03 06:58 UTC, ehtjsv2 approved these changes, later dismissed

2024-12-03 07:07 UTC, ehtjsv2 approved these changes

2024-12-03 07:07 UTC, J-I-H-O approved these changes

2024-12-03 07:07 UTC, merged