[BE] refactor: 발자국 리팩터링
woowacourse-teams/2024-friendogly pull request #92
Opened 2024-07-17 06:42 UTC by takoyakimchi

## 이슈
- #79 

## 개발 사항
- 가독성 개선
- API 명세를 위한 테스트 코드 작성
- 로직 변경 

## 전달 사항
- Spring REST Docs 템플릿 관련 논의가 필요할 것 같아요. 나중에 하나로 묶어서 부모 클래스 만들어도 될 듯.
- 커스텀 예외를 만드는 것도 좋을 것 같네요. 이것도 나중에 같이 작업해봐요.

2024-07-17 07:24 UTC, ehtjsv2 approved these changes, later dismissed
리팩토링 좋아요~~

2024-07-17 07:24 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Location.java
> +import static java.lang.Math.*;
인텔리제이에서 자동으로 와일드카드를 사용하게 하는 옵션이 켜져있는 걸까요?

팀끼리 혼동을 야기할 가능성이 있는 와일드 카드는 지양하는 것이 어떤가 싶네요~! 

한번 팀끼리 이야기해보죠

2024-07-17 08:44 UTC, jimi567 requested changes

2024-07-17 08:44 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Location.java
> +        return abs(dist * 60 * 1.1515 * 1609.344);
``` return abs(dist * 60 * 1.1515 * 1609.344);```

이 부분 공식에서 각 값에 의미를 부여하기 힘들다면, 
해당 반환문을 메서드로 따로 빼서 네이밍 해주면 이해하기 쉬울 것 같은데 어떠신가요?

2024-07-17 08:44 UTC, jimi567 commented on backend/src/test/java/com/woowacourse/friendogly/footprint/controller/FootprintControllerTest.java
> +    private FootprintCommandService footprintCommandService;
이거 RestDocs Base 코드 있어요. 추상 클래스라서 예시 Member 문서 테스트 참고해서 다시 작성해주시면 감사하겠습니다.

2024-07-17 08:44 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
> +            .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 사용자 ID입니다."));
이 부분도 저희 커스텀 예외 만들어둔걸로 대체해주세요.!

예외처리 repo로 내리는건 추후에 service 두꺼워지면 고려해봅시다

2024-07-17 08:47 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Location.java
> +import static java.lang.Math.*;
reformat 단축키 누르니까 잘 되네요 ,...!

2024-07-17 08:51 UTC, J-I-H-O requested changes
트레~ 고생했어요
코멘트 확인 부탁드려요!

2024-07-17 08:51 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
> +            .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 사용자 ID입니다."));
#93 
develop 브랜치 rebase 후에 `IllegalArgumnetException` 대신 Custom Exception 사용해주세요!

2024-07-17 08:51 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintQueryService.java
> +    private static final int FOOTPRINT_REMAIN_HOURS = 24;
해당 상수는 실제로 `현재 시간으로 부터 n시간 이내` 를 나타내는데 사용되는 반면, 
`REMAIN_HOURS` 라는 네이밍은 `남은 시간` 이라는 의미가 강한 것 같아요. 조금 더 적절한 네이밍을 고민해보면 좋겠습니다!

2024-07-17 08:51 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Location.java
> +    private double distanceAsMeter(Location other) {
```suggestion
    private double calculateDistanceAsMeter(Location other) {
```
메서드명은 동사로 시작하는게 좋겠습니당

2024-07-17 08:51 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Location.java
>      private double longitude;
약어만 사용하거나, 정확한 표현만 사용하거나 둘 중 하나로 통일하면 좋겠어요.

추가로 약어를 사용하는게 과연 좋을지 잘 모르겠어요.
오랜 시간이 지나고 해당 도메인을 유지보수할 때, `경도` 를 나타내는 표현이 `lon` 이었는지 `lng` 였는지 헷갈리지 않을까요?

또 여러 개발자들과 협업하는 상황에서는 인지 비용을 줄이기 위해서라도 정확한 표현을 사용하는 것이 좋지 않을까 생각합니다. 쿼리 파라미터에서도 사용될 표현이기 때문에 안드로이드 크루들도 인지해야 한다는 점 또한 고려해야겠네요.

개인적으로, 적어도 협업에 있어서는 개발의 간편함 보다는 이해하기 쉬운 코드를 작성하는 것이 더 높은 우선순위를 가져야하지 않나 싶습니다.

투기장 오픈, 아무나 참전 가능(1/8)

2024-07-17 10:31 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/service/FootprintCommandService.java
> +            .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 사용자 ID입니다."));
반영했습니다 👍

2024-07-17 10:32 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Location.java
> +        return abs(dist * 60 * 1.1515 * 1609.344);
이 부분은 어차피 공식이 워낙 복잡해서 하나의 메서드로 가져가도 될 것 같아요...!

2024-07-17 10:34 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Location.java
> +    private double distanceAsMeter(Location other) {
동사로 통일!! 👍

2024-07-17 10:35 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/footprint/domain/Location.java
>      private double longitude;
query parameter를 짧게 가져가고 싶은 욕심이 있었는데, 일관성까지 챙기기는 확실히 어렵네요.

2024-07-18 01:48 UTC, J-I-H-O approved these changes

2024-07-18 02:46 UTC, closed without merging