[BE] 회원 도메인 리팩토링
woowacourse-teams/2024-friendogly pull request #95
Opened 2024-07-17 07:47 UTC by J-I-H-O

## 이슈
- close #80 

## 개발 사항
-회원 도메인 리팩토링 및 테스트 추가

# 전달 사항
- VO 포장은 추후에 필드 많아지면 시도해볼게요!

2024-07-17 08:20 UTC, takoyakimchi requested changes
고생 많으셨습니다 코멘트 몇 개 남겨보았습니다~

2024-07-17 08:20 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/member/domain/MemberTest.java
>      @DisplayName("이름이 1글자 미만 15글자 초과면 예외가 발생한다.")
`@ParameterizedTest`를 사용하는 거라면 하나의 메서드로 합쳐도 좋을 것 같아요.
2개의 메서드로 나누고 싶다면 `hasMessage()`를 써봐도 되겠네요!

2024-07-17 08:20 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/member/controller/MemberControllerTest.java
> +        SaveMemberRequest request = new SaveMemberRequest("15글자를 초과하는 닉네임이다.으아아", "member@email.com");
16글자로 경계값 테스트를 해봐도 될 것 같아요.
`1234567890123456` 이러한 이름이면 16자인지 파악이 쉬울 것 같네요!

2024-07-17 08:20 UTC, takoyakimchi commented on backend/src/test/java/com/woowacourse/friendogly/docs/MemberApiDocsTest.java
> +        SaveMemberResponse response = new SaveMemberResponse(1L, "반갑개", "member@email.com");
request, response 모킹 데이터가 한 곳에 있으니 파악이 쉽네요 👍

2024-07-17 08:20 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/member/dto/request/SaveMemberRequest.java
> +) {
검증에 실패했을 때를 대비해 message를 추가해도 되겠네요.
이 경우 어노테이션이 길어질 것 같으니 개행을 하는 건 어떤가요?

```suggestion
public record SaveMemberRequest(
        @NotBlank(message = "빈 문자열이나 null을 입력할 수 없습니다.")
        @Size(max = 15, message = "닉네임은 1글자 이상 15글자 이하여야 합니다.")
        String name,
        
        @NotBlank(message = "빈 문자열이나 null을 입력할 수 없습니다.")
        @Email(message = "올바른 email 형식이 아닙니다.")
        String email
) {
```

2024-07-17 08:20 UTC, takoyakimchi commented on backend/src/main/java/com/woowacourse/friendogly/member/domain/Member.java
>  @NoArgsConstructor
```suggestion
@NoArgsConstructor(access = AccessLevel.PROTECTED)
```

2024-07-17 09:02 UTC, jimi567 approved these changes, later dismissed

2024-07-17 09:02 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/member/controller/MemberController.java
> +                .body(response);
디테일 굿..

2024-07-17 09:02 UTC, jimi567 commented on backend/src/main/java/com/woowacourse/friendogly/member/dto/response/SaveMemberResponse.java
> +    }
member을 매개변수로 받는 생성자를 새로 하나 만드는건 어떤가요?

다른 분들 의견도 궁금합니다.

2024-07-17 10:55 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/member/dto/request/SaveMemberRequest.java
> +) {
인정합니당~ 
적절한 메시지를 함께 응답해주는게 재시도를 유도하는데 좋겠네요 😊

2024-07-17 10:57 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/member/domain/Member.java
>  @NoArgsConstructor
디테일 굳

2024-07-17 11:20 UTC, ehtjsv2 commented on backend/src/main/java/com/woowacourse/friendogly/member/dto/response/SaveMemberResponse.java
> +    }
Dto라서 어떤 거해도 크게 신경 안쓰지만, 정팩메를 꼭 써야되는 이유가있나요??

2024-07-17 11:31 UTC, takoyakimchi submitted a review, later dismissed

2024-07-17 11:55 UTC, J-I-H-O commented on backend/src/main/java/com/woowacourse/friendogly/member/dto/response/SaveMemberResponse.java
> +    }
흠.. 현재로써는 메리트를 느끼기 어려울지도?
일단 생성자로 다시 돌렸어요. 나중에 필요성이 느껴지면 해봅시다!

2024-07-17 12:05 UTC, takoyakimchi approved these changes
👍

2024-07-18 01:16 UTC, ehtjsv2 approved these changes

2024-07-18 01:23 UTC, merged