[AN] feat: 댕댕이 등록하기
woowacourse-teams/2024-friendogly pull request #98
Opened 2024-07-17 11:44 UTC by junjange

## 이슈
- close #14 

## 개발 사항
- 댕댕이 등록하기 페이지 구현

# 전달 사항 (없으면 삭제해 주세요)
- 태어난 달 선택 바텀시트를 보기 위해서는 최초에 태어난 날을 두 번 클릭해야하는 이슈가 있습니다. 그 이후에는 한 번 클릭해도 바텀 시트가 생깁니다. 이 부분은 나중 PR 때 해결하도록 하겠습니다.

2024-07-18 01:55 UTC, gaeun5744 requested changes
짱짱!!

2024-07-18 01:55 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/bottom/EditDogBirthdayBottomSheet.kt
> +    }
localDateTime에서 내부적으로 1~12 사이의 숫자를 반환한다고 되어있는데, 이 부분을 활용해도 좋을 것 같아요!
![image](https://github.com/user-attachments/assets/ea631814-e3d2-4bcc-9768-e5042d8c4daf)

2024-07-18 01:55 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/bottom/EditDogBirthdayBottomSheet.kt
> +        const val MONTH_PAD_CHAR = '0'
dateTimeFormatter로 변환하는게 가독성 면에서 좋을 것 같습니다!!

2024-07-18 01:55 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/bottom/EditDogProfileImageBottomSheet.kt
> +        }
메서드도 분리해주면 좋을것 같습니다!

2024-07-18 01:55 UTC, gaeun5744 commented on android/app/src/main/res/layout/bottom_sheet_dog_edit_birthday.xml
> +            android:text="언제 태어났나요?"
strings.xml로 빼주세요!!

2024-07-18 01:55 UTC, gaeun5744 commented on android/app/src/main/res/values/themes.xml
> +    </style>
사용하지 않는 style은 삭제해주세요!

2024-07-18 04:39 UTC, jinuemong approved these changes, later dismissed
고생하셨습니다 ~~

2024-07-18 04:39 UTC, jinuemong commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/RegisterDogBindingAdapters.kt
> +        if (length != 0) {
함수로 분리하거나, 어떤 기능을 하는지 직관적이었으면 좋겠습니다.
ex>
```kotlin
val isValid = content?.length ?: 0 !=0
```

2024-07-18 04:39 UTC, jinuemong commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/RegisterDogBindingAdapters.kt
> +    if (dogName != "" && dogDescription != "" && profileImage != null) {
이것도 function으로 분리했으면 좋겠네요

2024-07-18 04:39 UTC, jinuemong commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/bottom/EditDogProfileImageBottomSheet.kt
> +        val gallery = view.findViewById<TextView>(R.id.btn_gallery_select)
bottomSheet는 데이터바인딩 활용을 안하는 편인가요?

2024-07-18 04:39 UTC, jinuemong commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/utils/GlideImageBindingAdapters.kt
> +@BindingAdapter("dogProfile")
BindingAdapter 활용 굳

2024-07-18 06:54 UTC, dpcks0509 approved these changes, later dismissed
고생하셨습니다!

2024-07-18 06:54 UTC, dpcks0509 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/bottom/EditDogProfileImageBottomSheet.kt
> +            bottomSheet.setBackgroundResource(android.R.color.transparent)
저도 바텀시트는 데이터 바인딩을 사용안하는 이유가 궁금합니다! 저는 하나만 데이터바인딩이 필요하더라도 전부 하는 편인데 에디만의 기준이 있는지 궁금해요!

2024-07-18 13:47 UTC, junjange commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/bottom/EditDogBirthdayBottomSheet.kt
> +    }
이부분은 현재 달에 대한 정보를 받아오는 메서드로 활용하지 못할 것 같습니다!!

2024-07-19 00:13 UTC, junjange commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/bottom/EditDogProfileImageBottomSheet.kt
> +        val gallery = view.findViewById<TextView>(R.id.btn_gallery_select)
데이터바인딩 할 게 없다면 안하는 편입니다!

2024-07-19 00:13 UTC, junjange commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/bottom/EditDogProfileImageBottomSheet.kt
> +            bottomSheet.setBackgroundResource(android.R.color.transparent)
데이터바인딩 할 게 없다면 안하는 편입니다!

2024-07-19 00:20 UTC, junjange commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/RegisterDogBindingAdapters.kt
> +        if (length != 0) {
흠 저는 이미 직관적이라고 생각하는데 어떤 부분이 이해가 안됐을까요🥲

2024-07-19 00:48 UTC, jinuemong submitted a review, later dismissed
고생하셨습니다
멍개 화면과 비슷한 화면이 많아서 재활용도 생각해봤으나, ui 동작 기능이 다른부분이 꽤 있어서 별도로 제작해서 사용하겠습니다!! 참고사항

2024-07-19 00:48 UTC, jinuemong commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/RegisterDogFragment.kt
> +    private fun handleCroppedImage(uri: Uri) {
단순질문인데 사용자 동작으로 생성된 객체(여기선 uri)를 변환하는 과정(to multipart)는 뷰모델에서 하는게 좋을까요 뷰에서 처리한 뒤 넘겨주는게 좋을까요

2024-07-19 01:47 UTC, junjange commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/RegisterDogFragment.kt
> +    private fun handleCroppedImage(uri: Uri) {
`context`가 필요한 작업이기 때문에 `Actiivty`/`Fragment`에서 하는게 좋을 것 같다고 생각합니다!!

2024-07-19 05:49 UTC, gaeun5744 approved these changes, later dismissed
고생하셨습니다!

2024-07-19 05:49 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/RegisterDogFragment.kt
> +        }
너무 좋아요!! 👍

2024-07-19 05:49 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/RegisterDogFragment.kt
> +        binding.etDescription.customOnFocusChangeListener(requireContext())
포커싱에 따른 뷰 처리도 context없이 xml에서 처리할 수 있기 때문에 이 방법도 고려하면 좋을 것 같아요!!

2024-07-19 05:49 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/RegisterDogUiState.kt
> +}
나중에 domain 나오면 string.xml로 빼주세요!!

2024-07-19 05:49 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/RegisterDogBindingAdapters.kt
> +    val isProfileComplete = dogName != "" && dogDescription != "" && profileImage != null
`!=""` 대신 isBlank()를 쓰는게 가독성 면에서 좋을것 같아요!!
<img src="https://github.com/user-attachments/assets/4825a566-841f-45fc-b95f-cbcfc5366bf1" width=50%/>

2024-07-19 05:49 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/RegisterDogBindingAdapters.kt
> +    val isProfileComplete = dogName != "" && dogDescription != "" && profileImage != null
이런 비즈니스 로직은 mediator를 이용해 viewModel 내부에서 하는게 좋을 것 같아요!

2024-07-19 05:49 UTC, gaeun5744 commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/RegisterDogBindingAdapters.kt
> +}
이부분도 전부 strings.xml에서 처리하면 좋을 것 같습니다. 그러면 bindingAdapter 하나가 줄어들 것 같아요!

```
%d년 %d월
```

2024-07-19 06:56 UTC, junjange commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/RegisterDogBindingAdapters.kt
> +}
좋습니다!!

2024-07-19 07:12 UTC, junjange commented on android/app/src/main/java/com/woowacourse/friendogly/presentation/ui/registerdog/RegisterDogBindingAdapters.kt
> +    val isProfileComplete = dogName != "" && dogDescription != "" && profileImage != null
좋은 것 같습니다!!

2024-07-19 07:28 UTC, jinuemong approved these changes, later dismissed

2024-07-19 07:29 UTC, gaeun5744 submitted a review, later dismissed

2024-07-19 07:32 UTC, jinuemong approved these changes

2024-07-19 07:33 UTC, dpcks0509 approved these changes
굳!

2024-07-19 07:34 UTC, merged